<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <KrysProjectInclude>$(projectDir)include\</KrysProjectInclude>
  </PropertyGroup>
  <PropertyGroup>
    <IncludePath>$(KrysProjectInclude);$(VC_IncludePath);$(WindowsSDK_IncludePath);</IncludePath>
    <PublicIncludeDirectories>$(KrysProjectInclude);</PublicIncludeDirectories>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <EnableASAN>false</EnableASAN>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level4</WarningLevel>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <TreatWarningAsError>true</TreatWarningAsError>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <LanguageStandard>stdcpp23</LanguageStandard>
      <LanguageStandard_C>stdc17</LanguageStandard_C>
      <AdditionalOptions>/utf-8 /DKRYS_ENV_DEV=1 %(AdditionalOptions)</AdditionalOptions>
      <ObjectFileName>$(IntDir)%(RelativeDir)%(Filename).obj</ObjectFileName>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="KrysProjectInclude">
      <Value>$(KrysProjectInclude)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>