#pragma once

#include "Krystal.Lib/Core/Attributes.hpp"
#include "Krystal.Lib/Mixins/NonCopyable.hpp"
#include "Krystal.Lib/Pointers/RefCounted/RefCountDebugger.hpp"
#include "Krystal.Lib/Types/Numeric.hpp"

namespace Krys
{
  // This base class holds the non-template methods and attributes.
  // The RefCountedWithInlineWeakPtr class inherits from it reducing the template bloat
  // generated by the compiler (technique called template hoisting).
  class KRYS_EMPTY_BASE_CLASS RefCountedWithInlineWeakPtrBase
  {
    using Debugger = RefCountDebugger<uint32>;

  public:
    void ref() const
    {
      m_refCountDebugger.WillAddRef(m_strongCount);
      ++m_strongCount;
    }

    bool hasOneRef() const
    {
      return m_strongCount == 1;
    }
    unsigned refCount() const
    {
      return m_strongCount;
    }

    void weakRef() const
    {
      ++m_weakCount;
    }

    Debugger &refCountDebugger() const
    {
      return const_cast<Debugger &>(m_refCountDebugger);
    }

  protected:
    RefCountedWithInlineWeakPtrBase() = default;

    ~RefCountedWithInlineWeakPtrBase()
    {
      m_refCountDebugger.WillDestroy(m_strongCount);
      assert(m_strongCount == 1);
      m_strongCount = 0;
    }

    // Returns true if the pointer should be destroyed.
    bool derefBase() const
    {
      m_refCountDebugger.WillSubRef(m_strongCount);

      if (m_strongCount != 1)
      {
        --m_strongCount;
        return false;
      }

      m_refCountDebugger.MarkDeletionHasBegun();
      return true;
    }

    // Returns true if the pointer should be freed.
    bool weakDerefBase() const
    {
      if (m_weakCount != 1)
      {
        --m_weakCount;
        return false;
      }

      return true;
    }

  private:
    mutable uint32 m_strongCount {1};
    mutable uint32 m_weakCount {1}; // The strong counts collectively share one weak count.
    KRYS_NO_UNIQUE_ADDRESS Debugger m_refCountDebugger;
  };

  template <typename T>
  class RefCountedWithInlineWeakPtr : public RefCountedWithInlineWeakPtrBase,
                                      public NonCopyable<RefCountedWithInlineWeakPtr>
  {
  public:
    RefCountedWithInlineWeakPtr() = default;

    void deref() const
    {
      if (!derefBase()) [[likely]]
        return;
      derefSlowCase();
    }

    void weakDeref() const
    {
      if (!weakDerefBase()) [[likely]]
        return;
      weakDerefSlowCase();
    }

  private:
    void derefSlowCase() const;
    void weakDerefSlowCase() const;
  };

  template <typename T>
  void RefCountedWithInlineWeakPtr<T>::derefSlowCase() const
  {
    const_cast<T *>(static_cast<const T *>(this))->~T();
    weakDeref();
  }

  template <typename T>
  void RefCountedWithInlineWeakPtr<T>::weakDerefSlowCase() const
  {
    T::operator delete(const_cast<T *>(static_cast<const T *>(this)));
  }
}
