#pragma once

#include "Krystal.Lib/Core/Attributes.hpp"
#include "Krystal.Lib/Core/Concepts.hpp"
#include "Krystal.Lib/Pointers/RawPtr.hpp"
#include "Krystal.Lib/Pointers/RefCounted/RefCountDebugger.hpp"
#include "Krystal.Lib/Types/Numeric.hpp"

namespace Krys
{
  // This base class holds the non-template methods and attributes. The RefCounted class inherits from it
  // reducing the template bloat generated by the compiler (technique called template hoisting).
  class RefCountedBase
  {
    using Debugger = RefCountDebugger<uint32>;

  private:
    mutable uint32 _refCount {1};
    KRYS_NO_UNIQUE_ADDRESS Debugger _refCountDebugger;

  protected:
    RefCountedBase() noexcept = default;

    ~RefCountedBase() noexcept
    {
      _refCountDebugger.WillDestroy(_refCount);
    }

  public:
    void AddRef() const noexcept
    {
      _refCountDebugger.WillAddRef(_refCount);
      ++_refCount;
    }

    KRYS_NODISCARD bool HasOneRef() const noexcept
    {
      return _refCount == 1;
    }

    KRYS_NODISCARD uint32 GetRefCount() const noexcept
    {
      return _refCount;
    }

    KRYS_NODISCARD const Debugger &GetRefCountDebugger() const noexcept
    {
      return _refCountDebugger;
    }

    KRYS_NODISCARD Debugger &GetRefCountDebugger() noexcept
    {
      return _refCountDebugger;
    }

  protected:
    /// @brief Returns true if the pointer should be deleted.
    bool SubRefBase() const noexcept
    {
      _refCountDebugger.WillSubRef(_refCount);

      auto tempCount = _refCount - 1u;
      if (tempCount == 0)
      {
        _refCountDebugger.MarkDeletionHasBegun();
        // Don't save the decremented count, it allows us to detect if someone tries to AddRef or SubRef after
        // deletion has begun.
        return true;
      }

      _refCount = tempCount;
      return false;
    }
  };

  template <typename T>
  class RefCounted : public RefCountedBase
  {
  protected:
    RefCounted() noexcept = default;
    ~RefCounted() noexcept = default;

  public:
    void SubRef() const noexcept
    {
      if (SubRefBase())
      {
        delete const_cast<T *>(static_cast<const T *>(this));
      }
    }
  };
}