// <auto-generated>
//   Generated at 2026-08-13 21:43:25 by css-values.generator.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#include "Krystal.HTML/CSS/Values/Enums/CSSValueId.hpp"

namespace Krys::HTML
{
  template <CSSValueId ValueId>
  struct KeywordConstant
  {
    constexpr static auto value = ValueId;

    constexpr bool operator==(const KeywordConstant<ValueId> &) const = default;
  };

  namespace Keywords
  {
    using Initial = KeywordConstant<CSSValueId::Initial>;
    using Inherit = KeywordConstant<CSSValueId::Inherit>;
    using Unset = KeywordConstant<CSSValueId::Unset>;
    using Revert = KeywordConstant<CSSValueId::Revert>;
    using RevertLayer = KeywordConstant<CSSValueId::RevertLayer>;
    using Auto = KeywordConstant<CSSValueId::Auto>;
    using And = KeywordConstant<CSSValueId::And>;
    using Or = KeywordConstant<CSSValueId::Or>;
    using Not = KeywordConstant<CSSValueId::Not>;
    using Default = KeywordConstant<CSSValueId::Default>;
    using None = KeywordConstant<CSSValueId::None>;
  }
}