/* C++ code produced by gperf version 3.1 */
/* Command-line: 'c:\\ProgramData\\chocolatey\\lib\\gperf\\tools\\gperf.exe' --key-positions='*' -D -n -s 2 --output-file=CSSPropertyId.cpp CSSPropertyId.gperf  */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#line 1 "CSSPropertyId.gperf"

// <auto-generated>
//   Generated at 2026-08-21 18:22:47 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#include "Krystal.HTML/CSS/Properties/Enums/CSSPropertyId.hpp"
#include "Krystal.HTML/CSS/Parser/CSSParserContext.hpp"
#include "Krystal.HTML/CSS/Properties/CSSProperty.hpp"
#include "Krystal.HTML/CSS/Values/Enums/CSSValueId.hpp"
#include "Krystal.Lib/String/String.hpp"
#include "Krystal.Lib/Types/SmallList.hpp"

// Older versions of gperf like to use the `register` keyword.
#define register

namespace Krys::HTML
{
  static_assert(CSSPropertyIdEnumValueCount <= (std::numeric_limits<uint16>::max() + 1), "CSSPropertyId should fit into uint16.");

  const Array<CSSPropertyId, 51> ComputedPropertyIds {
    CSSPropertyId::BackgroundImage,
    CSSPropertyId::CornerBottomLeftShape,
    CSSPropertyId::CornerBottomRightShape,
    CSSPropertyId::CornerEndEndShape,
    CSSPropertyId::CornerEndStartShape,
    CSSPropertyId::CornerStartEndShape,
    CSSPropertyId::CornerStartStartShape,
    CSSPropertyId::CornerTopLeftShape,
    CSSPropertyId::CornerTopRightShape,
    CSSPropertyId::D,
    CSSPropertyId::Direction,
    CSSPropertyId::Display,
    CSSPropertyId::FontFamily,
    CSSPropertyId::FontFeatureSettings,
    CSSPropertyId::FontKerning,
    CSSPropertyId::FontPalette,
    CSSPropertyId::FontSize,
    CSSPropertyId::FontSizeAdjust,
    CSSPropertyId::FontStyle,
    CSSPropertyId::FontSynthesisSmallCaps,
    CSSPropertyId::FontSynthesisStyle,
    CSSPropertyId::FontSynthesisWeight,
    CSSPropertyId::FontVariantAlternates,
    CSSPropertyId::FontVariantCaps,
    CSSPropertyId::FontVariantEastAsian,
    CSSPropertyId::FontVariantEmoji,
    CSSPropertyId::FontVariantLigatures,
    CSSPropertyId::FontVariantNumeric,
    CSSPropertyId::FontVariantPosition,
    CSSPropertyId::FontWeight,
    CSSPropertyId::FontWidth,
    CSSPropertyId::LineHeight,
    CSSPropertyId::MarginBlockEnd,
    CSSPropertyId::MarginBlockStart,
    CSSPropertyId::MarginBottom,
    CSSPropertyId::MarginInlineEnd,
    CSSPropertyId::MarginInlineStart,
    CSSPropertyId::MarginLeft,
    CSSPropertyId::MarginRight,
    CSSPropertyId::MarginTop,
    CSSPropertyId::MarginTrim,
    CSSPropertyId::PaddingBlockEnd,
    CSSPropertyId::PaddingBlockStart,
    CSSPropertyId::PaddingBottom,
    CSSPropertyId::PaddingInlineEnd,
    CSSPropertyId::PaddingInlineStart,
    CSSPropertyId::PaddingLeft,
    CSSPropertyId::PaddingRight,
    CSSPropertyId::PaddingTop,
    CSSPropertyId::WritingMode,
    CSSPropertyId::WebkitFontSmoothing,
  };

  constexpr CSSOMStringView PropertyNameStrings[NumCSSProperties] = {
    u8"writing-mode"
    u8"direction"
    u8"display"
    u8"font-family"
    u8"font-feature-settings"
    u8"font-kerning"
    u8"font-palette"
    u8"font-size"
    u8"font-size-adjust"
    u8"font-style"
    u8"font-synthesis-small-caps"
    u8"font-synthesis-style"
    u8"font-synthesis-weight"
    u8"font-variant-alternates"
    u8"font-variant-caps"
    u8"font-variant-east-asian"
    u8"font-variant-emoji"
    u8"font-variant-ligatures"
    u8"font-variant-numeric"
    u8"font-variant-position"
    u8"font-weight"
    u8"font-width"
    u8"-webkit-font-smoothing"
    u8"background-image"
    u8"d"
    u8"line-height"
    u8"margin-trim"
    u8"corner-bottom-left-shape"
    u8"corner-bottom-right-shape"
    u8"corner-top-left-shape"
    u8"corner-top-right-shape"
    u8"margin-bottom"
    u8"margin-left"
    u8"margin-right"
    u8"margin-top"
    u8"padding-bottom"
    u8"padding-left"
    u8"padding-right"
    u8"padding-top"
    u8"corner-end-end-shape"
    u8"corner-end-start-shape"
    u8"corner-start-end-shape"
    u8"corner-start-start-shape"
    u8"margin-block-end"
    u8"margin-block-start"
    u8"margin-inline-end"
    u8"margin-inline-start"
    u8"padding-block-end"
    u8"padding-block-start"
    u8"padding-inline-end"
    u8"padding-inline-start"
    u8"all"
    u8"corner-shape"
    u8"font"
    u8"font-synthesis"
    u8"font-variant"
    u8"margin"
    u8"margin-block"
    u8"margin-inline"
    u8"padding"
    u8"padding-block"
    u8"padding-inline"
  };

#line 142 "CSSPropertyId.gperf"
struct CSSPropertyHashTableEntry
{
    const char* name;
    uint16 id;
};
enum
  {
    TOTAL_KEYWORDS = 74,
    MIN_WORD_LENGTH = 1,
    MAX_WORD_LENGTH = 25,
    MIN_HASH_VALUE = 5,
    MAX_HASH_VALUE = 530
  };

/* maximum key range = 526, duplicates = 0 */

class CSSPropertyNamesHash
{
private:
  static inline unsigned int hash (const char *str, size_t len);
public:
  static const struct CSSPropertyHashTableEntry *in_word_set (const char *str, size_t len);
};

inline unsigned int
CSSPropertyNamesHash::hash (const char *str, size_t len)
{
  static const unsigned short asso_values[] =
    {
      531, 531, 531, 531, 531, 531, 531, 531, 531, 531,
      531, 531, 531, 531, 531, 531, 531, 531, 531, 531,
      531, 531, 531, 531, 531, 531, 531, 531, 531, 531,
      531, 531, 531, 531, 531, 531, 531, 531, 531, 531,
      531, 531, 531, 531, 531,   5,  20, 531, 531, 531,
      531, 531, 531, 531, 531, 531, 531, 531, 531, 531,
      531, 531, 531, 531, 531, 531, 531, 531, 531, 531,
      531, 531, 531, 531, 531, 531, 531, 531, 531, 531,
      531, 531, 531, 531, 531, 531, 531, 531, 531, 531,
      531, 531, 531, 531, 531, 531, 531,  25,  80,  85,
        5,   5,  15,  20,  20,  15,   0,  90,   0,   0,
        0,   0,   0,   0,   0,  35,   0,   5, 160, 125,
        0, 140,  85, 531, 531, 531, 531, 531, 531
    };
  unsigned int hval = 0;

  switch (len)
    {
      default:
        hval += asso_values[static_cast<unsigned char>(str[24])];
      /*FALLTHROUGH*/
      case 24:
        hval += asso_values[static_cast<unsigned char>(str[23])];
      /*FALLTHROUGH*/
      case 23:
        hval += asso_values[static_cast<unsigned char>(str[22])];
      /*FALLTHROUGH*/
      case 22:
        hval += asso_values[static_cast<unsigned char>(str[21])];
      /*FALLTHROUGH*/
      case 21:
        hval += asso_values[static_cast<unsigned char>(str[20])];
      /*FALLTHROUGH*/
      case 20:
        hval += asso_values[static_cast<unsigned char>(str[19])];
      /*FALLTHROUGH*/
      case 19:
        hval += asso_values[static_cast<unsigned char>(str[18])];
      /*FALLTHROUGH*/
      case 18:
        hval += asso_values[static_cast<unsigned char>(str[17])];
      /*FALLTHROUGH*/
      case 17:
        hval += asso_values[static_cast<unsigned char>(str[16])];
      /*FALLTHROUGH*/
      case 16:
        hval += asso_values[static_cast<unsigned char>(str[15]+1)];
      /*FALLTHROUGH*/
      case 15:
        hval += asso_values[static_cast<unsigned char>(str[14])];
      /*FALLTHROUGH*/
      case 14:
        hval += asso_values[static_cast<unsigned char>(str[13])];
      /*FALLTHROUGH*/
      case 13:
        hval += asso_values[static_cast<unsigned char>(str[12])];
      /*FALLTHROUGH*/
      case 12:
        hval += asso_values[static_cast<unsigned char>(str[11])];
      /*FALLTHROUGH*/
      case 11:
        hval += asso_values[static_cast<unsigned char>(str[10])];
      /*FALLTHROUGH*/
      case 10:
        hval += asso_values[static_cast<unsigned char>(str[9])];
      /*FALLTHROUGH*/
      case 9:
        hval += asso_values[static_cast<unsigned char>(str[8])];
      /*FALLTHROUGH*/
      case 8:
        hval += asso_values[static_cast<unsigned char>(str[7])];
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[static_cast<unsigned char>(str[6])];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[static_cast<unsigned char>(str[5])];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[static_cast<unsigned char>(str[4])];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[static_cast<unsigned char>(str[3])];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[static_cast<unsigned char>(str[2])];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[static_cast<unsigned char>(str[1])];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[static_cast<unsigned char>(str[0])];
        break;
    }
  return hval;
}

static const struct CSSPropertyHashTableEntry wordlist[] =
  {
#line 178 "CSSPropertyId.gperf"
    {"d", static_cast<uint16>(CSSPropertyId::D)},
#line 181 "CSSPropertyId.gperf"
    {"font", static_cast<uint16>(CSSPropertyId::Font)},
#line 167 "CSSPropertyId.gperf"
    {"all", static_cast<uint16>(CSSPropertyId::All)},
#line 185 "CSSPropertyId.gperf"
    {"font-palette", static_cast<uint16>(CSSPropertyId::FontPalette)},
#line 205 "CSSPropertyId.gperf"
    {"margin", static_cast<uint16>(CSSPropertyId::Margin)},
#line 215 "CSSPropertyId.gperf"
    {"margin-top", static_cast<uint16>(CSSPropertyId::MarginTop)},
#line 217 "CSSPropertyId.gperf"
    {"padding", static_cast<uint16>(CSSPropertyId::Padding)},
#line 227 "CSSPropertyId.gperf"
    {"padding-top", static_cast<uint16>(CSSPropertyId::PaddingTop)},
#line 216 "CSSPropertyId.gperf"
    {"margin-trim", static_cast<uint16>(CSSPropertyId::MarginTrim)},
#line 213 "CSSPropertyId.gperf"
    {"margin-left", static_cast<uint16>(CSSPropertyId::MarginLeft)},
#line 225 "CSSPropertyId.gperf"
    {"padding-left", static_cast<uint16>(CSSPropertyId::PaddingLeft)},
#line 210 "CSSPropertyId.gperf"
    {"margin-inline", static_cast<uint16>(CSSPropertyId::MarginInline)},
#line 204 "CSSPropertyId.gperf"
    {"line-height", static_cast<uint16>(CSSPropertyId::LineHeight)},
#line 222 "CSSPropertyId.gperf"
    {"padding-inline", static_cast<uint16>(CSSPropertyId::PaddingInline)},
#line 211 "CSSPropertyId.gperf"
    {"margin-inline-end", static_cast<uint16>(CSSPropertyId::MarginInlineEnd)},
#line 214 "CSSPropertyId.gperf"
    {"margin-right", static_cast<uint16>(CSSPropertyId::MarginRight)},
#line 179 "CSSPropertyId.gperf"
    {"direction", static_cast<uint16>(CSSPropertyId::Direction)},
#line 226 "CSSPropertyId.gperf"
    {"padding-right", static_cast<uint16>(CSSPropertyId::PaddingRight)},
#line 223 "CSSPropertyId.gperf"
    {"padding-inline-end", static_cast<uint16>(CSSPropertyId::PaddingInlineEnd)},
#line 224 "CSSPropertyId.gperf"
    {"padding-inline-start", static_cast<uint16>(CSSPropertyId::PaddingInlineStart)},
#line 209 "CSSPropertyId.gperf"
    {"margin-bottom", static_cast<uint16>(CSSPropertyId::MarginBottom)},
#line 184 "CSSPropertyId.gperf"
    {"font-kerning", static_cast<uint16>(CSSPropertyId::FontKerning)},
#line 221 "CSSPropertyId.gperf"
    {"padding-bottom", static_cast<uint16>(CSSPropertyId::PaddingBottom)},
#line 186 "CSSPropertyId.gperf"
    {"font-size", static_cast<uint16>(CSSPropertyId::FontSize)},
#line 188 "CSSPropertyId.gperf"
    {"font-stretch", static_cast<uint16>(CSSPropertyId::FontWidth)},
#line 212 "CSSPropertyId.gperf"
    {"margin-inline-start", static_cast<uint16>(CSSPropertyId::MarginInlineStart)},
#line 171 "CSSPropertyId.gperf"
    {"corner-end-end-shape", static_cast<uint16>(CSSPropertyId::CornerEndEndShape)},
#line 173 "CSSPropertyId.gperf"
    {"corner-shape", static_cast<uint16>(CSSPropertyId::CornerShape)},
#line 203 "CSSPropertyId.gperf"
    {"font-width", static_cast<uint16>(CSSPropertyId::FontWidth)},
#line 228 "CSSPropertyId.gperf"
    {"writing-mode", static_cast<uint16>(CSSPropertyId::WritingMode)},
#line 183 "CSSPropertyId.gperf"
    {"font-feature-settings", static_cast<uint16>(CSSPropertyId::FontFeatureSettings)},
#line 189 "CSSPropertyId.gperf"
    {"font-style", static_cast<uint16>(CSSPropertyId::FontStyle)},
#line 202 "CSSPropertyId.gperf"
    {"font-weight", static_cast<uint16>(CSSPropertyId::FontWeight)},
#line 182 "CSSPropertyId.gperf"
    {"font-family", static_cast<uint16>(CSSPropertyId::FontFamily)},
#line 180 "CSSPropertyId.gperf"
    {"display", static_cast<uint16>(CSSPropertyId::Display)},
#line 176 "CSSPropertyId.gperf"
    {"corner-top-left-shape", static_cast<uint16>(CSSPropertyId::CornerTopLeftShape)},
#line 187 "CSSPropertyId.gperf"
    {"font-size-adjust", static_cast<uint16>(CSSPropertyId::FontSizeAdjust)},
#line 194 "CSSPropertyId.gperf"
    {"font-variant", static_cast<uint16>(CSSPropertyId::FontVariant)},
#line 177 "CSSPropertyId.gperf"
    {"corner-top-right-shape", static_cast<uint16>(CSSPropertyId::CornerTopRightShape)},
#line 174 "CSSPropertyId.gperf"
    {"corner-start-end-shape", static_cast<uint16>(CSSPropertyId::CornerStartEndShape)},
#line 172 "CSSPropertyId.gperf"
    {"corner-end-start-shape", static_cast<uint16>(CSSPropertyId::CornerEndStartShape)},
#line 198 "CSSPropertyId.gperf"
    {"font-variant-emoji", static_cast<uint16>(CSSPropertyId::FontVariantEmoji)},
#line 201 "CSSPropertyId.gperf"
    {"font-variant-position", static_cast<uint16>(CSSPropertyId::FontVariantPosition)},
#line 155 "CSSPropertyId.gperf"
    {"-epub-writing-mode", static_cast<uint16>(CSSPropertyId::WritingMode)},
#line 169 "CSSPropertyId.gperf"
    {"corner-bottom-left-shape", static_cast<uint16>(CSSPropertyId::CornerBottomLeftShape)},
#line 190 "CSSPropertyId.gperf"
    {"font-synthesis", static_cast<uint16>(CSSPropertyId::FontSynthesis)},
#line 170 "CSSPropertyId.gperf"
    {"corner-bottom-right-shape", static_cast<uint16>(CSSPropertyId::CornerBottomRightShape)},
#line 206 "CSSPropertyId.gperf"
    {"margin-block", static_cast<uint16>(CSSPropertyId::MarginBlock)},
#line 218 "CSSPropertyId.gperf"
    {"padding-block", static_cast<uint16>(CSSPropertyId::PaddingBlock)},
#line 207 "CSSPropertyId.gperf"
    {"margin-block-end", static_cast<uint16>(CSSPropertyId::MarginBlockEnd)},
#line 219 "CSSPropertyId.gperf"
    {"padding-block-end", static_cast<uint16>(CSSPropertyId::PaddingBlockEnd)},
#line 195 "CSSPropertyId.gperf"
    {"font-variant-alternates", static_cast<uint16>(CSSPropertyId::FontVariantAlternates)},
#line 199 "CSSPropertyId.gperf"
    {"font-variant-ligatures", static_cast<uint16>(CSSPropertyId::FontVariantLigatures)},
#line 200 "CSSPropertyId.gperf"
    {"font-variant-numeric", static_cast<uint16>(CSSPropertyId::FontVariantNumeric)},
#line 175 "CSSPropertyId.gperf"
    {"corner-start-start-shape", static_cast<uint16>(CSSPropertyId::CornerStartStartShape)},
#line 193 "CSSPropertyId.gperf"
    {"font-synthesis-weight", static_cast<uint16>(CSSPropertyId::FontSynthesisWeight)},
#line 197 "CSSPropertyId.gperf"
    {"font-variant-east-asian", static_cast<uint16>(CSSPropertyId::FontVariantEastAsian)},
#line 168 "CSSPropertyId.gperf"
    {"background-image", static_cast<uint16>(CSSPropertyId::BackgroundImage)},
#line 196 "CSSPropertyId.gperf"
    {"font-variant-caps", static_cast<uint16>(CSSPropertyId::FontVariantCaps)},
#line 220 "CSSPropertyId.gperf"
    {"padding-block-start", static_cast<uint16>(CSSPropertyId::PaddingBlockStart)},
#line 160 "CSSPropertyId.gperf"
    {"-webkit-margin-end", static_cast<uint16>(CSSPropertyId::MarginInlineEnd)},
#line 161 "CSSPropertyId.gperf"
    {"-webkit-margin-start", static_cast<uint16>(CSSPropertyId::MarginInlineStart)},
#line 164 "CSSPropertyId.gperf"
    {"-webkit-padding-end", static_cast<uint16>(CSSPropertyId::PaddingInlineEnd)},
#line 157 "CSSPropertyId.gperf"
    {"-webkit-font-smoothing", static_cast<uint16>(CSSPropertyId::WebkitFontSmoothing)},
#line 208 "CSSPropertyId.gperf"
    {"margin-block-start", static_cast<uint16>(CSSPropertyId::MarginBlockStart)},
#line 192 "CSSPropertyId.gperf"
    {"font-synthesis-style", static_cast<uint16>(CSSPropertyId::FontSynthesisStyle)},
#line 162 "CSSPropertyId.gperf"
    {"-webkit-padding-after", static_cast<uint16>(CSSPropertyId::PaddingBlockEnd)},
#line 165 "CSSPropertyId.gperf"
    {"-webkit-padding-start", static_cast<uint16>(CSSPropertyId::PaddingInlineStart)},
#line 191 "CSSPropertyId.gperf"
    {"font-synthesis-small-caps", static_cast<uint16>(CSSPropertyId::FontSynthesisSmallCaps)},
#line 158 "CSSPropertyId.gperf"
    {"-webkit-margin-after", static_cast<uint16>(CSSPropertyId::MarginBlockEnd)},
#line 159 "CSSPropertyId.gperf"
    {"-webkit-margin-before", static_cast<uint16>(CSSPropertyId::MarginBlockStart)},
#line 156 "CSSPropertyId.gperf"
    {"-webkit-font-kerning", static_cast<uint16>(CSSPropertyId::FontKerning)},
#line 163 "CSSPropertyId.gperf"
    {"-webkit-padding-before", static_cast<uint16>(CSSPropertyId::PaddingBlockStart)},
#line 166 "CSSPropertyId.gperf"
    {"-webkit-writing-mode", static_cast<uint16>(CSSPropertyId::WritingMode)}
  };

static const signed char lookup[] =
  {
    -1, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1,
    -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  2, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  3,
    -1, -1, -1, -1,  4, -1, -1, -1, -1,  5, -1, -1, -1, -1,
     6, -1, -1, -1, -1,  7, -1, -1, -1, -1,  8, -1, -1, -1,
    -1,  9, -1, -1, -1, -1, -1, -1, -1, -1, -1, 10, -1, -1,
    -1, -1, 11, -1, -1, -1, -1, 12, -1, -1, -1, -1, 13, -1,
    -1, -1, -1, 14, -1, -1, -1, -1, 15, -1, -1, -1, -1, 16,
    -1, -1, -1, -1, 17, -1, -1, -1, -1, 18, -1, -1, -1, -1,
    19, -1, -1, -1, -1, 20, -1, -1, -1, -1, 21, -1, -1, -1,
    -1, 22, -1, -1, -1, -1, 23, -1, -1, -1, -1, 24, -1, -1,
    -1, -1, 25, -1, -1, -1, -1, 26, -1, -1, -1, -1, 27, -1,
    -1, -1, -1, 28, -1, -1, -1, -1, 29, -1, -1, -1, -1, 30,
    -1, -1, -1, -1, 31, -1, -1, -1, -1, 32, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, 33, -1, -1, -1, -1, 34, -1, -1, -1,
    -1, 35, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, 36, -1, -1, -1, -1, 37, -1, -1, -1, -1, 38, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, 39, -1, -1, -1, -1, 40,
    -1, -1, -1, -1, 41, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    42, -1, -1, -1, -1, -1, -1, -1, -1, -1, 43, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, 44, -1, -1, -1, -1, 45, -1, -1,
    -1, -1, 46, -1, -1, -1, -1, -1, -1, -1, -1, -1, 47, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, 48, -1, -1, -1, -1, 49,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, 50, -1, -1, -1, -1,
    51, -1, -1, -1, -1, 52, -1, -1, -1, -1, 53, -1, -1, -1,
    -1, 54, -1, -1, -1, -1, 55, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, 56, -1, -1, -1, -1, 57, -1,
    -1, -1, -1, 58, -1, -1, -1, -1, 59, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, 60, -1, -1, -1, -1, 61, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, 62, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, 63, -1, -1, -1, -1, 64, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, 65, -1, -1, -1, -1, 66, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 67,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, 68, -1, -1, -1, -1,
    69, -1, -1, -1, -1, -1, -1, -1, -1, -1, 70, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, 71, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, 72, -1, -1, -1, -1, -1, -1, -1, -1, -1, 73
  };

const struct CSSPropertyHashTableEntry *
CSSPropertyNamesHash::in_word_set (const char *str, size_t len)
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          int index = lookup[key];

          if (index >= 0)
            {
              const char *s = wordlist[index].name;

              if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
                return &wordlist[index];
            }
        }
    }
  return 0;
}
#line 229 "CSSPropertyId.gperf"

  CSSPropertyId FindCSSProperty(CSSOMStringView characters) noexcept
  {
    auto* value = CSSPropertyNamesHash::in_word_set(reinterpret_cast<const char*>(characters.data()), characters.length());
    return value ? static_cast<CSSPropertyId>(value->id) : CSSPropertyId::Invalid;
  }

  CSSOMStringView ToString(CSSPropertyId id) noexcept
  {
    auto value = static_cast<uint16>(id);
    if (value < FirstCSSProperty)
    {
      return {};
    }

    size_t index = value - FirstCSSProperty;
    if (index >= NumCSSProperties)
    {
      return {};
    }

    return PropertyNameStrings[index];
  }

  bool IsInternal(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  namespace
  {
    KRYS_NODISCARD bool IsExposedNotInvalidAndNotInternal(CSSPropertyId id, const CSSPropertySettings &settings) noexcept
    {
      switch (id)
      {
        case CSSPropertyId::FontVariantEmoji:
        {
          return settings.FontVariantEmojiPropertyEnabled;
        }
        case CSSPropertyId::D:
        {
          return settings.DPropertyEnabled;
        }
        case CSSPropertyId::CornerBottomLeftShape:
        case CSSPropertyId::CornerBottomRightShape:
        case CSSPropertyId::CornerTopLeftShape:
        case CSSPropertyId::CornerTopRightShape:
        case CSSPropertyId::CornerEndEndShape:
        case CSSPropertyId::CornerEndStartShape:
        case CSSPropertyId::CornerStartEndShape:
        case CSSPropertyId::CornerStartStartShape:
        case CSSPropertyId::CornerShape:
        {
          return settings.CornerShapePropertyEnabled;
        }
        default:
        {
          return true;
        }
      }
    }


    KRYS_NODISCARD bool IsExposed(CSSPropertyId id, const CSSPropertySettings* settings) noexcept
    {
      if (id == CSSPropertyId::Invalid || IsInternal(id))
      {
        return false;
      }

      if (!settings)
      {
        return true;
      }

      return IsExposedNotInvalidAndNotInternal(id, *settings);
    }

    KRYS_NODISCARD bool IsExposed(CSSPropertyId id, const CSSPropertySettings& settings) noexcept
    {
      if (id == CSSPropertyId::Invalid || IsInternal(id))
      {
        return false;
      }

      return IsExposedNotInvalidAndNotInternal(id, settings);
    }

  }
  constexpr bool IsInheritedPropertyTable[CSSPropertyIdEnumValueCount] = {
    false, // CSSPropertyId::Invalid
    true , // CSSPropertyId::Custom
    true , // CSSPropertyId::WritingMode
    true , // CSSPropertyId::Direction
    false, // CSSPropertyId::Display
    true , // CSSPropertyId::FontFamily
    true , // CSSPropertyId::FontFeatureSettings
    true , // CSSPropertyId::FontKerning
    true , // CSSPropertyId::FontPalette
    true , // CSSPropertyId::FontSize
    true , // CSSPropertyId::FontSizeAdjust
    true , // CSSPropertyId::FontStyle
    true , // CSSPropertyId::FontSynthesisSmallCaps
    true , // CSSPropertyId::FontSynthesisStyle
    true , // CSSPropertyId::FontSynthesisWeight
    true , // CSSPropertyId::FontVariantAlternates
    true , // CSSPropertyId::FontVariantCaps
    true , // CSSPropertyId::FontVariantEastAsian
    true , // CSSPropertyId::FontVariantEmoji
    true , // CSSPropertyId::FontVariantLigatures
    true , // CSSPropertyId::FontVariantNumeric
    true , // CSSPropertyId::FontVariantPosition
    true , // CSSPropertyId::FontWeight
    true , // CSSPropertyId::FontWidth
    true , // CSSPropertyId::WebkitFontSmoothing
    false, // CSSPropertyId::BackgroundImage
    false, // CSSPropertyId::D
    true , // CSSPropertyId::LineHeight
    false, // CSSPropertyId::MarginTrim
    false, // CSSPropertyId::CornerBottomLeftShape
    false, // CSSPropertyId::CornerBottomRightShape
    false, // CSSPropertyId::CornerTopLeftShape
    false, // CSSPropertyId::CornerTopRightShape
    false, // CSSPropertyId::MarginBottom
    false, // CSSPropertyId::MarginLeft
    false, // CSSPropertyId::MarginRight
    false, // CSSPropertyId::MarginTop
    false, // CSSPropertyId::PaddingBottom
    false, // CSSPropertyId::PaddingLeft
    false, // CSSPropertyId::PaddingRight
    false, // CSSPropertyId::PaddingTop
    false, // CSSPropertyId::CornerEndEndShape
    false, // CSSPropertyId::CornerEndStartShape
    false, // CSSPropertyId::CornerStartEndShape
    false, // CSSPropertyId::CornerStartStartShape
    false, // CSSPropertyId::MarginBlockEnd
    false, // CSSPropertyId::MarginBlockStart
    false, // CSSPropertyId::MarginInlineEnd
    false, // CSSPropertyId::MarginInlineStart
    false, // CSSPropertyId::PaddingBlockEnd
    false, // CSSPropertyId::PaddingBlockStart
    false, // CSSPropertyId::PaddingInlineEnd
    false, // CSSPropertyId::PaddingInlineStart
    false, // CSSPropertyId::All
    false, // CSSPropertyId::CornerShape
    true , // CSSPropertyId::Font
    true , // CSSPropertyId::FontSynthesis
    true , // CSSPropertyId::FontVariant
    false, // CSSPropertyId::Margin
    false, // CSSPropertyId::MarginBlock
    false, // CSSPropertyId::MarginInline
    false, // CSSPropertyId::Padding
    false, // CSSPropertyId::PaddingBlock
    false, // CSSPropertyId::PaddingInline
  };

  bool CSSProperty::IsInheritedProperty(CSSPropertyId id) noexcept
  {
    assert(static_cast<size_t>(id) < CSSPropertyIdEnumValueCount);
    assert(id != CSSPropertyId::Invalid);
    return IsInheritedPropertyTable[static_cast<size_t>(id)];
  }

  CSSPropertyId CascadeAliasProperty(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      default:
      {
        return id;
      }
    }
  }

  SmallList<CSSOMString> CSSProperty::AliasesForProperty(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::WritingMode:
      {
        return { u8"-webkit-writing-mode", u8"-epub-writing-mode" };
      }
      case CSSPropertyId::FontKerning:
      {
        return { u8"-webkit-font-kerning" };
      }
      case CSSPropertyId::FontWidth:
      {
        return { u8"font-stretch" };
      }
      case CSSPropertyId::MarginBlockEnd:
      {
        return { u8"-webkit-margin-after" };
      }
      case CSSPropertyId::MarginBlockStart:
      {
        return { u8"-webkit-margin-before" };
      }
      case CSSPropertyId::MarginInlineEnd:
      {
        return { u8"-webkit-margin-end" };
      }
      case CSSPropertyId::MarginInlineStart:
      {
        return { u8"-webkit-margin-start" };
      }
      case CSSPropertyId::PaddingBlockEnd:
      {
        return { u8"-webkit-padding-after" };
      }
      case CSSPropertyId::PaddingBlockStart:
      {
        return { u8"-webkit-padding-before" };
      }
      case CSSPropertyId::PaddingInlineEnd:
      {
        return { u8"-webkit-padding-end" };
      }
      case CSSPropertyId::PaddingInlineStart:
      {
        return { u8"-webkit-padding-start" };
      }
      default:
      {
        return {};
      }
    }
  }

  char32 CSSProperty::ListValuedPropertySeparator(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::FontSizeAdjust:
      case CSSPropertyId::BackgroundImage:
      {
        return ' ';
      }
      default:
      {
        break;
      }
    }
    return '\0';
  }

  bool CSSProperty::AllowsNumberOrIntegerInput(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::FontSizeAdjust:
      case CSSPropertyId::LineHeight:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSProperty::DisablesNativeAppearance(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::BackgroundImage:
      case CSSPropertyId::CornerBottomLeftShape:
      case CSSPropertyId::CornerBottomRightShape:
      case CSSPropertyId::CornerTopLeftShape:
      case CSSPropertyId::CornerTopRightShape:
      case CSSPropertyId::CornerEndEndShape:
      case CSSPropertyId::CornerEndStartShape:
      case CSSPropertyId::CornerStartEndShape:
      case CSSPropertyId::CornerStartStartShape:
      case CSSPropertyId::CornerShape:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSProperty::IsCornerShapeProperty(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::CornerBottomLeftShape:
      case CSSPropertyId::CornerBottomRightShape:
      case CSSPropertyId::CornerEndEndShape:
      case CSSPropertyId::CornerEndStartShape:
      case CSSPropertyId::CornerShape:
      case CSSPropertyId::CornerStartEndShape:
      case CSSPropertyId::CornerStartStartShape:
      case CSSPropertyId::CornerTopLeftShape:
      case CSSPropertyId::CornerTopRightShape:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSProperty::IsMarginProperty(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::Margin:
      case CSSPropertyId::MarginBlock:
      case CSSPropertyId::MarginBlockEnd:
      case CSSPropertyId::MarginBlockStart:
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginInline:
      case CSSPropertyId::MarginInlineEnd:
      case CSSPropertyId::MarginInlineStart:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSProperty::IsPaddingProperty(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::Padding:
      case CSSPropertyId::PaddingBlock:
      case CSSPropertyId::PaddingBlockEnd:
      case CSSPropertyId::PaddingBlockStart:
      case CSSPropertyId::PaddingBottom:
      case CSSPropertyId::PaddingInline:
      case CSSPropertyId::PaddingInlineEnd:
      case CSSPropertyId::PaddingInlineStart:
      case CSSPropertyId::PaddingLeft:
      case CSSPropertyId::PaddingRight:
      case CSSPropertyId::PaddingTop:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSProperty::IsInLogicalPropertyGroup(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::CornerEndEndShape:
      case CSSPropertyId::CornerEndStartShape:
      case CSSPropertyId::CornerStartEndShape:
      case CSSPropertyId::CornerStartStartShape:
      case CSSPropertyId::CornerBottomLeftShape:
      case CSSPropertyId::CornerBottomRightShape:
      case CSSPropertyId::CornerTopLeftShape:
      case CSSPropertyId::CornerTopRightShape:
      case CSSPropertyId::MarginBlockEnd:
      case CSSPropertyId::MarginBlockStart:
      case CSSPropertyId::MarginInlineEnd:
      case CSSPropertyId::MarginInlineStart:
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      case CSSPropertyId::PaddingBlockEnd:
      case CSSPropertyId::PaddingBlockStart:
      case CSSPropertyId::PaddingInlineEnd:
      case CSSPropertyId::PaddingInlineStart:
      case CSSPropertyId::PaddingBottom:
      case CSSPropertyId::PaddingLeft:
      case CSSPropertyId::PaddingRight:
      case CSSPropertyId::PaddingTop:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSProperty::AreInSameLogicalPropertyGroupWithDifferentMappingLogic(CSSPropertyId id1, CSSPropertyId id2) noexcept
  {
    switch (id1)
    {
      case CSSPropertyId::CornerEndEndShape:
      case CSSPropertyId::CornerEndStartShape:
      case CSSPropertyId::CornerStartEndShape:
      case CSSPropertyId::CornerStartStartShape:
      {
        switch (id2)
        {
          case CSSPropertyId::CornerBottomLeftShape:
          case CSSPropertyId::CornerBottomRightShape:
          case CSSPropertyId::CornerTopLeftShape:
          case CSSPropertyId::CornerTopRightShape:
          {
            return true;
          }
          default:
          {
            return false;
          }
        }
      }
      case CSSPropertyId::CornerBottomLeftShape:
      case CSSPropertyId::CornerBottomRightShape:
      case CSSPropertyId::CornerTopLeftShape:
      case CSSPropertyId::CornerTopRightShape:
      {
        switch (id2)
        {
          case CSSPropertyId::CornerEndEndShape:
          case CSSPropertyId::CornerEndStartShape:
          case CSSPropertyId::CornerStartEndShape:
          case CSSPropertyId::CornerStartStartShape:
          {
            return true;
          }
          default:
          {
            return false;
          }
        }
      }
      case CSSPropertyId::MarginBlockEnd:
      case CSSPropertyId::MarginBlockStart:
      case CSSPropertyId::MarginInlineEnd:
      case CSSPropertyId::MarginInlineStart:
      {
        switch (id2)
        {
          case CSSPropertyId::MarginBottom:
          case CSSPropertyId::MarginLeft:
          case CSSPropertyId::MarginRight:
          case CSSPropertyId::MarginTop:
          {
            return true;
          }
          default:
          {
            return false;
          }
        }
      }
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      {
        switch (id2)
        {
          case CSSPropertyId::MarginBlockEnd:
          case CSSPropertyId::MarginBlockStart:
          case CSSPropertyId::MarginInlineEnd:
          case CSSPropertyId::MarginInlineStart:
          {
            return true;
          }
          default:
          {
            return false;
          }
        }
      }
      case CSSPropertyId::PaddingBlockEnd:
      case CSSPropertyId::PaddingBlockStart:
      case CSSPropertyId::PaddingInlineEnd:
      case CSSPropertyId::PaddingInlineStart:
      {
        switch (id2)
        {
          case CSSPropertyId::PaddingBottom:
          case CSSPropertyId::PaddingLeft:
          case CSSPropertyId::PaddingRight:
          case CSSPropertyId::PaddingTop:
          {
            return true;
          }
          default:
          {
            return false;
          }
        }
      }
      case CSSPropertyId::PaddingBottom:
      case CSSPropertyId::PaddingLeft:
      case CSSPropertyId::PaddingRight:
      case CSSPropertyId::PaddingTop:
      {
        switch (id2)
        {
          case CSSPropertyId::PaddingBlockEnd:
          case CSSPropertyId::PaddingBlockStart:
          case CSSPropertyId::PaddingInlineEnd:
          case CSSPropertyId::PaddingInlineStart:
          {
            return true;
          }
          default:
          {
            return false;
          }
        }
      }
      default:
      {
        return false;
      }
    }
  }

  CSSPropertyId CSSProperty::ResolveDirectionAwareProperty(CSSPropertyId id, WritingMode writingMode) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::CornerEndEndShape:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::CornerTopLeftShape, CSSPropertyId::CornerTopRightShape, CSSPropertyId::CornerBottomLeftShape, CSSPropertyId::CornerBottomRightShape };
        return properties[static_cast<size_t>(MapCornerLogicalToPhysical(writingMode, LogicalBoxCorner::EndEnd))];
      }
      case CSSPropertyId::CornerEndStartShape:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::CornerTopLeftShape, CSSPropertyId::CornerTopRightShape, CSSPropertyId::CornerBottomLeftShape, CSSPropertyId::CornerBottomRightShape };
        return properties[static_cast<size_t>(MapCornerLogicalToPhysical(writingMode, LogicalBoxCorner::EndStart))];
      }
      case CSSPropertyId::CornerStartEndShape:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::CornerTopLeftShape, CSSPropertyId::CornerTopRightShape, CSSPropertyId::CornerBottomLeftShape, CSSPropertyId::CornerBottomRightShape };
        return properties[static_cast<size_t>(MapCornerLogicalToPhysical(writingMode, LogicalBoxCorner::StartEnd))];
      }
      case CSSPropertyId::CornerStartStartShape:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::CornerTopLeftShape, CSSPropertyId::CornerTopRightShape, CSSPropertyId::CornerBottomLeftShape, CSSPropertyId::CornerBottomRightShape };
        return properties[static_cast<size_t>(MapCornerLogicalToPhysical(writingMode, LogicalBoxCorner::StartStart))];
      }
      case CSSPropertyId::MarginBlockEnd:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::MarginTop, CSSPropertyId::MarginRight, CSSPropertyId::MarginBottom, CSSPropertyId::MarginLeft };
        return properties[static_cast<size_t>(MapSideLogicalToPhysical(writingMode, LogicalBoxSide::BlockEnd))];
      }
      case CSSPropertyId::MarginBlockStart:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::MarginTop, CSSPropertyId::MarginRight, CSSPropertyId::MarginBottom, CSSPropertyId::MarginLeft };
        return properties[static_cast<size_t>(MapSideLogicalToPhysical(writingMode, LogicalBoxSide::BlockStart))];
      }
      case CSSPropertyId::MarginInlineEnd:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::MarginTop, CSSPropertyId::MarginRight, CSSPropertyId::MarginBottom, CSSPropertyId::MarginLeft };
        return properties[static_cast<size_t>(MapSideLogicalToPhysical(writingMode, LogicalBoxSide::InlineEnd))];
      }
      case CSSPropertyId::MarginInlineStart:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::MarginTop, CSSPropertyId::MarginRight, CSSPropertyId::MarginBottom, CSSPropertyId::MarginLeft };
        return properties[static_cast<size_t>(MapSideLogicalToPhysical(writingMode, LogicalBoxSide::InlineStart))];
      }
      case CSSPropertyId::PaddingBlockEnd:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::PaddingTop, CSSPropertyId::PaddingRight, CSSPropertyId::PaddingBottom, CSSPropertyId::PaddingLeft };
        return properties[static_cast<size_t>(MapSideLogicalToPhysical(writingMode, LogicalBoxSide::BlockEnd))];
      }
      case CSSPropertyId::PaddingBlockStart:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::PaddingTop, CSSPropertyId::PaddingRight, CSSPropertyId::PaddingBottom, CSSPropertyId::PaddingLeft };
        return properties[static_cast<size_t>(MapSideLogicalToPhysical(writingMode, LogicalBoxSide::BlockStart))];
      }
      case CSSPropertyId::PaddingInlineEnd:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::PaddingTop, CSSPropertyId::PaddingRight, CSSPropertyId::PaddingBottom, CSSPropertyId::PaddingLeft };
        return properties[static_cast<size_t>(MapSideLogicalToPhysical(writingMode, LogicalBoxSide::InlineEnd))];
      }
      case CSSPropertyId::PaddingInlineStart:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::PaddingTop, CSSPropertyId::PaddingRight, CSSPropertyId::PaddingBottom, CSSPropertyId::PaddingLeft };
        return properties[static_cast<size_t>(MapSideLogicalToPhysical(writingMode, LogicalBoxSide::InlineStart))];
      }
      default:
      {
        return id;
      }
    }
  }

  CSSPropertyId CSSProperty::UnresolvePhysicalProperty(CSSPropertyId id, WritingMode writingMode) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::CornerBottomLeftShape:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::CornerStartStartShape, CSSPropertyId::CornerStartEndShape, CSSPropertyId::CornerEndStartShape, CSSPropertyId::CornerEndEndShape };
        return properties[static_cast<size_t>(MapCornerPhysicalToLogical(writingMode, BoxCorner::BottomLeft))];
      }
      case CSSPropertyId::CornerBottomRightShape:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::CornerStartStartShape, CSSPropertyId::CornerStartEndShape, CSSPropertyId::CornerEndStartShape, CSSPropertyId::CornerEndEndShape };
        return properties[static_cast<size_t>(MapCornerPhysicalToLogical(writingMode, BoxCorner::BottomRight))];
      }
      case CSSPropertyId::CornerTopLeftShape:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::CornerStartStartShape, CSSPropertyId::CornerStartEndShape, CSSPropertyId::CornerEndStartShape, CSSPropertyId::CornerEndEndShape };
        return properties[static_cast<size_t>(MapCornerPhysicalToLogical(writingMode, BoxCorner::TopLeft))];
      }
      case CSSPropertyId::CornerTopRightShape:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::CornerStartStartShape, CSSPropertyId::CornerStartEndShape, CSSPropertyId::CornerEndStartShape, CSSPropertyId::CornerEndEndShape };
        return properties[static_cast<size_t>(MapCornerPhysicalToLogical(writingMode, BoxCorner::TopRight))];
      }
      case CSSPropertyId::MarginBottom:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::MarginBlockStart, CSSPropertyId::MarginInlineEnd, CSSPropertyId::MarginBlockEnd, CSSPropertyId::MarginInlineStart };
        return properties[static_cast<size_t>(MapSidePhysicalToLogical(writingMode, BoxSide::Bottom))];
      }
      case CSSPropertyId::MarginLeft:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::MarginBlockStart, CSSPropertyId::MarginInlineEnd, CSSPropertyId::MarginBlockEnd, CSSPropertyId::MarginInlineStart };
        return properties[static_cast<size_t>(MapSidePhysicalToLogical(writingMode, BoxSide::Left))];
      }
      case CSSPropertyId::MarginRight:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::MarginBlockStart, CSSPropertyId::MarginInlineEnd, CSSPropertyId::MarginBlockEnd, CSSPropertyId::MarginInlineStart };
        return properties[static_cast<size_t>(MapSidePhysicalToLogical(writingMode, BoxSide::Right))];
      }
      case CSSPropertyId::MarginTop:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::MarginBlockStart, CSSPropertyId::MarginInlineEnd, CSSPropertyId::MarginBlockEnd, CSSPropertyId::MarginInlineStart };
        return properties[static_cast<size_t>(MapSidePhysicalToLogical(writingMode, BoxSide::Top))];
      }
      case CSSPropertyId::PaddingBottom:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::PaddingBlockStart, CSSPropertyId::PaddingInlineEnd, CSSPropertyId::PaddingBlockEnd, CSSPropertyId::PaddingInlineStart };
        return properties[static_cast<size_t>(MapSidePhysicalToLogical(writingMode, BoxSide::Bottom))];
      }
      case CSSPropertyId::PaddingLeft:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::PaddingBlockStart, CSSPropertyId::PaddingInlineEnd, CSSPropertyId::PaddingBlockEnd, CSSPropertyId::PaddingInlineStart };
        return properties[static_cast<size_t>(MapSidePhysicalToLogical(writingMode, BoxSide::Left))];
      }
      case CSSPropertyId::PaddingRight:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::PaddingBlockStart, CSSPropertyId::PaddingInlineEnd, CSSPropertyId::PaddingBlockEnd, CSSPropertyId::PaddingInlineStart };
        return properties[static_cast<size_t>(MapSidePhysicalToLogical(writingMode, BoxSide::Right))];
      }
      case CSSPropertyId::PaddingTop:
      {
        constexpr static CSSPropertyId properties[4] = { CSSPropertyId::PaddingBlockStart, CSSPropertyId::PaddingInlineEnd, CSSPropertyId::PaddingBlockEnd, CSSPropertyId::PaddingInlineStart };
        return properties[static_cast<size_t>(MapSidePhysicalToLogical(writingMode, BoxSide::Top))];
      }
      default:
      {
        return id;
      }
    }
  }

  bool CSSProperty::IsDescriptorOnly(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSProperty::AcceptsQuirkyColor(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSProperty::AcceptsQuirkyLength(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::FontSize:
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      case CSSPropertyId::PaddingBottom:
      case CSSPropertyId::PaddingLeft:
      case CSSPropertyId::PaddingRight:
      case CSSPropertyId::PaddingTop:
      case CSSPropertyId::Margin:
      case CSSPropertyId::Padding:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSProperty::AcceptsQuirkyAngle(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  bool operator==(const CSSPropertySettings &a, const CSSPropertySettings &b)
  {
    return a.CornerShapePropertyEnabled == b.CornerShapePropertyEnabled
      && a.DPropertyEnabled == b.DPropertyEnabled
      && a.FontVariantEmojiPropertyEnabled == b.FontVariantEmojiPropertyEnabled;
  }

  constexpr static Array<CSSValueId, 12uz> ValidKeywordsForWritingMode {
    CSSValueId::HorizontalTb,
    CSSValueId::VerticalLr,
    CSSValueId::VerticalRl,
    CSSValueId::SidewaysLr,
    CSSValueId::SidewaysRl,
    CSSValueId::LrTb,
    CSSValueId::RlTb,
    CSSValueId::TbRl,
    CSSValueId::Lr,
    CSSValueId::Rl,
    CSSValueId::Tb,
    CSSValueId::HorizontalBt,
  };

  constexpr static Array<CSSValueId, 2uz> ValidKeywordsForDirection {
    CSSValueId::Ltr,
    CSSValueId::Rtl,
  };

  constexpr static Array<CSSValueId, 35uz> ValidKeywordsForDisplay {
    CSSValueId::Inline,
    CSSValueId::Block,
    CSSValueId::Flow,
    CSSValueId::FlowRoot,
    CSSValueId::ListItem,
    CSSValueId::InlineBlock,
    CSSValueId::Table,
    CSSValueId::InlineTable,
    CSSValueId::TableRowGroup,
    CSSValueId::TableHeaderGroup,
    CSSValueId::TableFooterGroup,
    CSSValueId::TableRow,
    CSSValueId::TableColumnGroup,
    CSSValueId::TableColumn,
    CSSValueId::TableCell,
    CSSValueId::TableCaption,
    CSSValueId::Flex,
    CSSValueId::InlineFlex,
    CSSValueId::Grid,
    CSSValueId::InlineGrid,
    CSSValueId::GridLanes,
    CSSValueId::InlineGridLanes,
    CSSValueId::Ruby,
    CSSValueId::RubyTextContainer,
    CSSValueId::RubyBase,
    CSSValueId::RubyText,
    CSSValueId::RubyBaseContainer,
    CSSValueId::Contents,
    CSSValueId::None,
    CSSValueId::WebkitBox,
    CSSValueId::WebkitInlineBox,
    CSSValueId::WebkitFlex,
    CSSValueId::WebkitInlineFlex,
    CSSValueId::Compact,
    CSSValueId::RunIn,
  };

  constexpr static Array<CSSValueId, 14uz> ValidKeywordsForFontFamily {
    CSSValueId::Serif,
    CSSValueId::SansSerif,
    CSSValueId::Cursive,
    CSSValueId::Fantasy,
    CSSValueId::Monospace,
    CSSValueId::Math,
    CSSValueId::SystemUi,
    CSSValueId::Emoji,
    CSSValueId::Fangsong,
    CSSValueId::UiSerif,
    CSSValueId::UiSansSerif,
    CSSValueId::UiMonospace,
    CSSValueId::UiRounded,
    CSSValueId::WebkitBody,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForFontFeatureSettings {
    CSSValueId::Normal,
  };

  constexpr static Array<CSSValueId, 3uz> ValidKeywordsForFontKerning {
    CSSValueId::Auto,
    CSSValueId::Normal,
    CSSValueId::None,
  };

  constexpr static Array<CSSValueId, 13uz> ValidKeywordsForFontSize {
    CSSValueId::XSmall,
    CSSValueId::XxSmall,
    CSSValueId::Small,
    CSSValueId::Medium,
    CSSValueId::Large,
    CSSValueId::XLarge,
    CSSValueId::XxLarge,
    CSSValueId::XxxLarge,
    CSSValueId::Smaller,
    CSSValueId::Larger,
    CSSValueId::Math,
    CSSValueId::WebkitXxxLarge,
    CSSValueId::WebkitRubyText,
  };

  constexpr static Array<CSSValueId, 7uz> ValidKeywordsForFontSizeAdjust {
    CSSValueId::None,
    CSSValueId::ExHeight,
    CSSValueId::CapHeight,
    CSSValueId::ChWidth,
    CSSValueId::IcWidth,
    CSSValueId::IcHeight,
    CSSValueId::FromFont,
  };

  constexpr static Array<CSSValueId, 3uz> ValidKeywordsForFontStyle {
    CSSValueId::Normal,
    CSSValueId::Italic,
    CSSValueId::Oblique,
  };

  constexpr static Array<CSSValueId, 2uz> ValidKeywordsForFontSynthesisSmallCaps {
    CSSValueId::Auto,
    CSSValueId::None,
  };

  constexpr static Array<CSSValueId, 2uz> ValidKeywordsForFontSynthesisStyle {
    CSSValueId::Auto,
    CSSValueId::None,
  };

  constexpr static Array<CSSValueId, 2uz> ValidKeywordsForFontSynthesisWeight {
    CSSValueId::Auto,
    CSSValueId::None,
  };

  constexpr static Array<CSSValueId, 7uz> ValidKeywordsForFontVariantCaps {
    CSSValueId::Normal,
    CSSValueId::SmallCaps,
    CSSValueId::AllSmallCaps,
    CSSValueId::PetiteCaps,
    CSSValueId::AllPetiteCaps,
    CSSValueId::Unicase,
    CSSValueId::TitlingCaps,
  };

  constexpr static Array<CSSValueId, 10uz> ValidKeywordsForFontVariantEastAsian {
    CSSValueId::Normal,
    CSSValueId::Jis78,
    CSSValueId::Jis83,
    CSSValueId::Jis90,
    CSSValueId::Jis04,
    CSSValueId::Simplified,
    CSSValueId::Traditional,
    CSSValueId::FullWidth,
    CSSValueId::ProportionalWidth,
    CSSValueId::Ruby,
  };

  constexpr static Array<CSSValueId, 4uz> ValidKeywordsForFontVariantEmoji {
    CSSValueId::Normal,
    CSSValueId::Text,
    CSSValueId::Emoji,
    CSSValueId::Unicode,
  };

  constexpr static Array<CSSValueId, 10uz> ValidKeywordsForFontVariantLigatures {
    CSSValueId::Normal,
    CSSValueId::None,
    CSSValueId::CommonLigatures,
    CSSValueId::NoCommonLigatures,
    CSSValueId::DiscretionaryLigatures,
    CSSValueId::NoDiscretionaryLigatures,
    CSSValueId::HistoricalLigatures,
    CSSValueId::NoHistoricalLigatures,
    CSSValueId::Contextual,
    CSSValueId::NoContextual,
  };

  constexpr static Array<CSSValueId, 9uz> ValidKeywordsForFontVariantNumeric {
    CSSValueId::Normal,
    CSSValueId::LiningNums,
    CSSValueId::OldstyleNums,
    CSSValueId::ProportionalNums,
    CSSValueId::TabularNums,
    CSSValueId::DiagonalFractions,
    CSSValueId::StackedFractions,
    CSSValueId::Ordinal,
    CSSValueId::SlashedZero,
  };

  constexpr static Array<CSSValueId, 3uz> ValidKeywordsForFontVariantPosition {
    CSSValueId::Normal,
    CSSValueId::Sub,
    CSSValueId::Super,
  };

  constexpr static Array<CSSValueId, 4uz> ValidKeywordsForFontWeight {
    CSSValueId::Normal,
    CSSValueId::Bold,
    CSSValueId::Bolder,
    CSSValueId::Lighter,
  };

  constexpr static Array<CSSValueId, 9uz> ValidKeywordsForFontWidth {
    CSSValueId::Normal,
    CSSValueId::UltraCondensed,
    CSSValueId::ExtraCondensed,
    CSSValueId::Condensed,
    CSSValueId::SemiCondensed,
    CSSValueId::SemiExpanded,
    CSSValueId::Expanded,
    CSSValueId::ExtraExpanded,
    CSSValueId::UltraExpanded,
  };

  constexpr static Array<CSSValueId, 4uz> ValidKeywordsForWebkitFontSmoothing {
    CSSValueId::Auto,
    CSSValueId::None,
    CSSValueId::Antialiased,
    CSSValueId::SubpixelAntialiased,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForBackgroundImage {
    CSSValueId::None,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForD {
    CSSValueId::None,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForLineHeight {
    CSSValueId::Normal,
  };

  constexpr static Array<CSSValueId, 7uz> ValidKeywordsForMarginTrim {
    CSSValueId::None,
    CSSValueId::Block,
    CSSValueId::Inline,
    CSSValueId::BlockStart,
    CSSValueId::InlineStart,
    CSSValueId::BlockEnd,
    CSSValueId::InlineEnd,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForMarginBottom {
    CSSValueId::Auto,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForMarginLeft {
    CSSValueId::Auto,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForMarginRight {
    CSSValueId::Auto,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForMarginTop {
    CSSValueId::Auto,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForMarginBlockEnd {
    CSSValueId::Auto,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForMarginInlineEnd {
    CSSValueId::Auto,
  };

  constexpr static Array<CSSValueId, 1uz> ValidKeywordsForMarginInlineStart {
    CSSValueId::Auto,
  };

  Span<const CSSValueId> CSSProperty::ValidKeywordsForProperty(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::WritingMode:
      {
        return Span<const CSSValueId> { ValidKeywordsForWritingMode };
      }
      case CSSPropertyId::Direction:
      {
        return Span<const CSSValueId> { ValidKeywordsForDirection };
      }
      case CSSPropertyId::Display:
      {
        return Span<const CSSValueId> { ValidKeywordsForDisplay };
      }
      case CSSPropertyId::FontFamily:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontFamily };
      }
      case CSSPropertyId::FontFeatureSettings:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontFeatureSettings };
      }
      case CSSPropertyId::FontKerning:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontKerning };
      }
      case CSSPropertyId::FontSize:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontSize };
      }
      case CSSPropertyId::FontSizeAdjust:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontSizeAdjust };
      }
      case CSSPropertyId::FontStyle:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontStyle };
      }
      case CSSPropertyId::FontSynthesisSmallCaps:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontSynthesisSmallCaps };
      }
      case CSSPropertyId::FontSynthesisStyle:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontSynthesisStyle };
      }
      case CSSPropertyId::FontSynthesisWeight:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontSynthesisWeight };
      }
      case CSSPropertyId::FontVariantCaps:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontVariantCaps };
      }
      case CSSPropertyId::FontVariantEastAsian:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontVariantEastAsian };
      }
      case CSSPropertyId::FontVariantEmoji:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontVariantEmoji };
      }
      case CSSPropertyId::FontVariantLigatures:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontVariantLigatures };
      }
      case CSSPropertyId::FontVariantNumeric:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontVariantNumeric };
      }
      case CSSPropertyId::FontVariantPosition:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontVariantPosition };
      }
      case CSSPropertyId::FontWeight:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontWeight };
      }
      case CSSPropertyId::FontWidth:
      {
        return Span<const CSSValueId> { ValidKeywordsForFontWidth };
      }
      case CSSPropertyId::WebkitFontSmoothing:
      {
        return Span<const CSSValueId> { ValidKeywordsForWebkitFontSmoothing };
      }
      case CSSPropertyId::BackgroundImage:
      {
        return Span<const CSSValueId> { ValidKeywordsForBackgroundImage };
      }
      case CSSPropertyId::D:
      {
        return Span<const CSSValueId> { ValidKeywordsForD };
      }
      case CSSPropertyId::LineHeight:
      {
        return Span<const CSSValueId> { ValidKeywordsForLineHeight };
      }
      case CSSPropertyId::MarginTrim:
      {
        return Span<const CSSValueId> { ValidKeywordsForMarginTrim };
      }
      case CSSPropertyId::MarginBottom:
      {
        return Span<const CSSValueId> { ValidKeywordsForMarginBottom };
      }
      case CSSPropertyId::MarginLeft:
      {
        return Span<const CSSValueId> { ValidKeywordsForMarginLeft };
      }
      case CSSPropertyId::MarginRight:
      {
        return Span<const CSSValueId> { ValidKeywordsForMarginRight };
      }
      case CSSPropertyId::MarginTop:
      {
        return Span<const CSSValueId> { ValidKeywordsForMarginTop };
      }
      case CSSPropertyId::MarginBlockEnd:
      {
        return Span<const CSSValueId> { ValidKeywordsForMarginBlockEnd };
      }
      case CSSPropertyId::MarginInlineEnd:
      {
        return Span<const CSSValueId> { ValidKeywordsForMarginInlineEnd };
      }
      case CSSPropertyId::MarginInlineStart:
      {
        return Span<const CSSValueId> { ValidKeywordsForMarginInlineStart };
      }
      default:
      {
        return {};
      }
    }
  }

  namespace
  {
    KRYS_NODISCARD bool IsKeywordValidForWritingModeValues(CSSValueId keyword, const CSSParserContext &context) noexcept
    {
      switch (keyword)
      {
        case CSSValueId::HorizontalTb:
        case CSSValueId::VerticalLr:
        case CSSValueId::VerticalRl:
        case CSSValueId::LrTb:
        case CSSValueId::RlTb:
        case CSSValueId::TbRl:
        case CSSValueId::Lr:
        case CSSValueId::Rl:
        case CSSValueId::Tb:
        case CSSValueId::HorizontalBt:
        {
          return true;
        }
        case CSSValueId::SidewaysLr:
        case CSSValueId::SidewaysRl:
        {
          return context.SidewaysWritingModesEnabled;
        }
        default:
        {
          return false;
        }
      }
    }

    KRYS_NODISCARD bool IsKeywordValidForDisplayValues(CSSValueId keyword, const CSSParserContext &context) noexcept
    {
      switch (keyword)
      {
        case CSSValueId::Inline:
        case CSSValueId::Block:
        case CSSValueId::Flow:
        case CSSValueId::FlowRoot:
        case CSSValueId::ListItem:
        case CSSValueId::InlineBlock:
        case CSSValueId::Table:
        case CSSValueId::InlineTable:
        case CSSValueId::TableRowGroup:
        case CSSValueId::TableHeaderGroup:
        case CSSValueId::TableFooterGroup:
        case CSSValueId::TableRow:
        case CSSValueId::TableColumnGroup:
        case CSSValueId::TableColumn:
        case CSSValueId::TableCell:
        case CSSValueId::TableCaption:
        case CSSValueId::Flex:
        case CSSValueId::InlineFlex:
        case CSSValueId::Grid:
        case CSSValueId::InlineGrid:
        case CSSValueId::Ruby:
        case CSSValueId::RubyTextContainer:
        case CSSValueId::RubyBase:
        case CSSValueId::RubyText:
        case CSSValueId::RubyBaseContainer:
        case CSSValueId::Contents:
        case CSSValueId::None:
        case CSSValueId::WebkitBox:
        case CSSValueId::WebkitInlineBox:
        case CSSValueId::WebkitFlex:
        case CSSValueId::WebkitInlineFlex:
        case CSSValueId::Compact:
        case CSSValueId::RunIn:
        {
          return true;
        }
        case CSSValueId::GridLanes:
        case CSSValueId::InlineGridLanes:
        {
          return context.GridLanesEnabled;
        }
        default:
        {
          return false;
        }
      }
    }

    KRYS_NODISCARD bool IsKeywordValidForFontSizeValues(CSSValueId keyword, const CSSParserContext &context) noexcept
    {
      switch (keyword)
      {
        case CSSValueId::XSmall:
        case CSSValueId::XxSmall:
        case CSSValueId::Small:
        case CSSValueId::Medium:
        case CSSValueId::Large:
        case CSSValueId::XLarge:
        case CSSValueId::XxLarge:
        case CSSValueId::XxxLarge:
        case CSSValueId::Smaller:
        case CSSValueId::Larger:
        case CSSValueId::WebkitXxxLarge:
        case CSSValueId::WebkitRubyText:
        {
          return true;
        }
        case CSSValueId::Math:
        {
          return context.MathDepthEnabled;
        }
        default:
        {
          return false;
        }
      }
    }

  }

  bool CSSProperty::IsKeywordValidForPropertyValues(CSSPropertyId id, CSSValueId keyword, const CSSParserContext &context) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::WritingMode:
      {
        return IsKeywordValidForWritingModeValues(keyword, context);
      }
      case CSSPropertyId::Direction:
      {
        return std::ranges::find(ValidKeywordsForDirection, keyword) != ValidKeywordsForDirection.end();
      }
      case CSSPropertyId::Display:
      {
        return IsKeywordValidForDisplayValues(keyword, context);
      }
      case CSSPropertyId::FontFamily:
      {
        return std::ranges::find(ValidKeywordsForFontFamily, keyword) != ValidKeywordsForFontFamily.end();
      }
      case CSSPropertyId::FontFeatureSettings:
      {
        return std::ranges::find(ValidKeywordsForFontFeatureSettings, keyword) != ValidKeywordsForFontFeatureSettings.end();
      }
      case CSSPropertyId::FontKerning:
      {
        return std::ranges::find(ValidKeywordsForFontKerning, keyword) != ValidKeywordsForFontKerning.end();
      }
      case CSSPropertyId::FontSize:
      {
        return IsKeywordValidForFontSizeValues(keyword, context);
      }
      case CSSPropertyId::FontSizeAdjust:
      {
        return std::ranges::find(ValidKeywordsForFontSizeAdjust, keyword) != ValidKeywordsForFontSizeAdjust.end();
      }
      case CSSPropertyId::FontStyle:
      {
        return std::ranges::find(ValidKeywordsForFontStyle, keyword) != ValidKeywordsForFontStyle.end();
      }
      case CSSPropertyId::FontSynthesisSmallCaps:
      {
        return std::ranges::find(ValidKeywordsForFontSynthesisSmallCaps, keyword) != ValidKeywordsForFontSynthesisSmallCaps.end();
      }
      case CSSPropertyId::FontSynthesisStyle:
      {
        return std::ranges::find(ValidKeywordsForFontSynthesisStyle, keyword) != ValidKeywordsForFontSynthesisStyle.end();
      }
      case CSSPropertyId::FontSynthesisWeight:
      {
        return std::ranges::find(ValidKeywordsForFontSynthesisWeight, keyword) != ValidKeywordsForFontSynthesisWeight.end();
      }
      case CSSPropertyId::FontVariantCaps:
      {
        return std::ranges::find(ValidKeywordsForFontVariantCaps, keyword) != ValidKeywordsForFontVariantCaps.end();
      }
      case CSSPropertyId::FontVariantEastAsian:
      {
        return std::ranges::find(ValidKeywordsForFontVariantEastAsian, keyword) != ValidKeywordsForFontVariantEastAsian.end();
      }
      case CSSPropertyId::FontVariantEmoji:
      {
        return std::ranges::find(ValidKeywordsForFontVariantEmoji, keyword) != ValidKeywordsForFontVariantEmoji.end();
      }
      case CSSPropertyId::FontVariantLigatures:
      {
        return std::ranges::find(ValidKeywordsForFontVariantLigatures, keyword) != ValidKeywordsForFontVariantLigatures.end();
      }
      case CSSPropertyId::FontVariantNumeric:
      {
        return std::ranges::find(ValidKeywordsForFontVariantNumeric, keyword) != ValidKeywordsForFontVariantNumeric.end();
      }
      case CSSPropertyId::FontVariantPosition:
      {
        return std::ranges::find(ValidKeywordsForFontVariantPosition, keyword) != ValidKeywordsForFontVariantPosition.end();
      }
      case CSSPropertyId::FontWeight:
      {
        return std::ranges::find(ValidKeywordsForFontWeight, keyword) != ValidKeywordsForFontWeight.end();
      }
      case CSSPropertyId::FontWidth:
      {
        return std::ranges::find(ValidKeywordsForFontWidth, keyword) != ValidKeywordsForFontWidth.end();
      }
      case CSSPropertyId::WebkitFontSmoothing:
      {
        return std::ranges::find(ValidKeywordsForWebkitFontSmoothing, keyword) != ValidKeywordsForWebkitFontSmoothing.end();
      }
      case CSSPropertyId::BackgroundImage:
      {
        return std::ranges::find(ValidKeywordsForBackgroundImage, keyword) != ValidKeywordsForBackgroundImage.end();
      }
      case CSSPropertyId::D:
      {
        return std::ranges::find(ValidKeywordsForD, keyword) != ValidKeywordsForD.end();
      }
      case CSSPropertyId::LineHeight:
      {
        return std::ranges::find(ValidKeywordsForLineHeight, keyword) != ValidKeywordsForLineHeight.end();
      }
      case CSSPropertyId::MarginTrim:
      {
        return std::ranges::find(ValidKeywordsForMarginTrim, keyword) != ValidKeywordsForMarginTrim.end();
      }
      case CSSPropertyId::MarginBottom:
      {
        return std::ranges::find(ValidKeywordsForMarginBottom, keyword) != ValidKeywordsForMarginBottom.end();
      }
      case CSSPropertyId::MarginLeft:
      {
        return std::ranges::find(ValidKeywordsForMarginLeft, keyword) != ValidKeywordsForMarginLeft.end();
      }
      case CSSPropertyId::MarginRight:
      {
        return std::ranges::find(ValidKeywordsForMarginRight, keyword) != ValidKeywordsForMarginRight.end();
      }
      case CSSPropertyId::MarginTop:
      {
        return std::ranges::find(ValidKeywordsForMarginTop, keyword) != ValidKeywordsForMarginTop.end();
      }
      case CSSPropertyId::MarginBlockEnd:
      {
        return std::ranges::find(ValidKeywordsForMarginBlockEnd, keyword) != ValidKeywordsForMarginBlockEnd.end();
      }
      case CSSPropertyId::MarginInlineEnd:
      {
        return std::ranges::find(ValidKeywordsForMarginInlineEnd, keyword) != ValidKeywordsForMarginInlineEnd.end();
      }
      case CSSPropertyId::MarginInlineStart:
      {
        return std::ranges::find(ValidKeywordsForMarginInlineStart, keyword) != ValidKeywordsForMarginInlineStart.end();
      }
      default:
      {
        return false;
      }
    }
  }
  }
