// <auto-generated>
//   Generated at 2026-08-23 11:23:38 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.HTML/CSS/Properties/Enums/CSSPropertyId.hpp"
#include "Krystal.Lib/Core/Attributes.hpp"

namespace Krys::HTML
{
  class CSSPropertyShorthand;

  KRYS_NODISCARD CSSPropertyShorthand AllShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand AnimationShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand AnimationRangeShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockColorShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockEndShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockStartShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockStyleShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockWidthShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBottomShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderColorShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderImageShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineColorShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineEndShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineStartShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineStyleShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineWidthShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderLeftShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderRadiusShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderRightShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderStyleShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderTopShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderWidthShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand CornerShapeShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FontShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FontSynthesisShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FontVariantShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarginShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarginBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarginInlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PaddingShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PaddingBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PaddingInlineShorthand() noexcept;
}
