// <auto-generated>
//   Generated at 2026-08-21 17:42:47 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.HTML/CSS/Properties/Enums/CSSPropertyId.hpp"
#include "Krystal.Lib/Core/Attributes.hpp"

namespace Krys::HTML
{
  struct CSSPropertyShorthand;

  KRYS_NODISCARD CSSPropertyShorthand AllShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand CornerShapeShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FontShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FontSynthesisShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FontVariantShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarginShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarginBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarginInlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PaddingShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PaddingBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PaddingInlineShorthand() noexcept;
}
