#pragma once

#include "Krystal.HTML/CSS/Parser/CSSTokenRange.hpp"
#include "Krystal.HTML/CSS/Parser/Types/ParsedCSSPropertyList.hpp"
#include "Krystal.HTML/CSS/Properties/CSSPropertyParserState.hpp"

namespace Krys::HTML
{
  class CSSPropertyConsumer
  {
  public:
    /// @brief Parses a shorthand style property from the given tokens and adds the resulting longhand
    /// properties to the given properties list. Returns true if the property was successfully parsed and
    /// added to the list.
    /// @note Implementation is generated by css-properties.generator.py.
    KRYS_NODISCARD static bool ParseShorthandStyleProperty(CSSTokenRange tokens,
                                                           CSSPropertyParserState &state,
                                                           ParsedCSSPropertyList &properties) noexcept;

    /// @brief Parses a longhand style property from the given tokens and adds it to the given properties
    /// list. Returns true if the property was successfully parsed and added to the list.
    /// @note Implementation is generated by css-properties.generator.py.
    KRYS_NODISCARD static bool ParseLonghandStyleProperty(CSSTokenRange tokens, CSSPropertyParserState &state,
                                                          ParsedCSSPropertyList &properties) noexcept;
  };
}