// <auto-generated>
//   Generated at 2026-08-21 18:22:47 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.HTML/CSS/Properties/Enums/CSSPropertyId.hpp"
#include "Krystal.HTML/CSS/Values/Enums/CSSValueId.hpp"
#include "Krystal.Lib/Pointers/RefPtr.hpp"

namespace Krys::HTML
{
  struct CSSPropertyParserResult;
  struct CSSPropertyParserState;

  class CSSTokenRange;
  class CSSValue;

  struct CSSPropertyParsing
  {
    /// @brief Parse and return a single longhand style property.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseStylePropertyLonghand(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state) noexcept;

    /// @brief Parse a shorthand style property, adding longhands to the provided result collection.
    /// @returns true on success, false on failure.
    KRYS_NODISCARD static bool ParseStylePropertyShorthand(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state, CSSPropertyParserResult &result) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForStyleProperty(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleStyleProperty(CSSPropertyId id) noexcept;

    // Direct consumers.

    // Exported style property consumers.
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFeatureSettings(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontSize(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantAlternates(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantCaps(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantEastAsian(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantEmoji(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantPosition(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontWeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeLineHeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeCornerStartEndShape(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
  };
}
