// <auto-generated>
//   Generated at 2026-08-29 16:34:38 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.HTML/CSS/Properties/Enums/CSSPropertyId.hpp"
#include "Krystal.HTML/CSS/Values/Enums/CSSValueId.hpp"
#include "Krystal.Lib/Pointers/RefPtr.hpp"

namespace Krys::HTML
{
  struct CSSPropertyParserResult;
  struct CSSPropertyParserState;

  class CSSTokenRange;
  class CSSValue;

  struct CSSPropertyParsing
  {
    /// @brief Parse and return a single longhand style property.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseStylePropertyLonghand(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state) noexcept;

    /// @brief Parse a shorthand style property, adding longhands to the provided result collection.
    /// @returns true on success, false on failure.
    KRYS_NODISCARD static bool ParseStylePropertyShorthand(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state, CSSPropertyParserResult &result) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForStyleProperty(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleStyleProperty(CSSPropertyId id) noexcept;

    /// @brief Parse and return a single @counter-style descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseCounterStyleDescriptor(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForCounterStyleDescriptor(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleCounterStyleDescriptor(CSSPropertyId id) noexcept;

    /// @brief Parse and return a single @font-face descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseFontFaceDescriptor(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForFontFaceDescriptor(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleFontFaceDescriptor(CSSPropertyId id) noexcept;

    /// @brief Parse and return a single @font-palette-values descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseFontPaletteValuesDescriptor(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForFontPaletteValuesDescriptor(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleFontPaletteValuesDescriptor(CSSPropertyId id) noexcept;

    /// @brief Parse and return a single @page descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParsePageDescriptor(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForPageDescriptor(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligiblePageDescriptor(CSSPropertyId id) noexcept;

    /// @brief Parse and return a single @property descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParsePropertyDescriptor(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForPropertyDescriptor(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligiblePropertyDescriptor(CSSPropertyId id) noexcept;

    /// @brief Parse and return a single @function descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseFunctionDescriptor(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForFunctionDescriptor(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleFunctionDescriptor(CSSPropertyId id) noexcept;

    /// @brief Parse and return a single @view-transition descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseViewTransitionDescriptor(CSSTokenRange &tokens, CSSPropertyId id, CSSPropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForViewTransitionDescriptor(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleViewTransitionDescriptor(CSSPropertyId id) noexcept;

    // Direct consumers.

    // Exported style property consumers.
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFeatureSettings(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontSize(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantAlternates(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantCaps(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantEastAsian(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantEmoji(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantPosition(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontWeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockEllipsis(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockStepAlign(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockStepInsert(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockStepRound(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockStepSize(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderImageOutset(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderImageRepeat(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeColumnCount(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeColumnGap(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeColumnWidth(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeContinue(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeLineHeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeListStyleType(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMaxLines(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumePerspective(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeRowGap(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeScrollTimelineAxis(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeScrollTimelineName(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTextBoxTrim(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTextDecorationLine(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTextWrapMode(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTextWrapStyle(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTransform(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeViewTimelineAxis(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeViewTimelineName(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeWhiteSpaceCollapse(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeContainIntrinsicHeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeContainIntrinsicWidth(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeOverscrollBehaviorX(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeOverscrollBehaviorY(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeCornerStartEndShape(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;

    // Exported @font-face descriptor consumers.
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontDisplay(CSSTokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontFamily(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontFeatureSettings(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontWeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontWidth(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceSizeAdjust(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceUnicodeRange(CSSTokenRange &range) noexcept;

    // Exported @view-transition descriptor consumers.
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeViewTransitionNavigation(CSSTokenRange &range) noexcept;

    // Exported shared consumers.
    static RefPtr<CSSValue> ConsumeAxis(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeBlendMode(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeFontWidthAbsolute(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeGeometryBox(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeLineWidth(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeScroller(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeShapeBox(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationComposition(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationDirection(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationDuration(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationFillMode(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationIterationCount(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationName(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationPlayState(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundAttachment(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundBlendMode(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundClip(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundImage(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundOrigin(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundPositionX(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundPositionY(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundRepeat(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleContainerName(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskClip(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskComposite(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskImage(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskMode(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskOrigin(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskRepeat(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleScrollTimelineName(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleViewTimelineInset(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitBackgroundClip(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitBackgroundOrigin(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskClip(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskComposite(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskPositionX(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskPositionY(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskSourceType(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSymbol(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeTimelineRangeName(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeTransformFunction(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeTransformList(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeTransitionBehaviorValue(CSSTokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeWidthOrHeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept;
  };
}
