// <auto-generated>
//   Generated at 2026-09-04 15:13:02 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.HTML/CSS/Properties/Enums/CSSPropertyId.hpp"
#include "Krystal.Lib/Core/Attributes.hpp"

namespace Krys::HTML
{
  class CSSPropertyShorthand;

  KRYS_NODISCARD CSSPropertyShorthand AllShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand AnimationShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand AnimationRangeShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BackgroundShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BackgroundPositionShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BlockStepShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockColorShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockEndShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockStartShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockStyleShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBlockWidthShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderBottomShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderColorShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderImageShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineColorShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineEndShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineStartShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineStyleShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderInlineWidthShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderLeftShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderRadiusShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderRightShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderSpacingShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderStyleShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderTopShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand BorderWidthShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ColumnRuleShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ColumnsShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ContainIntrinsicSizeShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ContainerShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand CornerShapeShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FlexShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FlexFlowShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FontShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FontSynthesisShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand FontVariantShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand GapShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand GridShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand GridAreaShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand GridColumnShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand GridRowShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand GridTemplateShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand InsetShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand InsetBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand InsetInlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand LineClampShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ListStyleShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarginShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarginBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarginInlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MarkerShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MaskShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MaskBorderShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand MaskPositionShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand OffsetShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand OutlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand OverflowShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand OverscrollBehaviorShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PaddingShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PaddingBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PaddingInlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PageBreakAfterShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PageBreakBeforeShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PageBreakInsideShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PerspectiveOriginShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PlaceContentShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PlaceItemsShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PlaceSelfShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand PositionTryShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ScrollMarginShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ScrollMarginBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ScrollMarginInlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ScrollPaddingShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ScrollPaddingBlockShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ScrollPaddingInlineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ScrollTimelineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand TextBoxShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand TextDecorationShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand TextDecorationSkipShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand TextEmphasisShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand TextWrapShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand TransformOriginShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand TransitionShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand ViewTimelineShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand WhiteSpaceShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand WebkitBackgroundSizeShorthand() noexcept;
  KRYS_NODISCARD CSSPropertyShorthand WebkitMaskPositionShorthand() noexcept;
}
