// <auto-generated>
//   Generated at 2026-08-23 11:23:38 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.HTML/CSS/Properties/Enums/CSSPropertyId.hpp"
#include "Krystal.HTML/CSS/Values/CSSUnits.hpp"
#include "Krystal.HTML/CSS/Values/Enums/CSSValueId.hpp"
#include "Krystal.Lib/Types/Variant.hpp"
#include <cassert>

namespace Krys::HTML
{
  struct InitialNumericValue
  {
    double Number;
    CSSUnitType Type { CSSUnitType::Number };
  };

  using InitialValue = Variant<CSSValueId, InitialNumericValue>;

  // Skipping CSSPropertyId::FontFamily, initial is a special value [SpecialLiteral @initial-font-family]
  KRYS_NODISCARD constexpr static InitialValue InitialValueForLonghand(CSSPropertyId longhand) noexcept
  {
    switch (longhand)
    {
      case CSSPropertyId::WritingMode:
      {
        return CSSValueId::HorizontalTb;
      }
      case CSSPropertyId::Direction:
      {
        return CSSValueId::Ltr;
      }
      case CSSPropertyId::Display:
      {
        return CSSValueId::Inline;
      }
      case CSSPropertyId::AnimationDirection:
      case CSSPropertyId::AnimationRangeEnd:
      case CSSPropertyId::AnimationRangeStart:
      case CSSPropertyId::FontFeatureSettings:
      case CSSPropertyId::FontPalette:
      case CSSPropertyId::FontStyle:
      case CSSPropertyId::FontVariantAlternates:
      case CSSPropertyId::FontVariantCaps:
      case CSSPropertyId::FontVariantEastAsian:
      case CSSPropertyId::FontVariantEmoji:
      case CSSPropertyId::FontVariantLigatures:
      case CSSPropertyId::FontVariantNumeric:
      case CSSPropertyId::FontVariantPosition:
      case CSSPropertyId::FontWeight:
      case CSSPropertyId::FontWidth:
      case CSSPropertyId::LineHeight:
      {
        return CSSValueId::Normal;
      }
      case CSSPropertyId::AnimationDuration:
      case CSSPropertyId::AnimationTimeline:
      case CSSPropertyId::FontKerning:
      case CSSPropertyId::FontSynthesisSmallCaps:
      case CSSPropertyId::FontSynthesisStyle:
      case CSSPropertyId::FontSynthesisWeight:
      {
        return CSSValueId::Auto;
      }
      case CSSPropertyId::BorderBlockEndWidth:
      case CSSPropertyId::BorderBlockStartWidth:
      case CSSPropertyId::BorderBottomWidth:
      case CSSPropertyId::BorderInlineEndWidth:
      case CSSPropertyId::BorderInlineStartWidth:
      case CSSPropertyId::BorderLeftWidth:
      case CSSPropertyId::BorderRightWidth:
      case CSSPropertyId::BorderTopWidth:
      case CSSPropertyId::FontSize:
      {
        return CSSValueId::Medium;
      }
      case CSSPropertyId::AnimationFillMode:
      case CSSPropertyId::AnimationName:
      case CSSPropertyId::BackgroundImage:
      case CSSPropertyId::BorderBlockEndStyle:
      case CSSPropertyId::BorderBlockStartStyle:
      case CSSPropertyId::BorderBottomStyle:
      case CSSPropertyId::BorderImageSource:
      case CSSPropertyId::BorderInlineEndStyle:
      case CSSPropertyId::BorderInlineStartStyle:
      case CSSPropertyId::BorderLeftStyle:
      case CSSPropertyId::BorderRightStyle:
      case CSSPropertyId::BorderTopStyle:
      case CSSPropertyId::D:
      case CSSPropertyId::FontSizeAdjust:
      case CSSPropertyId::MarginTrim:
      {
        return CSSValueId::None;
      }
      case CSSPropertyId::AnimationComposition:
      {
        return CSSValueId::Replace;
      }
      case CSSPropertyId::AnimationDelay:
      {
        return InitialNumericValue { 0, CSSUnitType::s };
      }
      case CSSPropertyId::AnimationIterationCount:
      case CSSPropertyId::BorderImageWidth:
      {
        return InitialNumericValue { 1, CSSUnitType::Number };
      }
      case CSSPropertyId::AnimationPlayState:
      {
        return CSSValueId::Running;
      }
      case CSSPropertyId::AnimationTimingFunction:
      {
        return CSSValueId::Ease;
      }
      case CSSPropertyId::BorderCollapse:
      {
        return CSSValueId::Separate;
      }
      case CSSPropertyId::BorderImageOutset:
      {
        return InitialNumericValue { 0, CSSUnitType::Number };
      }
      case CSSPropertyId::BorderImageRepeat:
      {
        return CSSValueId::Stretch;
      }
      case CSSPropertyId::BorderImageSlice:
      {
        return InitialNumericValue { 100, CSSUnitType::Percentage };
      }
      case CSSPropertyId::Color:
      {
        return CSSValueId::Canvastext;
      }
      case CSSPropertyId::BorderBlockEndColor:
      case CSSPropertyId::BorderBlockStartColor:
      case CSSPropertyId::BorderBottomColor:
      case CSSPropertyId::BorderInlineEndColor:
      case CSSPropertyId::BorderInlineStartColor:
      case CSSPropertyId::BorderLeftColor:
      case CSSPropertyId::BorderRightColor:
      case CSSPropertyId::BorderTopColor:
      {
        return CSSValueId::Currentcolor;
      }
      case CSSPropertyId::BorderBottomLeftRadius:
      case CSSPropertyId::BorderBottomRightRadius:
      case CSSPropertyId::BorderEndEndRadius:
      case CSSPropertyId::BorderEndStartRadius:
      case CSSPropertyId::BorderStartEndRadius:
      case CSSPropertyId::BorderStartStartRadius:
      case CSSPropertyId::BorderTopLeftRadius:
      case CSSPropertyId::BorderTopRightRadius:
      case CSSPropertyId::MarginBlockEnd:
      case CSSPropertyId::MarginBlockStart:
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginInlineEnd:
      case CSSPropertyId::MarginInlineStart:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      case CSSPropertyId::PaddingBlockEnd:
      case CSSPropertyId::PaddingBlockStart:
      case CSSPropertyId::PaddingBottom:
      case CSSPropertyId::PaddingInlineEnd:
      case CSSPropertyId::PaddingInlineStart:
      case CSSPropertyId::PaddingLeft:
      case CSSPropertyId::PaddingRight:
      case CSSPropertyId::PaddingTop:
      {
        return InitialNumericValue { 0, CSSUnitType::px };
      }
      case CSSPropertyId::CornerBottomLeftShape:
      case CSSPropertyId::CornerBottomRightShape:
      case CSSPropertyId::CornerEndEndShape:
      case CSSPropertyId::CornerEndStartShape:
      case CSSPropertyId::CornerStartEndShape:
      case CSSPropertyId::CornerStartStartShape:
      case CSSPropertyId::CornerTopLeftShape:
      case CSSPropertyId::CornerTopRightShape:
      {
        return CSSValueId::Round;
      }
      default:
      {
        assert(false);
      }
    }
  }
}
