// <auto-generated>
//   Generated at 2026-09-04 15:13:02 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.HTML/CSS/Properties/Enums/CSSPropertyId.hpp"
#include "Krystal.HTML/CSS/Values/CSSUnits.hpp"
#include "Krystal.HTML/CSS/Values/Enums/CSSValueId.hpp"
#include "Krystal.Lib/Types/Variant.hpp"
#include <cassert>

namespace Krys::HTML
{
  struct InitialNumericValue
  {
    double Number;
    CSSUnitType Type { CSSUnitType::Number };
  };

  using InitialValue = Variant<CSSValueId, InitialNumericValue>;

  KRYS_NODISCARD constexpr static InitialValue InitialValueForLonghand(CSSPropertyId longhand) noexcept
  {
    switch (longhand)
    {
      case CSSPropertyId::BorderImageOutset:
      case CSSPropertyId::FlexGrow:
      case CSSPropertyId::MaskBorderOutset:
      case CSSPropertyId::MaskBorderSlice:
      case CSSPropertyId::MathDepth:
      case CSSPropertyId::Order:
      case CSSPropertyId::Page:
      case CSSPropertyId::ShapeImageThreshold:
      case CSSPropertyId::StrokeDashoffset:
      {
        return InitialNumericValue {0, CSSUnitType::Number};
      }
      case CSSPropertyId::RubyPosition:
      {
        return CSSValueId::Over;
      }
      case CSSPropertyId::WritingMode:
      {
        return CSSValueId::HorizontalTb;
      }
      case CSSPropertyId::Direction:
      {
        return CSSValueId::Ltr;
      }
      case CSSPropertyId::Display:
      {
        return CSSValueId::Inline;
      }
      case CSSPropertyId::AlignContent:
      case CSSPropertyId::AlignItems:
      case CSSPropertyId::AnimationDirection:
      case CSSPropertyId::AnimationRangeEnd:
      case CSSPropertyId::AnimationRangeStart:
      case CSSPropertyId::BackgroundBlendMode:
      case CSSPropertyId::ColumnGap:
      case CSSPropertyId::ContainerType:
      case CSSPropertyId::Content:
      case CSSPropertyId::FontFeatureSettings:
      case CSSPropertyId::FontPalette:
      case CSSPropertyId::FontStyle:
      case CSSPropertyId::FontVariantAlternates:
      case CSSPropertyId::FontVariantCaps:
      case CSSPropertyId::FontVariantEastAsian:
      case CSSPropertyId::FontVariantEmoji:
      case CSSPropertyId::FontVariantLigatures:
      case CSSPropertyId::FontVariantNumeric:
      case CSSPropertyId::FontVariantPosition:
      case CSSPropertyId::FontWeight:
      case CSSPropertyId::FontWidth:
      case CSSPropertyId::GridAutoFlow:
      case CSSPropertyId::ItemTolerance:
      case CSSPropertyId::JustifyContent:
      case CSSPropertyId::LetterSpacing:
      case CSSPropertyId::LineHeight:
      case CSSPropertyId::MathShift:
      case CSSPropertyId::MathStyle:
      case CSSPropertyId::MixBlendMode:
      case CSSPropertyId::OffsetPosition:
      case CSSPropertyId::OverflowWrap:
      case CSSPropertyId::PaintOrder:
      case CSSPropertyId::PositionTryOrder:
      case CSSPropertyId::RowGap:
      case CSSPropertyId::ScrollSnapStop:
      case CSSPropertyId::SpeakAs:
      case CSSPropertyId::TransitionBehavior:
      case CSSPropertyId::UnicodeBidi:
      case CSSPropertyId::WebkitColumnProgression:
      case CSSPropertyId::WebkitInitialLetter:
      case CSSPropertyId::WordBreak:
      case CSSPropertyId::WordSpacing:
      {
        return CSSValueId::Normal;
      }
      case CSSPropertyId::AccentColor:
      case CSSPropertyId::AlignSelf:
      case CSSPropertyId::AnimationDuration:
      case CSSPropertyId::AnimationTimeline:
      case CSSPropertyId::AspectRatio:
      case CSSPropertyId::BackgroundSize:
      case CSSPropertyId::BlockSize:
      case CSSPropertyId::BlockStepAlign:
      case CSSPropertyId::Bottom:
      case CSSPropertyId::BreakAfter:
      case CSSPropertyId::BreakBefore:
      case CSSPropertyId::BreakInside:
      case CSSPropertyId::BufferedRendering:
      case CSSPropertyId::CaretColor:
      case CSSPropertyId::Clip:
      case CSSPropertyId::ColumnCount:
      case CSSPropertyId::ColumnWidth:
      case CSSPropertyId::Continue:
      case CSSPropertyId::Cursor:
      case CSSPropertyId::DominantBaseline:
      case CSSPropertyId::FlexBasis:
      case CSSPropertyId::FontKerning:
      case CSSPropertyId::FontSynthesisSmallCaps:
      case CSSPropertyId::FontSynthesisStyle:
      case CSSPropertyId::FontSynthesisWeight:
      case CSSPropertyId::GlyphOrientationVertical:
      case CSSPropertyId::GridAutoColumns:
      case CSSPropertyId::GridAutoRows:
      case CSSPropertyId::GridColumnEnd:
      case CSSPropertyId::GridColumnStart:
      case CSSPropertyId::GridRowEnd:
      case CSSPropertyId::GridRowStart:
      case CSSPropertyId::Height:
      case CSSPropertyId::HyphenateCharacter:
      case CSSPropertyId::ImageRendering:
      case CSSPropertyId::InlineSize:
      case CSSPropertyId::InputSecurity:
      case CSSPropertyId::InsetBlockEnd:
      case CSSPropertyId::InsetBlockStart:
      case CSSPropertyId::InsetInlineEnd:
      case CSSPropertyId::InsetInlineStart:
      case CSSPropertyId::Isolation:
      case CSSPropertyId::JustifySelf:
      case CSSPropertyId::Left:
      case CSSPropertyId::LineBreak:
      case CSSPropertyId::MaskBorderWidth:
      case CSSPropertyId::MaskSize:
      case CSSPropertyId::MinHeight:
      case CSSPropertyId::MinWidth:
      case CSSPropertyId::OffsetAnchor:
      case CSSPropertyId::OffsetRotate:
      case CSSPropertyId::Orphans:
      case CSSPropertyId::OverflowAnchor:
      case CSSPropertyId::OverscrollBehaviorBlock:
      case CSSPropertyId::OverscrollBehaviorInline:
      case CSSPropertyId::OverscrollBehaviorX:
      case CSSPropertyId::OverscrollBehaviorY:
      case CSSPropertyId::PointerEvents:
      case CSSPropertyId::PositionAnchor:
      case CSSPropertyId::Quotes:
      case CSSPropertyId::Right:
      case CSSPropertyId::RubyOverhang:
      case CSSPropertyId::Rx:
      case CSSPropertyId::Ry:
      case CSSPropertyId::ScrollBehavior:
      case CSSPropertyId::ScrollPaddingBlockEnd:
      case CSSPropertyId::ScrollPaddingBlockStart:
      case CSSPropertyId::ScrollPaddingBottom:
      case CSSPropertyId::ScrollPaddingInlineEnd:
      case CSSPropertyId::ScrollPaddingInlineStart:
      case CSSPropertyId::ScrollPaddingLeft:
      case CSSPropertyId::ScrollPaddingRight:
      case CSSPropertyId::ScrollPaddingTop:
      case CSSPropertyId::ScrollbarColor:
      case CSSPropertyId::ScrollbarGutter:
      case CSSPropertyId::ScrollbarWidth:
      case CSSPropertyId::ShapeRendering:
      case CSSPropertyId::TableLayout:
      case CSSPropertyId::TextAlignLast:
      case CSSPropertyId::TextBoxEdge:
      case CSSPropertyId::TextDecorationSkipInk:
      case CSSPropertyId::TextDecorationThickness:
      case CSSPropertyId::TextJustify:
      case CSSPropertyId::TextRendering:
      case CSSPropertyId::TextUnderlineOffset:
      case CSSPropertyId::TextUnderlinePosition:
      case CSSPropertyId::TextWrapStyle:
      case CSSPropertyId::Top:
      case CSSPropertyId::TouchAction:
      case CSSPropertyId::ViewTimelineInset:
      case CSSPropertyId::WebkitFontSmoothing:
      case CSSPropertyId::WebkitHyphenateLimitAfter:
      case CSSPropertyId::WebkitHyphenateLimitBefore:
      case CSSPropertyId::WebkitLocale:
      case CSSPropertyId::WebkitUserDrag:
      case CSSPropertyId::Widows:
      case CSSPropertyId::Width:
      case CSSPropertyId::WillChange:
      case CSSPropertyId::ZIndex:
      {
        return CSSValueId::Auto;
      }
      case CSSPropertyId::BorderBlockEndWidth:
      case CSSPropertyId::BorderBlockStartWidth:
      case CSSPropertyId::BorderBottomWidth:
      case CSSPropertyId::BorderInlineEndWidth:
      case CSSPropertyId::BorderInlineStartWidth:
      case CSSPropertyId::BorderLeftWidth:
      case CSSPropertyId::BorderRightWidth:
      case CSSPropertyId::BorderTopWidth:
      case CSSPropertyId::ColumnRuleWidth:
      case CSSPropertyId::FontSize:
      case CSSPropertyId::OutlineWidth:
      {
        return CSSValueId::Medium;
      }
      case CSSPropertyId::AnchorName:
      case CSSPropertyId::AnchorScope:
      case CSSPropertyId::AnimationFillMode:
      case CSSPropertyId::AnimationName:
      case CSSPropertyId::Appearance:
      case CSSPropertyId::AppleColorFilter:
      case CSSPropertyId::BackdropFilter:
      case CSSPropertyId::BackgroundImage:
      case CSSPropertyId::BlockEllipsis:
      case CSSPropertyId::BlockStepSize:
      case CSSPropertyId::BorderBlockEndStyle:
      case CSSPropertyId::BorderBlockStartStyle:
      case CSSPropertyId::BorderBottomStyle:
      case CSSPropertyId::BorderImageSource:
      case CSSPropertyId::BorderInlineEndStyle:
      case CSSPropertyId::BorderInlineStartStyle:
      case CSSPropertyId::BorderLeftStyle:
      case CSSPropertyId::BorderRightStyle:
      case CSSPropertyId::BorderTopStyle:
      case CSSPropertyId::BoxShadow:
      case CSSPropertyId::Clear:
      case CSSPropertyId::ClipPath:
      case CSSPropertyId::ColumnRuleStyle:
      case CSSPropertyId::ColumnSpan:
      case CSSPropertyId::Contain:
      case CSSPropertyId::ContainIntrinsicBlockSize:
      case CSSPropertyId::ContainIntrinsicHeight:
      case CSSPropertyId::ContainIntrinsicInlineSize:
      case CSSPropertyId::ContainIntrinsicWidth:
      case CSSPropertyId::ContainerName:
      case CSSPropertyId::CounterIncrement:
      case CSSPropertyId::CounterReset:
      case CSSPropertyId::CounterSet:
      case CSSPropertyId::D:
      case CSSPropertyId::Filter:
      case CSSPropertyId::Float:
      case CSSPropertyId::FontSizeAdjust:
      case CSSPropertyId::GridTemplateAreas:
      case CSSPropertyId::GridTemplateColumns:
      case CSSPropertyId::GridTemplateRows:
      case CSSPropertyId::HangingPunctuation:
      case CSSPropertyId::ListStyleImage:
      case CSSPropertyId::MarginTrim:
      case CSSPropertyId::MarkerEnd:
      case CSSPropertyId::MarkerMid:
      case CSSPropertyId::MarkerStart:
      case CSSPropertyId::MaskBorderSource:
      case CSSPropertyId::MaskImage:
      case CSSPropertyId::MaxBlockSize:
      case CSSPropertyId::MaxHeight:
      case CSSPropertyId::MaxInlineSize:
      case CSSPropertyId::MaxLines:
      case CSSPropertyId::MaxWidth:
      case CSSPropertyId::OffsetPath:
      case CSSPropertyId::OutlineStyle:
      case CSSPropertyId::Perspective:
      case CSSPropertyId::PositionArea:
      case CSSPropertyId::PositionTryFallbacks:
      case CSSPropertyId::Resize:
      case CSSPropertyId::Rotate:
      case CSSPropertyId::Scale:
      case CSSPropertyId::ScrollSnapAlign:
      case CSSPropertyId::ScrollSnapType:
      case CSSPropertyId::ScrollTimelineName:
      case CSSPropertyId::ShapeOutside:
      case CSSPropertyId::Stroke:
      case CSSPropertyId::StrokeDasharray:
      case CSSPropertyId::TextBoxTrim:
      case CSSPropertyId::TextCombineUpright:
      case CSSPropertyId::TextDecorationLine:
      case CSSPropertyId::TextEmphasisStyle:
      case CSSPropertyId::TextGroupAlign:
      case CSSPropertyId::TextShadow:
      case CSSPropertyId::TextTransform:
      case CSSPropertyId::TimelineScope:
      case CSSPropertyId::Transform:
      case CSSPropertyId::Translate:
      case CSSPropertyId::VectorEffect:
      case CSSPropertyId::ViewTimelineName:
      case CSSPropertyId::ViewTransitionClass:
      case CSSPropertyId::ViewTransitionName:
      case CSSPropertyId::WebkitLineAlign:
      case CSSPropertyId::WebkitTextCombine:
      case CSSPropertyId::WebkitTextDecorationsInEffect:
      case CSSPropertyId::WebkitTextSecurity:
      {
        return CSSValueId::None;
      }
      case CSSPropertyId::TextOrientation:
      {
        return CSSValueId::Mixed;
      }
      case CSSPropertyId::AnimationIterationCount:
      case CSSPropertyId::BorderImageWidth:
      case CSSPropertyId::FillOpacity:
      case CSSPropertyId::FlexShrink:
      case CSSPropertyId::FloodOpacity:
      case CSSPropertyId::Opacity:
      case CSSPropertyId::StopOpacity:
      case CSSPropertyId::StrokeOpacity:
      case CSSPropertyId::Zoom:
      {
        return InitialNumericValue {1, CSSUnitType::Number};
      }
      case CSSPropertyId::TextAutospace:
      {
        return CSSValueId::NoAutospace;
      }
      case CSSPropertyId::TextSpacingTrim:
      {
        return CSSValueId::SpaceAll;
      }
      case CSSPropertyId::AlignmentBaseline:
      case CSSPropertyId::BaselineShift:
      case CSSPropertyId::VerticalAlign:
      {
        return CSSValueId::Baseline;
      }
      case CSSPropertyId::AnimationComposition:
      {
        return CSSValueId::Replace;
      }
      case CSSPropertyId::AnimationDelay:
      case CSSPropertyId::TransitionDelay:
      case CSSPropertyId::TransitionDuration:
      {
        return InitialNumericValue {0, CSSUnitType::s};
      }
      case CSSPropertyId::AnimationPlayState:
      {
        return CSSValueId::Running;
      }
      case CSSPropertyId::AnimationTimingFunction:
      case CSSPropertyId::TransitionTimingFunction:
      {
        return CSSValueId::Ease;
      }
      case CSSPropertyId::BackfaceVisibility:
      case CSSPropertyId::ContentVisibility:
      case CSSPropertyId::OverflowBlock:
      case CSSPropertyId::OverflowInline:
      case CSSPropertyId::OverflowX:
      case CSSPropertyId::OverflowY:
      case CSSPropertyId::Visibility:
      {
        return CSSValueId::Visible;
      }
      case CSSPropertyId::BackgroundAttachment:
      {
        return CSSValueId::Scroll;
      }
      case CSSPropertyId::BackgroundClip:
      case CSSPropertyId::MaskClip:
      case CSSPropertyId::MaskOrigin:
      {
        return CSSValueId::BorderBox;
      }
      case CSSPropertyId::BackgroundColor:
      case CSSPropertyId::StrokeColor:
      {
        return CSSValueId::Transparent;
      }
      case CSSPropertyId::BackgroundOrigin:
      {
        return CSSValueId::PaddingBox;
      }
      case CSSPropertyId::BackgroundPositionX:
      case CSSPropertyId::BackgroundPositionY:
      case CSSPropertyId::WebkitMaskPositionX:
      case CSSPropertyId::WebkitMaskPositionY:
      {
        return InitialNumericValue {0, CSSUnitType::Percentage};
      }
      case CSSPropertyId::BackgroundRepeat:
      case CSSPropertyId::MaskRepeat:
      {
        return CSSValueId::Repeat;
      }
      case CSSPropertyId::BlockStepInsert:
      {
        return CSSValueId::MarginBox;
      }
      case CSSPropertyId::BlockStepRound:
      {
        return CSSValueId::Up;
      }
      case CSSPropertyId::BorderCollapse:
      {
        return CSSValueId::Separate;
      }
      case CSSPropertyId::BorderImageRepeat:
      case CSSPropertyId::MaskBorderRepeat:
      {
        return CSSValueId::Stretch;
      }
      case CSSPropertyId::BorderImageSlice:
      {
        return InitialNumericValue {100, CSSUnitType::Percentage};
      }
      case CSSPropertyId::BoxSizing:
      {
        return CSSValueId::ContentBox;
      }
      case CSSPropertyId::CaptionSide:
      {
        return CSSValueId::Top;
      }
      case CSSPropertyId::ClipRule:
      case CSSPropertyId::FillRule:
      {
        return CSSValueId::Nonzero;
      }
      case CSSPropertyId::Color:
      {
        return CSSValueId::Canvastext;
      }
      case CSSPropertyId::ColorInterpolation:
      {
        return CSSValueId::SRGB;
      }
      case CSSPropertyId::ColorInterpolationFilters:
      {
        return CSSValueId::LinearRGB;
      }
      case CSSPropertyId::ColumnFill:
      {
        return CSSValueId::Balance;
      }
      case CSSPropertyId::BorderBlockEndColor:
      case CSSPropertyId::BorderBlockStartColor:
      case CSSPropertyId::BorderBottomColor:
      case CSSPropertyId::BorderInlineEndColor:
      case CSSPropertyId::BorderInlineStartColor:
      case CSSPropertyId::BorderLeftColor:
      case CSSPropertyId::BorderRightColor:
      case CSSPropertyId::BorderTopColor:
      case CSSPropertyId::ColumnRuleColor:
      case CSSPropertyId::OutlineColor:
      case CSSPropertyId::TextDecorationColor:
      case CSSPropertyId::TextEmphasisColor:
      case CSSPropertyId::WebkitTextFillColor:
      {
        return CSSValueId::Currentcolor;
      }
      case CSSPropertyId::BorderBottomLeftRadius:
      case CSSPropertyId::BorderBottomRightRadius:
      case CSSPropertyId::BorderEndEndRadius:
      case CSSPropertyId::BorderEndStartRadius:
      case CSSPropertyId::BorderStartEndRadius:
      case CSSPropertyId::BorderStartStartRadius:
      case CSSPropertyId::BorderTopLeftRadius:
      case CSSPropertyId::BorderTopRightRadius:
      case CSSPropertyId::Cx:
      case CSSPropertyId::Cy:
      case CSSPropertyId::MarginBlockEnd:
      case CSSPropertyId::MarginBlockStart:
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginInlineEnd:
      case CSSPropertyId::MarginInlineStart:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      case CSSPropertyId::MinBlockSize:
      case CSSPropertyId::MinInlineSize:
      case CSSPropertyId::OffsetDistance:
      case CSSPropertyId::OutlineOffset:
      case CSSPropertyId::PaddingBlockEnd:
      case CSSPropertyId::PaddingBlockStart:
      case CSSPropertyId::PaddingBottom:
      case CSSPropertyId::PaddingInlineEnd:
      case CSSPropertyId::PaddingInlineStart:
      case CSSPropertyId::PaddingLeft:
      case CSSPropertyId::PaddingRight:
      case CSSPropertyId::PaddingTop:
      case CSSPropertyId::R:
      case CSSPropertyId::ScrollMarginBlockEnd:
      case CSSPropertyId::ScrollMarginBlockStart:
      case CSSPropertyId::ScrollMarginBottom:
      case CSSPropertyId::ScrollMarginInlineEnd:
      case CSSPropertyId::ScrollMarginInlineStart:
      case CSSPropertyId::ScrollMarginLeft:
      case CSSPropertyId::ScrollMarginRight:
      case CSSPropertyId::ScrollMarginTop:
      case CSSPropertyId::ShapeMargin:
      case CSSPropertyId::TextIndent:
      case CSSPropertyId::TransformOriginZ:
      case CSSPropertyId::WebkitBorderHorizontalSpacing:
      case CSSPropertyId::WebkitBorderVerticalSpacing:
      case CSSPropertyId::X:
      case CSSPropertyId::Y:
      {
        return InitialNumericValue {0, CSSUnitType::px};
      }
      case CSSPropertyId::DynamicRangeLimit:
      case CSSPropertyId::WebkitHyphenateLimitLines:
      {
        return CSSValueId::NoLimit;
      }
      case CSSPropertyId::EmptyCells:
      {
        return CSSValueId::Show;
      }
      case CSSPropertyId::FieldSizing:
      {
        return CSSValueId::Fixed;
      }
      case CSSPropertyId::Fill:
      case CSSPropertyId::FloodColor:
      case CSSPropertyId::StopColor:
      {
        return CSSValueId::Black;
      }
      case CSSPropertyId::FlexDirection:
      {
        return CSSValueId::Row;
      }
      case CSSPropertyId::FlexWrap:
      {
        return CSSValueId::Nowrap;
      }
      case CSSPropertyId::GlyphOrientationHorizontal:
      {
        return InitialNumericValue {0, CSSUnitType::deg};
      }
      case CSSPropertyId::Hyphens:
      {
        return CSSValueId::Manual;
      }
      case CSSPropertyId::ImageOrientation:
      {
        return CSSValueId::FromImage;
      }
      case CSSPropertyId::JustifyItems:
      {
        return CSSValueId::Legacy;
      }
      case CSSPropertyId::LightingColor:
      {
        return CSSValueId::White;
      }
      case CSSPropertyId::LineFitEdge:
      {
        return CSSValueId::Leading;
      }
      case CSSPropertyId::ListStylePosition:
      {
        return CSSValueId::Outside;
      }
      case CSSPropertyId::ListStyleType:
      {
        return CSSValueId::Disc;
      }
      case CSSPropertyId::MaskComposite:
      {
        return CSSValueId::Add;
      }
      case CSSPropertyId::MaskMode:
      {
        return CSSValueId::MatchSource;
      }
      case CSSPropertyId::MaskType:
      {
        return CSSValueId::Luminance;
      }
      case CSSPropertyId::ObjectFit:
      {
        return CSSValueId::Fill;
      }
      case CSSPropertyId::PerspectiveOriginX:
      case CSSPropertyId::PerspectiveOriginY:
      case CSSPropertyId::TransformOriginX:
      case CSSPropertyId::TransformOriginY:
      {
        return InitialNumericValue {50, CSSUnitType::Percentage};
      }
      case CSSPropertyId::Position:
      {
        return CSSValueId::Static;
      }
      case CSSPropertyId::PositionVisibility:
      {
        return CSSValueId::AnchorsVisible;
      }
      case CSSPropertyId::PrintColorAdjust:
      {
        return CSSValueId::Economy;
      }
      case CSSPropertyId::RubyAlign:
      {
        return CSSValueId::SpaceAround;
      }
      case CSSPropertyId::ScrollTimelineAxis:
      case CSSPropertyId::ViewTimelineAxis:
      {
        return CSSValueId::Block;
      }
      case CSSPropertyId::StrokeLinecap:
      {
        return CSSValueId::Butt;
      }
      case CSSPropertyId::StrokeLinejoin:
      {
        return CSSValueId::Miter;
      }
      case CSSPropertyId::StrokeMiterlimit:
      {
        return InitialNumericValue {4, CSSUnitType::Number};
      }
      case CSSPropertyId::StrokeWidth:
      {
        return InitialNumericValue {1, CSSUnitType::px};
      }
      case CSSPropertyId::TabSize:
      {
        return InitialNumericValue {8, CSSUnitType::Number};
      }
      case CSSPropertyId::TextAlign:
      case CSSPropertyId::TextAnchor:
      {
        return CSSValueId::Start;
      }
      case CSSPropertyId::TextDecorationStyle:
      {
        return CSSValueId::Solid;
      }
      case CSSPropertyId::TextOverflow:
      {
        return CSSValueId::Clip;
      }
      case CSSPropertyId::TextWrapMode:
      {
        return CSSValueId::Wrap;
      }
      case CSSPropertyId::TransformBox:
      {
        return CSSValueId::ViewBox;
      }
      case CSSPropertyId::TransformStyle:
      {
        return CSSValueId::Flat;
      }
      case CSSPropertyId::TransitionProperty:
      {
        return CSSValueId::All;
      }
      case CSSPropertyId::WhiteSpaceCollapse:
      {
        return CSSValueId::Collapse;
      }
      case CSSPropertyId::WebkitBoxDecorationBreak:
      {
        return CSSValueId::Slice;
      }
      case CSSPropertyId::WebkitRtlOrdering:
      {
        return CSSValueId::Logical;
      }
      case CSSPropertyId::WebkitRubyPosition:
      {
        return CSSValueId::Before;
      }
      case CSSPropertyId::WebkitUserModify:
      {
        return CSSValueId::ReadOnly;
      }
      case CSSPropertyId::WebkitUserSelect:
      {
        return CSSValueId::Text;
      }
      case CSSPropertyId::CornerBottomLeftShape:
      case CSSPropertyId::CornerBottomRightShape:
      case CSSPropertyId::CornerEndEndShape:
      case CSSPropertyId::CornerEndStartShape:
      case CSSPropertyId::CornerStartEndShape:
      case CSSPropertyId::CornerStartStartShape:
      case CSSPropertyId::CornerTopLeftShape:
      case CSSPropertyId::CornerTopRightShape:
      {
        return CSSValueId::Round;
      }
      default:
      {
        assert(false);
      }
    }
  }
}
