// <auto-generated>
//   Generated at 2026-08-21 17:42:47 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.HTML/CSS/Properties/Enums/CSSPropertyId.hpp"
#include "Krystal.HTML/CSS/Values/CSSUnits.hpp"
#include "Krystal.HTML/CSS/Values/Enums/CSSValueId.hpp"
#include "Krystal.Lib/Types/Variant.hpp"
#include <cassert>

namespace Krys::HTML
{
  struct InitialNumericValue
  {
    double Number;
    CSSUnitType Type { CSSUnitType::Number };
  };

  using InitialValue = Variant<CSSValueId, InitialNumericValue>;

  // Skipping CSSPropertyId::FontFamily, initial is a special value [SpecialLiteral @initial-font-family]
  KRYS_NODISCARD constexpr static InitialValue InitialValueForLonghand(CSSPropertyId longhand) noexcept
  {
    switch (longhand)
    {
      case CSSPropertyId::WritingMode:
      {
        return CSSValueId::HorizontalTb;
      }
      case CSSPropertyId::Direction:
      {
        return CSSValueId::Ltr;
      }
      case CSSPropertyId::Display:
      {
        return CSSValueId::Inline;
      }
      case CSSPropertyId::FontFeatureSettings:
      case CSSPropertyId::FontPalette:
      case CSSPropertyId::FontStyle:
      case CSSPropertyId::FontVariantAlternates:
      case CSSPropertyId::FontVariantCaps:
      case CSSPropertyId::FontVariantEastAsian:
      case CSSPropertyId::FontVariantEmoji:
      case CSSPropertyId::FontVariantLigatures:
      case CSSPropertyId::FontVariantNumeric:
      case CSSPropertyId::FontVariantPosition:
      case CSSPropertyId::FontWeight:
      case CSSPropertyId::FontWidth:
      case CSSPropertyId::LineHeight:
      {
        return CSSValueId::Normal;
      }
      case CSSPropertyId::FontKerning:
      case CSSPropertyId::FontSynthesisSmallCaps:
      case CSSPropertyId::FontSynthesisStyle:
      case CSSPropertyId::FontSynthesisWeight:
      case CSSPropertyId::WebkitFontSmoothing:
      {
        return CSSValueId::Auto;
      }
      case CSSPropertyId::FontSize:
      {
        return CSSValueId::Medium;
      }
      case CSSPropertyId::BackgroundImage:
      case CSSPropertyId::D:
      case CSSPropertyId::FontSizeAdjust:
      case CSSPropertyId::MarginTrim:
      {
        return CSSValueId::None;
      }
      case CSSPropertyId::CornerBottomLeftShape:
      case CSSPropertyId::CornerBottomRightShape:
      case CSSPropertyId::CornerEndEndShape:
      case CSSPropertyId::CornerEndStartShape:
      case CSSPropertyId::CornerStartEndShape:
      case CSSPropertyId::CornerStartStartShape:
      case CSSPropertyId::CornerTopLeftShape:
      case CSSPropertyId::CornerTopRightShape:
      {
        return CSSValueId::Round;
      }
      case CSSPropertyId::MarginBlockEnd:
      case CSSPropertyId::MarginBlockStart:
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginInlineEnd:
      case CSSPropertyId::MarginInlineStart:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      case CSSPropertyId::PaddingBlockEnd:
      case CSSPropertyId::PaddingBlockStart:
      case CSSPropertyId::PaddingBottom:
      case CSSPropertyId::PaddingInlineEnd:
      case CSSPropertyId::PaddingInlineStart:
      case CSSPropertyId::PaddingLeft:
      case CSSPropertyId::PaddingRight:
      case CSSPropertyId::PaddingTop:
      {
        return InitialNumericValue { 0, CSSUnitType::px };
      }
      default:
      {
        assert(false);
      }
    }
  }
}
