// <auto-generated>
//   Generated at 2026-08-13 21:31:45 by css-values.generator.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.Lib/Core/Enum.hpp"
#include "Krystal.Lib/String/String.hpp"

namespace Krys::HTML
{
  /// @brief An enumeration of all CSS value identifiers.
  enum class CSSValueId : uint16
  {
    /// @brief Represents an invalid or unrecognized CSS keyword.
    Invalid = 0,
    Initial,
    Inherit,
    Unset,
    Revert,
    RevertLayer,
    And,
    Or,
    Not,
    Default,
    None,
  };

  KRYS_NODISCARD constexpr CSSValueId ParseCSSValueId(utf8_stringview str) noexcept
  {
    if (str == u8"initial")
    {
      return CSSValueId::Initial;
    }
    if (str == u8"inherit")
    {
      return CSSValueId::Inherit;
    }
    if (str == u8"unset")
    {
      return CSSValueId::Unset;
    }
    if (str == u8"revert")
    {
      return CSSValueId::Revert;
    }
    if (str == u8"revert-layer")
    {
      return CSSValueId::RevertLayer;
    }
    if (str == u8"and")
    {
      return CSSValueId::And;
    }
    if (str == u8"or")
    {
      return CSSValueId::Or;
    }
    if (str == u8"not")
    {
      return CSSValueId::Not;
    }
    if (str == u8"default")
    {
      return CSSValueId::Default;
    }
    if (str == u8"none")
    {
      return CSSValueId::None;
    }
    
    return CSSValueId::Invalid;
  }

  KRYS_NODISCARD constexpr utf8_stringview ToString(CSSValueId value) noexcept
  {
    switch (value)
    {
      case CSSValueId::Initial:
      {
        return u8"initial";
      }
      case CSSValueId::Inherit:
      {
        return u8"inherit";
      }
      case CSSValueId::Unset:
      {
        return u8"unset";
      }
      case CSSValueId::Revert:
      {
        return u8"revert";
      }
      case CSSValueId::RevertLayer:
      {
        return u8"revert-layer";
      }
      case CSSValueId::And:
      {
        return u8"and";
      }
      case CSSValueId::Or:
      {
        return u8"or";
      }
      case CSSValueId::Not:
      {
        return u8"not";
      }
      case CSSValueId::Default:
      {
        return u8"default";
      }
      case CSSValueId::None:
      {
        return u8"none";
      }
      default:
      {
        return u8"Invalid";
      }
    }
  }
}

KRYS_DEFINE_CONTIGUOUS_ENUM_TRAITS(Krys::HTML::CSSValueId, 11uz);