// <auto-generated>
//   Generated at 2026-08-21 18:22:47 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.Lib/Types/Array.hpp"
#include "Krystal.Lib/Types/Span.hpp"
#include "Krystal.Lib/Core/Enum.hpp"
#include "Krystal.HTML/CSS/Types/CSSOMString.hpp"

namespace Krys::HTML
{
  enum class CSSPropertyId : uint16
  {
    Invalid = 0,
    Custom = 1,
    WritingMode = 2,
    Direction = 3,
    Display = 4,
    FontFamily = 5,
    FontFeatureSettings = 6,
    FontKerning = 7,
    FontPalette = 8,
    FontSize = 9,
    FontSizeAdjust = 10,
    FontStyle = 11,
    FontSynthesisSmallCaps = 12,
    FontSynthesisStyle = 13,
    FontSynthesisWeight = 14,
    FontVariantAlternates = 15,
    FontVariantCaps = 16,
    FontVariantEastAsian = 17,
    FontVariantEmoji = 18,
    FontVariantLigatures = 19,
    FontVariantNumeric = 20,
    FontVariantPosition = 21,
    FontWeight = 22,
    FontWidth = 23,
    WebkitFontSmoothing = 24,
    BackgroundImage = 25,
    D = 26,
    LineHeight = 27,
    MarginTrim = 28,
    CornerBottomLeftShape = 29,
    CornerBottomRightShape = 30,
    CornerTopLeftShape = 31,
    CornerTopRightShape = 32,
    MarginBottom = 33,
    MarginLeft = 34,
    MarginRight = 35,
    MarginTop = 36,
    PaddingBottom = 37,
    PaddingLeft = 38,
    PaddingRight = 39,
    PaddingTop = 40,
    CornerEndEndShape = 41,
    CornerEndStartShape = 42,
    CornerStartEndShape = 43,
    CornerStartStartShape = 44,
    MarginBlockEnd = 45,
    MarginBlockStart = 46,
    MarginInlineEnd = 47,
    MarginInlineStart = 48,
    PaddingBlockEnd = 49,
    PaddingBlockStart = 50,
    PaddingInlineEnd = 51,
    PaddingInlineStart = 52,
    All = 53,
    CornerShape = 54,
    Font = 55,
    FontSynthesis = 56,
    FontVariant = 57,
    Margin = 58,
    MarginBlock = 59,
    MarginInline = 60,
    Padding = 61,
    PaddingBlock = 62,
    PaddingInline = 63,
  };

  /// @brief Enum value of the first "real" CSS property, which excludes
  /// CSSProperty::Invalid and CSSProperty::Custom.
  constexpr uint16 FirstCSSProperty = 2;

  /// @brief Total number of enum values in the CSSPropertyId enum. If making an array
  /// that can be indexed into using the enum value, use this as the size.
  constexpr uint16 CSSPropertyIdEnumValueCount = 64;

  /// @brief Number of "real" CSS properties. This differs from CSSPropertyIdEnumValueCount,
  /// as this doesn't consider CSSProperty::Invalid and CSSProperty::Custom.
  constexpr uint16 NumCSSProperties = 62;
  constexpr auto MaxCSSPropertyNameLength = 25uz;

  constexpr auto FirstTopPriorityProperty = CSSPropertyId::WritingMode;
  constexpr auto LastTopPriorityProperty = CSSPropertyId::WritingMode;
  constexpr auto FirstHighPriorityProperty = CSSPropertyId::Direction;
  constexpr auto LastHighPriorityProperty = CSSPropertyId::WebkitFontSmoothing;
  constexpr auto FirstMediumPriorityProperty = CSSPropertyId::BackgroundImage;
  constexpr auto LastMediumPriorityProperty = CSSPropertyId::BackgroundImage;
  constexpr auto FirstLowPriorityProperty = CSSPropertyId::D;
  constexpr auto LastLowPriorityProperty = CSSPropertyId::MarginTrim;
  constexpr auto FirstLogicalGroupPhysicalProperty = CSSPropertyId::CornerBottomLeftShape;
  constexpr auto LastLogicalGroupPhysicalProperty = CSSPropertyId::PaddingTop;
  constexpr auto FirstLogicalGroupLogicalProperty = CSSPropertyId::CornerEndEndShape;
  constexpr auto LastLogicalGroupLogicalProperty = CSSPropertyId::PaddingInlineStart;
  constexpr auto FirstLogicalGroupProperty = FirstLogicalGroupPhysicalProperty;
  constexpr auto LastLogicalGroupProperty = LastLogicalGroupLogicalProperty;
  constexpr auto FirstShorthandProperty = CSSPropertyId::All;
  constexpr auto LastShorthandProperty = CSSPropertyId::PaddingInline;
  constexpr auto NumCSSPropertyLonghands = static_cast<uint16>(FirstShorthandProperty) - FirstCSSProperty;

  extern const Array<CSSPropertyId, 51uz> ComputedPropertyIds;

  template<CSSPropertyId C>
  struct PropertyNameConstant
  {
    constexpr static auto value = C;
    constexpr bool operator==(const PropertyNameConstant &) const noexcept = default;
    constexpr bool operator==(CSSPropertyId other) const noexcept { return value == other; }
  };

  struct CSSPropertySettings
  {
    bool CornerShapePropertyEnabled : 1 { false };
    bool DPropertyEnabled : 1 { false };
    bool FontVariantEmojiPropertyEnabled : 1 { false };

    CSSPropertySettings() noexcept = default;
  };

  KRYS_NODISCARD bool operator==(const CSSPropertySettings &, const CSSPropertySettings &) noexcept;

  KRYS_NODISCARD bool IsInternal(CSSPropertyId id) noexcept;

  KRYS_NODISCARD bool IsExposed(CSSPropertyId id, const CSSPropertySettings *) noexcept;

  KRYS_NODISCARD bool IsExposed(CSSPropertyId id, const CSSPropertySettings &) noexcept;

  KRYS_NODISCARD CSSPropertyId FindCSSProperty(CSSOMStringView characters) noexcept;

  KRYS_NODISCARD CSSOMStringView ToString(CSSPropertyId id) noexcept;

  KRYS_NODISCARD CSSPropertyId CascadeAliasProperty(CSSPropertyId id) noexcept;

  template<CSSPropertyId First, CSSPropertyId Last>
  struct CSSPropertiesRange
  {
      struct Iterator
      {
          uint16 Index { static_cast<uint16>(First) };

          constexpr CSSPropertyId operator*() const noexcept
          {
            return static_cast<CSSPropertyId>(Index);
          }

          constexpr Iterator &operator++() noexcept
          {
            ++Index;
            return *this;
          }

          constexpr bool operator==(std::nullptr_t) const noexcept
          {
            return Index > static_cast<uint16>(Last);
          }
      };

      KRYS_NODISCARD constexpr static Iterator begin() noexcept
      {
        return {};
      }

      KRYS_NODISCARD constexpr static std::nullptr_t end() noexcept
      {
        return nullptr;
      }

      KRYS_NODISCARD constexpr static uint16_t size() noexcept
      {
        return Last - First + 1;
      }
  };

  using AllCSSPropertiesRange = CSSPropertiesRange<static_cast<CSSPropertyId>(FirstCSSProperty), LastShorthandProperty>;
  KRYS_NODISCARD constexpr AllCSSPropertiesRange AllCSSProperties() noexcept
  {
    return {};
  }

  using AllLonghandCSSPropertiesRange = CSSPropertiesRange<static_cast<CSSPropertyId>(FirstCSSProperty), LastLogicalGroupProperty>;
  KRYS_NODISCARD constexpr AllLonghandCSSPropertiesRange AllLonghandCSSProperties() noexcept
  {
    return {};
  }

  KRYS_NODISCARD constexpr bool IsLonghand(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= FirstCSSProperty
          && static_cast<uint16>(property) < static_cast<uint16>(FirstShorthandProperty);
  }

  KRYS_NODISCARD constexpr bool IsShorthand(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= static_cast<uint16>(FirstShorthandProperty)
          && static_cast<uint16>(property) <= static_cast<uint16>(LastShorthandProperty);
  }

  KRYS_NODISCARD constexpr bool IsLogicalPropertyGroupProperty(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= static_cast<uint16>(FirstLogicalGroupPhysicalProperty)
          && static_cast<uint16>(property) <= static_cast<uint16>(LastLogicalGroupLogicalProperty);
  }

  KRYS_NODISCARD constexpr bool IsLogicalPropertyGroupPhysicalProperty(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= static_cast<uint16>(FirstLogicalGroupPhysicalProperty)
          && static_cast<uint16>(property) <= static_cast<uint16>(LastLogicalGroupPhysicalProperty);
  }

  KRYS_NODISCARD constexpr bool IsLogicalPropertyGroupLogicalProperty(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= static_cast<uint16>(FirstLogicalGroupLogicalProperty)
          && static_cast<uint16>(property) <= static_cast<uint16>(LastLogicalGroupLogicalProperty);
  }
}

namespace Krys
{
  template<>
  struct DefaultHash<::Krys::HTML::CSSPropertyId> : IntegerHash<uint16>
  {
  };
}

KRYS_DEFINE_CONTIGUOUS_ENUM_TRAITS(::Krys::HTML::CSSPropertyId, ::Krys::HTML::CSSPropertyIdEnumValueCount);

namespace std
{
  template<>
  struct iterator_traits<Krys::HTML::AllCSSPropertiesRange::Iterator>
  {
    using value_type = Krys::HTML::CSSPropertyId;
  };

  template<>
  struct iterator_traits<Krys::HTML::AllLonghandCSSPropertiesRange::Iterator>
  { 
    using value_type = Krys::HTML::CSSPropertyId;
  };
}
