// <auto-generated>
//   Generated at 2026-08-28 18:29:50 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.Lib/Types/Array.hpp"
#include "Krystal.Lib/Types/Span.hpp"
#include "Krystal.Lib/Core/Enum.hpp"
#include "Krystal.HTML/CSS/Types/CSSOMString.hpp"

namespace Krys::HTML
{
  enum class CSSPropertyId : uint16
  {
    Invalid = 0,
    Custom = 1,
    MathDepth = 2,
    RubyPosition = 3,
    WritingMode = 4,
    Direction = 5,
    Display = 6,
    FontFamily = 7,
    FontFeatureSettings = 8,
    FontKerning = 9,
    FontPalette = 10,
    FontSize = 11,
    FontSizeAdjust = 12,
    FontStyle = 13,
    FontSynthesisSmallCaps = 14,
    FontSynthesisStyle = 15,
    FontSynthesisWeight = 16,
    FontVariantAlternates = 17,
    FontVariantCaps = 18,
    FontVariantEastAsian = 19,
    FontVariantEmoji = 20,
    FontVariantLigatures = 21,
    FontVariantNumeric = 22,
    FontVariantPosition = 23,
    FontWeight = 24,
    FontWidth = 25,
    TextOrientation = 26,
    TextRendering = 27,
    Zoom = 28,
    WebkitFontSmoothing = 29,
    WebkitLocale = 30,
    LetterSpacing = 31,
    TextAutospace = 32,
    TextSpacingTrim = 33,
    WordSpacing = 34,
    BackgroundImage = 35,
    MaskImage = 36,
    AccentColor = 37,
    AdditiveSymbols = 38,
    AlignContent = 39,
    AlignItems = 40,
    AlignSelf = 41,
    AlignmentBaseline = 42,
    AnchorName = 43,
    AnchorScope = 44,
    AnimationComposition = 45,
    AnimationDelay = 46,
    AnimationDirection = 47,
    AnimationDuration = 48,
    AnimationFillMode = 49,
    AnimationIterationCount = 50,
    AnimationName = 51,
    AnimationPlayState = 52,
    AnimationRangeEnd = 53,
    AnimationRangeStart = 54,
    AnimationTimeline = 55,
    AnimationTimingFunction = 56,
    Appearance = 57,
    AspectRatio = 58,
    BackdropFilter = 59,
    BackfaceVisibility = 60,
    BackgroundAttachment = 61,
    BackgroundBlendMode = 62,
    BackgroundClip = 63,
    BackgroundColor = 64,
    BackgroundOrigin = 65,
    BackgroundPositionX = 66,
    BackgroundPositionY = 67,
    BackgroundRepeat = 68,
    BackgroundSize = 69,
    BasePalette = 70,
    BaselineShift = 71,
    BlockEllipsis = 72,
    BlockStepAlign = 73,
    BlockStepInsert = 74,
    BlockStepRound = 75,
    BlockStepSize = 76,
    BorderCollapse = 77,
    BorderImageOutset = 78,
    BorderImageRepeat = 79,
    BorderImageSlice = 80,
    BorderImageSource = 81,
    BorderImageWidth = 82,
    BoxShadow = 83,
    BoxSizing = 84,
    BreakAfter = 85,
    BreakBefore = 86,
    BreakInside = 87,
    BufferedRendering = 88,
    CaptionSide = 89,
    CaretColor = 90,
    Clear = 91,
    Clip = 92,
    ClipPath = 93,
    ClipRule = 94,
    Color = 95,
    ColorInterpolation = 96,
    ColorInterpolationFilters = 97,
    ColumnCount = 98,
    ColumnFill = 99,
    ColumnGap = 100,
    ColumnRuleColor = 101,
    ColumnRuleStyle = 102,
    ColumnRuleWidth = 103,
    ColumnSpan = 104,
    ColumnWidth = 105,
    Contain = 106,
    ContainerName = 107,
    ContainerType = 108,
    Content = 109,
    ContentVisibility = 110,
    Continue = 111,
    CounterIncrement = 112,
    CounterReset = 113,
    CounterSet = 114,
    Cursor = 115,
    Cx = 116,
    Cy = 117,
    D = 118,
    DominantBaseline = 119,
    DynamicRangeLimit = 120,
    EmptyCells = 121,
    Fallback = 122,
    FieldSizing = 123,
    Fill = 124,
    FillOpacity = 125,
    FillRule = 126,
    Filter = 127,
    FlexBasis = 128,
    FlexDirection = 129,
    FlexGrow = 130,
    FlexShrink = 131,
    FlexWrap = 132,
    Float = 133,
    FloodColor = 134,
    FloodOpacity = 135,
    FontDisplay = 136,
    GlyphOrientationHorizontal = 137,
    GlyphOrientationVertical = 138,
    GridAutoColumns = 139,
    GridAutoFlow = 140,
    GridAutoRows = 141,
    GridColumnEnd = 142,
    GridColumnStart = 143,
    GridRowEnd = 144,
    GridRowStart = 145,
    GridTemplateAreas = 146,
    GridTemplateColumns = 147,
    GridTemplateRows = 148,
    HangingPunctuation = 149,
    HyphenateCharacter = 150,
    Hyphens = 151,
    ImageOrientation = 152,
    ImageRendering = 153,
    Inherits = 154,
    InitialValue = 155,
    InputSecurity = 156,
    Isolation = 157,
    ItemTolerance = 158,
    JustifyContent = 159,
    JustifyItems = 160,
    JustifySelf = 161,
    LightingColor = 162,
    LineBreak = 163,
    LineFitEdge = 164,
    LineHeight = 165,
    ListStyleImage = 166,
    ListStylePosition = 167,
    ListStyleType = 168,
    MarginTrim = 169,
    MarkerEnd = 170,
    MarkerMid = 171,
    MarkerStart = 172,
    MaskBorderOutset = 173,
    MaskBorderRepeat = 174,
    MaskBorderSlice = 175,
    MaskBorderSource = 176,
    MaskBorderWidth = 177,
    MaskClip = 178,
    MaskComposite = 179,
    MaskMode = 180,
    MaskOrigin = 181,
    MaskRepeat = 182,
    MaskSize = 183,
    MaskType = 184,
    MathShift = 185,
    MathStyle = 186,
    MaxLines = 187,
    MixBlendMode = 188,
    Navigation = 189,
    Negative = 190,
    ObjectFit = 191,
    ObjectPosition = 192,
    OffsetAnchor = 193,
    OffsetDistance = 194,
    OffsetPath = 195,
    OffsetPosition = 196,
    OffsetRotate = 197,
    Opacity = 198,
    Order = 199,
    Orphans = 200,
    OutlineColor = 201,
    OutlineOffset = 202,
    OutlineStyle = 203,
    OutlineWidth = 204,
    OverflowAnchor = 205,
    OverflowWrap = 206,
    OverrideColors = 207,
    Pad = 208,
    Page = 209,
    PaintOrder = 210,
    Perspective = 211,
    PerspectiveOriginX = 212,
    PerspectiveOriginY = 213,
    PointerEvents = 214,
    Position = 215,
    PositionAnchor = 216,
    PositionArea = 217,
    PositionTryFallbacks = 218,
    PositionTryOrder = 219,
    PositionVisibility = 220,
    Prefix = 221,
    PrintColorAdjust = 222,
    Quotes = 223,
    R = 224,
    Range = 225,
    Resize = 226,
    Result = 227,
    Rotate = 228,
    RowGap = 229,
    RubyAlign = 230,
    RubyOverhang = 231,
    Rx = 232,
    Ry = 233,
    Scale = 234,
    ScrollBehavior = 235,
    ScrollSnapAlign = 236,
    ScrollSnapStop = 237,
    ScrollSnapType = 238,
    ScrollTimelineAxis = 239,
    ScrollTimelineName = 240,
    ScrollbarColor = 241,
    ScrollbarGutter = 242,
    ScrollbarWidth = 243,
    ShapeImageThreshold = 244,
    ShapeMargin = 245,
    ShapeOutside = 246,
    ShapeRendering = 247,
    Size = 248,
    SizeAdjust = 249,
    SpeakAs = 250,
    Src = 251,
    StopColor = 252,
    StopOpacity = 253,
    Stroke = 254,
    StrokeColor = 255,
    StrokeDasharray = 256,
    StrokeDashoffset = 257,
    StrokeLinecap = 258,
    StrokeLinejoin = 259,
    StrokeMiterlimit = 260,
    StrokeOpacity = 261,
    StrokeWidth = 262,
    Suffix = 263,
    Symbols = 264,
    Syntax = 265,
    System = 266,
    TabSize = 267,
    TableLayout = 268,
    TextAlign = 269,
    TextAlignLast = 270,
    TextAnchor = 271,
    TextBoxEdge = 272,
    TextBoxTrim = 273,
    TextCombineUpright = 274,
    TextDecorationColor = 275,
    TextDecorationLine = 276,
    TextDecorationSkipInk = 277,
    TextDecorationStyle = 278,
    TextDecorationThickness = 279,
    TextEmphasisColor = 280,
    TextEmphasisPosition = 281,
    TextEmphasisStyle = 282,
    TextGroupAlign = 283,
    TextIndent = 284,
    TextJustify = 285,
    TextOverflow = 286,
    TextShadow = 287,
    TextTransform = 288,
    TextUnderlineOffset = 289,
    TextUnderlinePosition = 290,
    TextWrapMode = 291,
    TextWrapStyle = 292,
    TimelineScope = 293,
    TouchAction = 294,
    Transform = 295,
    TransformBox = 296,
    TransformOriginX = 297,
    TransformOriginY = 298,
    TransformOriginZ = 299,
    TransformStyle = 300,
    TransitionBehavior = 301,
    TransitionDelay = 302,
    TransitionDuration = 303,
    TransitionProperty = 304,
    TransitionTimingFunction = 305,
    Translate = 306,
    Types = 307,
    UnicodeBidi = 308,
    UnicodeRange = 309,
    VectorEffect = 310,
    VerticalAlign = 311,
    ViewTimelineAxis = 312,
    ViewTimelineInset = 313,
    ViewTimelineName = 314,
    ViewTransitionClass = 315,
    ViewTransitionName = 316,
    Visibility = 317,
    WhiteSpaceCollapse = 318,
    Widows = 319,
    WillChange = 320,
    WordBreak = 321,
    X = 322,
    Y = 323,
    ZIndex = 324,
    AppleColorFilter = 325,
    WebkitBorderHorizontalSpacing = 326,
    WebkitBorderVerticalSpacing = 327,
    WebkitBoxDecorationBreak = 328,
    WebkitColumnProgression = 329,
    WebkitHyphenateLimitAfter = 330,
    WebkitHyphenateLimitBefore = 331,
    WebkitHyphenateLimitLines = 332,
    WebkitInitialLetter = 333,
    WebkitLineAlign = 334,
    WebkitLineBoxContain = 335,
    WebkitMaskPositionX = 336,
    WebkitMaskPositionY = 337,
    WebkitRtlOrdering = 338,
    WebkitRubyPosition = 339,
    WebkitTextCombine = 340,
    WebkitTextDecorationsInEffect = 341,
    WebkitTextFillColor = 342,
    WebkitTextSecurity = 343,
    WebkitUserDrag = 344,
    WebkitUserModify = 345,
    WebkitUserSelect = 346,
    BorderBottomColor = 347,
    BorderBottomLeftRadius = 348,
    BorderBottomRightRadius = 349,
    BorderBottomStyle = 350,
    BorderBottomWidth = 351,
    BorderLeftColor = 352,
    BorderLeftStyle = 353,
    BorderLeftWidth = 354,
    BorderRightColor = 355,
    BorderRightStyle = 356,
    BorderRightWidth = 357,
    BorderTopColor = 358,
    BorderTopLeftRadius = 359,
    BorderTopRightRadius = 360,
    BorderTopStyle = 361,
    BorderTopWidth = 362,
    Bottom = 363,
    ContainIntrinsicHeight = 364,
    ContainIntrinsicWidth = 365,
    CornerBottomLeftShape = 366,
    CornerBottomRightShape = 367,
    CornerTopLeftShape = 368,
    CornerTopRightShape = 369,
    Height = 370,
    Left = 371,
    MarginBottom = 372,
    MarginLeft = 373,
    MarginRight = 374,
    MarginTop = 375,
    MaxHeight = 376,
    MaxWidth = 377,
    MinHeight = 378,
    MinWidth = 379,
    OverflowX = 380,
    OverflowY = 381,
    OverscrollBehaviorX = 382,
    OverscrollBehaviorY = 383,
    PaddingBottom = 384,
    PaddingLeft = 385,
    PaddingRight = 386,
    PaddingTop = 387,
    Right = 388,
    ScrollMarginBottom = 389,
    ScrollMarginLeft = 390,
    ScrollMarginRight = 391,
    ScrollMarginTop = 392,
    ScrollPaddingBottom = 393,
    ScrollPaddingLeft = 394,
    ScrollPaddingRight = 395,
    ScrollPaddingTop = 396,
    Top = 397,
    Width = 398,
    BlockSize = 399,
    BorderBlockEndColor = 400,
    BorderBlockEndStyle = 401,
    BorderBlockEndWidth = 402,
    BorderBlockStartColor = 403,
    BorderBlockStartStyle = 404,
    BorderBlockStartWidth = 405,
    BorderEndEndRadius = 406,
    BorderEndStartRadius = 407,
    BorderInlineEndColor = 408,
    BorderInlineEndStyle = 409,
    BorderInlineEndWidth = 410,
    BorderInlineStartColor = 411,
    BorderInlineStartStyle = 412,
    BorderInlineStartWidth = 413,
    BorderStartEndRadius = 414,
    BorderStartStartRadius = 415,
    ContainIntrinsicBlockSize = 416,
    ContainIntrinsicInlineSize = 417,
    CornerEndEndShape = 418,
    CornerEndStartShape = 419,
    CornerStartEndShape = 420,
    CornerStartStartShape = 421,
    InlineSize = 422,
    InsetBlockEnd = 423,
    InsetBlockStart = 424,
    InsetInlineEnd = 425,
    InsetInlineStart = 426,
    MarginBlockEnd = 427,
    MarginBlockStart = 428,
    MarginInlineEnd = 429,
    MarginInlineStart = 430,
    MaxBlockSize = 431,
    MaxInlineSize = 432,
    MinBlockSize = 433,
    MinInlineSize = 434,
    OverflowBlock = 435,
    OverflowInline = 436,
    OverscrollBehaviorBlock = 437,
    OverscrollBehaviorInline = 438,
    PaddingBlockEnd = 439,
    PaddingBlockStart = 440,
    PaddingInlineEnd = 441,
    PaddingInlineStart = 442,
    ScrollMarginBlockEnd = 443,
    ScrollMarginBlockStart = 444,
    ScrollMarginInlineEnd = 445,
    ScrollMarginInlineStart = 446,
    ScrollPaddingBlockEnd = 447,
    ScrollPaddingBlockStart = 448,
    ScrollPaddingInlineEnd = 449,
    ScrollPaddingInlineStart = 450,
    All = 451,
    Animation = 452,
    AnimationRange = 453,
    Background = 454,
    BackgroundPosition = 455,
    BlockStep = 456,
    Border = 457,
    BorderBlock = 458,
    BorderBlockColor = 459,
    BorderBlockEnd = 460,
    BorderBlockStart = 461,
    BorderBlockStyle = 462,
    BorderBlockWidth = 463,
    BorderBottom = 464,
    BorderColor = 465,
    BorderImage = 466,
    BorderInline = 467,
    BorderInlineColor = 468,
    BorderInlineEnd = 469,
    BorderInlineStart = 470,
    BorderInlineStyle = 471,
    BorderInlineWidth = 472,
    BorderLeft = 473,
    BorderRadius = 474,
    BorderRight = 475,
    BorderSpacing = 476,
    BorderStyle = 477,
    BorderTop = 478,
    BorderWidth = 479,
    ColumnRule = 480,
    Columns = 481,
    ContainIntrinsicSize = 482,
    Container = 483,
    CornerShape = 484,
    Flex = 485,
    FlexFlow = 486,
    Font = 487,
    FontSynthesis = 488,
    FontVariant = 489,
    Gap = 490,
    Grid = 491,
    GridArea = 492,
    GridColumn = 493,
    GridRow = 494,
    GridTemplate = 495,
    Inset = 496,
    InsetBlock = 497,
    InsetInline = 498,
    LineClamp = 499,
    ListStyle = 500,
    Margin = 501,
    MarginBlock = 502,
    MarginInline = 503,
    Marker = 504,
    Mask = 505,
    MaskBorder = 506,
    MaskPosition = 507,
    Offset = 508,
    Outline = 509,
    Overflow = 510,
    OverscrollBehavior = 511,
    Padding = 512,
    PaddingBlock = 513,
    PaddingInline = 514,
    PageBreakAfter = 515,
    PageBreakBefore = 516,
    PageBreakInside = 517,
    PerspectiveOrigin = 518,
    PlaceContent = 519,
    PlaceItems = 520,
    PlaceSelf = 521,
    PositionTry = 522,
    ScrollMargin = 523,
    ScrollMarginBlock = 524,
    ScrollMarginInline = 525,
    ScrollPadding = 526,
    ScrollPaddingBlock = 527,
    ScrollPaddingInline = 528,
    ScrollTimeline = 529,
    TextBox = 530,
    TextDecoration = 531,
    TextDecorationSkip = 532,
    TextEmphasis = 533,
    TextWrap = 534,
    TransformOrigin = 535,
    Transition = 536,
    ViewTimeline = 537,
    WhiteSpace = 538,
    WebkitMaskPosition = 539,
  };

  /// @brief Enum value of the first "real" CSS property, which excludes
  /// CSSProperty::Invalid and CSSProperty::Custom.
  constexpr uint16 FirstCSSProperty = 2;

  /// @brief Total number of enum values in the CSSPropertyId enum. If making an array
  /// that can be indexed into using the enum value, use this as the size.
  constexpr uint16 CSSPropertyIdEnumValueCount = 540;

  /// @brief Number of "real" CSS properties. This differs from CSSPropertyIdEnumValueCount,
  /// as this doesn't consider CSSProperty::Invalid and CSSProperty::Custom.
  constexpr uint16 NumCSSProperties = 538;
  constexpr auto MaxCSSPropertyNameLength = 34uz;

  constexpr auto FirstTopPriorityProperty = CSSPropertyId::MathDepth;
  constexpr auto LastTopPriorityProperty = CSSPropertyId::WritingMode;
  constexpr auto FirstHighPriorityProperty = CSSPropertyId::Direction;
  constexpr auto LastHighPriorityProperty = CSSPropertyId::WordSpacing;
  constexpr auto FirstMediumPriorityProperty = CSSPropertyId::BackgroundImage;
  constexpr auto LastMediumPriorityProperty = CSSPropertyId::MaskImage;
  constexpr auto FirstLowPriorityProperty = CSSPropertyId::AccentColor;
  constexpr auto LastLowPriorityProperty = CSSPropertyId::WebkitUserSelect;
  constexpr auto FirstLogicalGroupPhysicalProperty = CSSPropertyId::BorderBottomColor;
  constexpr auto LastLogicalGroupPhysicalProperty = CSSPropertyId::Width;
  constexpr auto FirstLogicalGroupLogicalProperty = CSSPropertyId::BlockSize;
  constexpr auto LastLogicalGroupLogicalProperty = CSSPropertyId::ScrollPaddingInlineStart;
  constexpr auto FirstLogicalGroupProperty = FirstLogicalGroupPhysicalProperty;
  constexpr auto LastLogicalGroupProperty = LastLogicalGroupLogicalProperty;
  constexpr auto FirstShorthandProperty = CSSPropertyId::All;
  constexpr auto LastShorthandProperty = CSSPropertyId::WebkitMaskPosition;
  constexpr auto NumCSSPropertyLonghands = static_cast<uint16>(FirstShorthandProperty) - FirstCSSProperty;

  extern const Array<CSSPropertyId, 422uz> ComputedPropertyIds;

  template<CSSPropertyId C>
  struct PropertyNameConstant
  {
    constexpr static auto value = C;
    constexpr bool operator==(const PropertyNameConstant &) const noexcept = default;
    constexpr bool operator==(CSSPropertyId other) const noexcept { return value == other; }
  };

  struct CSSPropertySettings
  {
    bool accentColorEnabled : 1 {false};
    bool colorFilterEnabled : 1 {false};
    bool crossDocumentViewTransitionsEnabled : 1 {false};
    bool cssAnchorPositioningEnabled : 1 {false};
    bool cssCornerShapeEnabled : 1 {false};
    bool cssDPropertyEnabled : 1 {false};
    bool cssFieldSizingEnabled : 1 {false};
    bool cssFontVariantEmojiEnabled : 1 {false};
    bool cssFunctionAtRuleEnabled : 1 {false};
    bool cssInputSecurityEnabled : 1 {false};
    bool cssLineClampEnabled : 1 {false};
    bool cssLineFitEdgeEnabled : 1 {false};
    bool cssMathDepthEnabled : 1 {false};
    bool cssRhythmicSizingEnabled : 1 {false};
    bool cssRubyAlignEnabled : 1 {false};
    bool cssRubyOverhangEnabled : 1 {false};
    bool cssScrollAnchoringEnabled : 1 {false};
    bool cssScrollbarColorEnabled : 1 {false};
    bool cssScrollbarGutterEnabled : 1 {false};
    bool cssScrollbarWidthEnabled : 1 {false};
    bool cssTextAutospaceEnabled : 1 {false};
    bool cssTextBoxTrimEnabled : 1 {false};
    bool cssTextGroupAlignEnabled : 1 {false};
    bool cssTextJustifyEnabled : 1 {false};
    bool cssTextSpacingTrimEnabled : 1 {false};
    bool cssUnprefixedBackdropFilterEnabled : 1 {false};
    bool overscrollBehaviorEnabled : 1 {false};
    bool scrollDrivenAnimationsEnabled : 1 {false};
    bool supportHDRDisplayEnabled : 1 {false};
    bool viewTransitionsEnabled : 1 {false};

    CSSPropertySettings() noexcept = default;
  };

  KRYS_NODISCARD bool operator==(const CSSPropertySettings &, const CSSPropertySettings &) noexcept;

  KRYS_NODISCARD bool IsInternal(CSSPropertyId id) noexcept;

  KRYS_NODISCARD bool IsExposed(CSSPropertyId id, const CSSPropertySettings *) noexcept;

  KRYS_NODISCARD bool IsExposed(CSSPropertyId id, const CSSPropertySettings &) noexcept;

  KRYS_NODISCARD CSSPropertyId FindCSSProperty(CSSOMStringView characters) noexcept;

  KRYS_NODISCARD CSSOMStringView ToString(CSSPropertyId id) noexcept;

  KRYS_NODISCARD CSSPropertyId CascadeAliasProperty(CSSPropertyId id) noexcept;

  template<CSSPropertyId First, CSSPropertyId Last>
  struct CSSPropertiesRange
  {
      struct Iterator
      {
          uint16 Index { static_cast<uint16>(First) };

          constexpr CSSPropertyId operator*() const noexcept
          {
            return static_cast<CSSPropertyId>(Index);
          }

          constexpr Iterator &operator++() noexcept
          {
            ++Index;
            return *this;
          }

          constexpr bool operator==(std::nullptr_t) const noexcept
          {
            return Index > static_cast<uint16>(Last);
          }
      };

      KRYS_NODISCARD constexpr static Iterator begin() noexcept
      {
        return {};
      }

      KRYS_NODISCARD constexpr static std::nullptr_t end() noexcept
      {
        return nullptr;
      }

      KRYS_NODISCARD constexpr static uint16_t size() noexcept
      {
        return Last - First + 1;
      }
  };

  using AllCSSPropertiesRange = CSSPropertiesRange<static_cast<CSSPropertyId>(FirstCSSProperty), LastShorthandProperty>;
  KRYS_NODISCARD constexpr AllCSSPropertiesRange AllCSSProperties() noexcept
  {
    return {};
  }

  using AllLonghandCSSPropertiesRange = CSSPropertiesRange<static_cast<CSSPropertyId>(FirstCSSProperty), LastLogicalGroupProperty>;
  KRYS_NODISCARD constexpr AllLonghandCSSPropertiesRange AllLonghandCSSProperties() noexcept
  {
    return {};
  }

  KRYS_NODISCARD constexpr bool IsLonghand(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= FirstCSSProperty
          && static_cast<uint16>(property) < static_cast<uint16>(FirstShorthandProperty);
  }

  KRYS_NODISCARD constexpr bool IsShorthand(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= static_cast<uint16>(FirstShorthandProperty)
          && static_cast<uint16>(property) <= static_cast<uint16>(LastShorthandProperty);
  }

  KRYS_NODISCARD constexpr bool IsLogicalPropertyGroupProperty(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= static_cast<uint16>(FirstLogicalGroupPhysicalProperty)
          && static_cast<uint16>(property) <= static_cast<uint16>(LastLogicalGroupLogicalProperty);
  }

  KRYS_NODISCARD constexpr bool IsLogicalPropertyGroupPhysicalProperty(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= static_cast<uint16>(FirstLogicalGroupPhysicalProperty)
          && static_cast<uint16>(property) <= static_cast<uint16>(LastLogicalGroupPhysicalProperty);
  }

  KRYS_NODISCARD constexpr bool IsLogicalPropertyGroupLogicalProperty(CSSPropertyId property) noexcept
  {
      return static_cast<uint16>(property) >= static_cast<uint16>(FirstLogicalGroupLogicalProperty)
          && static_cast<uint16>(property) <= static_cast<uint16>(LastLogicalGroupLogicalProperty);
  }
}

namespace Krys
{
  template<>
  struct DefaultHash<::Krys::HTML::CSSPropertyId> : IntegerHash<uint16>
  {
  };
}

KRYS_DEFINE_CONTIGUOUS_ENUM_TRAITS(::Krys::HTML::CSSPropertyId, ::Krys::HTML::CSSPropertyIdEnumValueCount);

namespace std
{
  template<>
  struct iterator_traits<Krys::HTML::AllCSSPropertiesRange::Iterator>
  {
    using value_type = Krys::HTML::CSSPropertyId;
  };

  template<>
  struct iterator_traits<Krys::HTML::AllLonghandCSSPropertiesRange::Iterator>
  { 
    using value_type = Krys::HTML::CSSPropertyId;
  };
}
