// <auto-generated>
//   Generated at 2026-08-11 20:28:05 by css-properties.generator.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.Lib/Core/Enum.hpp"
#include "Krystal.Lib/String/String.hpp"

namespace Krys::HTML
{
  /// @brief An enumeration of all CSS properties, including both shorthand and longhand properties.
  enum class CSSPropertyId : uint16
  {
    /// @brief Represents an invalid or unrecognized CSS property.
    Invalid = 0,
    /// @syntax initial | inherit | unset | revert | revert-layer
    /// @specification css-cascade-5 (https://www.w3.org/TR/css-cascade-5/#all-shorthand)
    All,
    /// @syntax <'margin-top'>{1,4}
    /// @specification css-box-4 (https://www.w3.org/TR/css-box-4/#propdef-margin)
    Margin,
    /// @syntax <'padding-top'>{1,4}
    /// @specification css-box-4 (https://www.w3.org/TR/css-box-4/#propdef-padding)
    Padding,
    /// @syntax <length-percentage> | auto
    /// @specification css-box-4 (https://drafts.csswg.org/css-box-4/#margin-physical)
    MarginBottom,
    /// @syntax <length-percentage> | auto 
    /// @specification css-box-4 (https://drafts.csswg.org/css-box-4/#margin-physical)
    MarginLeft,
    /// @syntax <length-percentage> | auto
    /// @specification css-box-4 (https://drafts.csswg.org/css-box-4/#margin-physical)
    MarginRight,
    /// @syntax <length-percentage> | auto
    /// @specification css-box-4 (https://drafts.csswg.org/css-box-4/#margin-physical)
    MarginTop,
    /// @syntax <length-percentage [0,∞]>
    /// @specification css-box-4 (https://drafts.csswg.org/css-box-4/#padding-physical)
    PaddingBottom,
    /// @syntax <length-percentage [0,∞]>
    /// @specification css-box-4 (https://drafts.csswg.org/css-box-4/#padding-physical)
    PaddingLeft,
    /// @syntax <length-percentage [0,∞]>
    /// @specification css-box-4 (https://drafts.csswg.org/css-box-4/#padding-physical)
    PaddingRight,
    /// @syntax <length-percentage [0,∞]>
    /// @specification css-box-4 (https://drafts.csswg.org/css-box-4/#padding-physical)
    PaddingTop,
  };

  KRYS_NODISCARD constexpr CSSPropertyId ParseCSSPropertyId(utf8_stringview str) noexcept
  {
    if (str == u8"all")
    {
      return CSSPropertyId::All;
    }
    if (str == u8"margin")
    {
      return CSSPropertyId::Margin;
    }
    if (str == u8"padding")
    {
      return CSSPropertyId::Padding;
    }
    if (str == u8"margin-bottom")
    {
      return CSSPropertyId::MarginBottom;
    }
    if (str == u8"margin-left")
    {
      return CSSPropertyId::MarginLeft;
    }
    if (str == u8"margin-right")
    {
      return CSSPropertyId::MarginRight;
    }
    if (str == u8"margin-top")
    {
      return CSSPropertyId::MarginTop;
    }
    if (str == u8"padding-bottom")
    {
      return CSSPropertyId::PaddingBottom;
    }
    if (str == u8"padding-left")
    {
      return CSSPropertyId::PaddingLeft;
    }
    if (str == u8"padding-right")
    {
      return CSSPropertyId::PaddingRight;
    }
    if (str == u8"padding-top")
    {
      return CSSPropertyId::PaddingTop;
    }
    
    return CSSPropertyId::Invalid;
  }

  KRYS_NODISCARD constexpr utf8_stringview ToString(CSSPropertyId value) noexcept
  {
    switch (value)
    {
      case CSSPropertyId::All:
      {
        return u8"all";
      }
      case CSSPropertyId::Margin:
      {
        return u8"margin";
      }
      case CSSPropertyId::Padding:
      {
        return u8"padding";
      }
      case CSSPropertyId::MarginBottom:
      {
        return u8"margin-bottom";
      }
      case CSSPropertyId::MarginLeft:
      {
        return u8"margin-left";
      }
      case CSSPropertyId::MarginRight:
      {
        return u8"margin-right";
      }
      case CSSPropertyId::MarginTop:
      {
        return u8"margin-top";
      }
      case CSSPropertyId::PaddingBottom:
      {
        return u8"padding-bottom";
      }
      case CSSPropertyId::PaddingLeft:
      {
        return u8"padding-left";
      }
      case CSSPropertyId::PaddingRight:
      {
        return u8"padding-right";
      }
      case CSSPropertyId::PaddingTop:
      {
        return u8"padding-top";
      }
      default:
      {
        return u8"Invalid";
      }
    }
  }
  constexpr size_t FirstShorthandCSSPropertyId = 1uz;
  constexpr size_t LastShorthandCSSPropertyId = 3uz;
  constexpr size_t FirstLonghandCSSPropertyId = 4uz;
  constexpr size_t LastLonghandCSSPropertyId = 10uz;
}

KRYS_DEFINE_CONTIGUOUS_ENUM_TRAITS(Krys::HTML::CSSPropertyId, 12uz);