// <auto-generated>
//   Generated at 2026-09-13 16:15:35 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#include "Krystal.Booey/CSS/Properties/PropertyShorthandFunctions.hpp"
#include "Krystal.Booey/CSS/Properties/PropertyShorthand.hpp"
#include <array>

namespace krys::boo
{
  PropertyShorthand AllShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::MathDepth,
      PropertyId::RubyPosition,
      PropertyId::WritingMode,
      PropertyId::Display,
      PropertyId::FontFamily,
      PropertyId::FontFeatureSettings,
      PropertyId::FontKerning,
      PropertyId::FontPalette,
      PropertyId::FontSize,
      PropertyId::FontSizeAdjust,
      PropertyId::FontStyle,
      PropertyId::FontSynthesisSmallCaps,
      PropertyId::FontSynthesisStyle,
      PropertyId::FontSynthesisWeight,
      PropertyId::FontVariantAlternates,
      PropertyId::FontVariantCaps,
      PropertyId::FontVariantEastAsian,
      PropertyId::FontVariantEmoji,
      PropertyId::FontVariantLigatures,
      PropertyId::FontVariantNumeric,
      PropertyId::FontVariantPosition,
      PropertyId::FontWeight,
      PropertyId::FontWidth,
      PropertyId::TextOrientation,
      PropertyId::TextRendering,
      PropertyId::Zoom,
      PropertyId::WebkitFontSmoothing,
      PropertyId::WebkitLocale,
      PropertyId::LetterSpacing,
      PropertyId::TextAutospace,
      PropertyId::TextSpacingTrim,
      PropertyId::WordSpacing,
      PropertyId::BackgroundImage,
      PropertyId::MaskImage,
      PropertyId::AccentColor,
      PropertyId::AlignContent,
      PropertyId::AlignItems,
      PropertyId::AlignSelf,
      PropertyId::AlignmentBaseline,
      PropertyId::AnchorName,
      PropertyId::AnchorScope,
      PropertyId::AnimationComposition,
      PropertyId::AnimationDelay,
      PropertyId::AnimationDirection,
      PropertyId::AnimationDuration,
      PropertyId::AnimationFillMode,
      PropertyId::AnimationIterationCount,
      PropertyId::AnimationName,
      PropertyId::AnimationPlayState,
      PropertyId::AnimationRangeEnd,
      PropertyId::AnimationRangeStart,
      PropertyId::AnimationTimeline,
      PropertyId::AnimationTimingFunction,
      PropertyId::Appearance,
      PropertyId::AspectRatio,
      PropertyId::BackdropFilter,
      PropertyId::BackfaceVisibility,
      PropertyId::BackgroundAttachment,
      PropertyId::BackgroundBlendMode,
      PropertyId::BackgroundClip,
      PropertyId::BackgroundColor,
      PropertyId::BackgroundOrigin,
      PropertyId::BackgroundPositionX,
      PropertyId::BackgroundPositionY,
      PropertyId::BackgroundRepeat,
      PropertyId::BackgroundSize,
      PropertyId::BaselineShift,
      PropertyId::BlockEllipsis,
      PropertyId::BlockStepAlign,
      PropertyId::BlockStepInsert,
      PropertyId::BlockStepRound,
      PropertyId::BlockStepSize,
      PropertyId::BorderCollapse,
      PropertyId::BorderImageOutset,
      PropertyId::BorderImageRepeat,
      PropertyId::BorderImageSlice,
      PropertyId::BorderImageSource,
      PropertyId::BorderImageWidth,
      PropertyId::BoxShadow,
      PropertyId::BoxSizing,
      PropertyId::BreakAfter,
      PropertyId::BreakBefore,
      PropertyId::BreakInside,
      PropertyId::BufferedRendering,
      PropertyId::CaptionSide,
      PropertyId::CaretColor,
      PropertyId::Clear,
      PropertyId::Clip,
      PropertyId::ClipPath,
      PropertyId::ClipRule,
      PropertyId::Color,
      PropertyId::ColorInterpolation,
      PropertyId::ColorInterpolationFilters,
      PropertyId::ColumnCount,
      PropertyId::ColumnFill,
      PropertyId::ColumnGap,
      PropertyId::ColumnRuleColor,
      PropertyId::ColumnRuleStyle,
      PropertyId::ColumnRuleWidth,
      PropertyId::ColumnSpan,
      PropertyId::ColumnWidth,
      PropertyId::Contain,
      PropertyId::ContainerName,
      PropertyId::ContainerType,
      PropertyId::Content,
      PropertyId::ContentVisibility,
      PropertyId::Continue,
      PropertyId::CounterIncrement,
      PropertyId::CounterReset,
      PropertyId::CounterSet,
      PropertyId::Cursor,
      PropertyId::Cx,
      PropertyId::Cy,
      PropertyId::D,
      PropertyId::DominantBaseline,
      PropertyId::DynamicRangeLimit,
      PropertyId::EmptyCells,
      PropertyId::FieldSizing,
      PropertyId::Fill,
      PropertyId::FillOpacity,
      PropertyId::FillRule,
      PropertyId::Filter,
      PropertyId::FlexBasis,
      PropertyId::FlexDirection,
      PropertyId::FlexGrow,
      PropertyId::FlexShrink,
      PropertyId::FlexWrap,
      PropertyId::Float,
      PropertyId::FloodColor,
      PropertyId::FloodOpacity,
      PropertyId::GlyphOrientationHorizontal,
      PropertyId::GlyphOrientationVertical,
      PropertyId::GridAutoColumns,
      PropertyId::GridAutoFlow,
      PropertyId::GridAutoRows,
      PropertyId::GridColumnEnd,
      PropertyId::GridColumnStart,
      PropertyId::GridRowEnd,
      PropertyId::GridRowStart,
      PropertyId::GridTemplateAreas,
      PropertyId::GridTemplateColumns,
      PropertyId::GridTemplateRows,
      PropertyId::HangingPunctuation,
      PropertyId::HyphenateCharacter,
      PropertyId::Hyphens,
      PropertyId::ImageOrientation,
      PropertyId::ImageRendering,
      PropertyId::InputSecurity,
      PropertyId::Isolation,
      PropertyId::ItemTolerance,
      PropertyId::JustifyContent,
      PropertyId::JustifyItems,
      PropertyId::JustifySelf,
      PropertyId::LightingColor,
      PropertyId::LineBreak,
      PropertyId::LineFitEdge,
      PropertyId::LineHeight,
      PropertyId::ListStyleImage,
      PropertyId::ListStylePosition,
      PropertyId::ListStyleType,
      PropertyId::MarginTrim,
      PropertyId::MarkerEnd,
      PropertyId::MarkerMid,
      PropertyId::MarkerStart,
      PropertyId::MaskBorderOutset,
      PropertyId::MaskBorderRepeat,
      PropertyId::MaskBorderSlice,
      PropertyId::MaskBorderSource,
      PropertyId::MaskBorderWidth,
      PropertyId::MaskClip,
      PropertyId::MaskComposite,
      PropertyId::MaskMode,
      PropertyId::MaskOrigin,
      PropertyId::MaskRepeat,
      PropertyId::MaskSize,
      PropertyId::MaskType,
      PropertyId::MathShift,
      PropertyId::MathStyle,
      PropertyId::MaxLines,
      PropertyId::MixBlendMode,
      PropertyId::ObjectFit,
      PropertyId::ObjectPosition,
      PropertyId::OffsetAnchor,
      PropertyId::OffsetDistance,
      PropertyId::OffsetPath,
      PropertyId::OffsetPosition,
      PropertyId::OffsetRotate,
      PropertyId::Opacity,
      PropertyId::Order,
      PropertyId::Orphans,
      PropertyId::OutlineColor,
      PropertyId::OutlineOffset,
      PropertyId::OutlineStyle,
      PropertyId::OutlineWidth,
      PropertyId::OverflowAnchor,
      PropertyId::OverflowWrap,
      PropertyId::Page,
      PropertyId::PaintOrder,
      PropertyId::Perspective,
      PropertyId::PerspectiveOriginX,
      PropertyId::PerspectiveOriginY,
      PropertyId::PointerEvents,
      PropertyId::Position,
      PropertyId::PositionAnchor,
      PropertyId::PositionArea,
      PropertyId::PositionTryFallbacks,
      PropertyId::PositionTryOrder,
      PropertyId::PositionVisibility,
      PropertyId::PrintColorAdjust,
      PropertyId::Quotes,
      PropertyId::R,
      PropertyId::Resize,
      PropertyId::Rotate,
      PropertyId::RowGap,
      PropertyId::RubyAlign,
      PropertyId::RubyOverhang,
      PropertyId::Rx,
      PropertyId::Ry,
      PropertyId::Scale,
      PropertyId::ScrollBehavior,
      PropertyId::ScrollSnapAlign,
      PropertyId::ScrollSnapStop,
      PropertyId::ScrollSnapType,
      PropertyId::ScrollTimelineAxis,
      PropertyId::ScrollTimelineName,
      PropertyId::ScrollbarColor,
      PropertyId::ScrollbarGutter,
      PropertyId::ScrollbarWidth,
      PropertyId::ShapeImageThreshold,
      PropertyId::ShapeMargin,
      PropertyId::ShapeOutside,
      PropertyId::ShapeRendering,
      PropertyId::SpeakAs,
      PropertyId::StopColor,
      PropertyId::StopOpacity,
      PropertyId::Stroke,
      PropertyId::StrokeColor,
      PropertyId::StrokeDasharray,
      PropertyId::StrokeDashoffset,
      PropertyId::StrokeLinecap,
      PropertyId::StrokeLinejoin,
      PropertyId::StrokeMiterlimit,
      PropertyId::StrokeOpacity,
      PropertyId::StrokeWidth,
      PropertyId::TabSize,
      PropertyId::TableLayout,
      PropertyId::TextAlign,
      PropertyId::TextAlignLast,
      PropertyId::TextAnchor,
      PropertyId::TextBoxEdge,
      PropertyId::TextBoxTrim,
      PropertyId::TextCombineUpright,
      PropertyId::TextDecorationColor,
      PropertyId::TextDecorationLine,
      PropertyId::TextDecorationSkipInk,
      PropertyId::TextDecorationStyle,
      PropertyId::TextDecorationThickness,
      PropertyId::TextEmphasisColor,
      PropertyId::TextEmphasisPosition,
      PropertyId::TextEmphasisStyle,
      PropertyId::TextGroupAlign,
      PropertyId::TextIndent,
      PropertyId::TextJustify,
      PropertyId::TextOverflow,
      PropertyId::TextShadow,
      PropertyId::TextTransform,
      PropertyId::TextUnderlineOffset,
      PropertyId::TextUnderlinePosition,
      PropertyId::TextWrapMode,
      PropertyId::TextWrapStyle,
      PropertyId::TimelineScope,
      PropertyId::TouchAction,
      PropertyId::Transform,
      PropertyId::TransformBox,
      PropertyId::TransformOriginX,
      PropertyId::TransformOriginY,
      PropertyId::TransformOriginZ,
      PropertyId::TransformStyle,
      PropertyId::TransitionBehavior,
      PropertyId::TransitionDelay,
      PropertyId::TransitionDuration,
      PropertyId::TransitionProperty,
      PropertyId::TransitionTimingFunction,
      PropertyId::Translate,
      PropertyId::VectorEffect,
      PropertyId::VerticalAlign,
      PropertyId::ViewTimelineAxis,
      PropertyId::ViewTimelineInset,
      PropertyId::ViewTimelineName,
      PropertyId::ViewTransitionClass,
      PropertyId::ViewTransitionName,
      PropertyId::Visibility,
      PropertyId::WhiteSpaceCollapse,
      PropertyId::Widows,
      PropertyId::WillChange,
      PropertyId::WordBreak,
      PropertyId::X,
      PropertyId::Y,
      PropertyId::ZIndex,
      PropertyId::AppleColorFilter,
      PropertyId::WebkitBorderHorizontalSpacing,
      PropertyId::WebkitBorderVerticalSpacing,
      PropertyId::WebkitBoxDecorationBreak,
      PropertyId::WebkitColumnProgression,
      PropertyId::WebkitHyphenateLimitAfter,
      PropertyId::WebkitHyphenateLimitBefore,
      PropertyId::WebkitHyphenateLimitLines,
      PropertyId::WebkitInitialLetter,
      PropertyId::WebkitLineAlign,
      PropertyId::WebkitLineBoxContain,
      PropertyId::WebkitMaskPositionX,
      PropertyId::WebkitMaskPositionY,
      PropertyId::WebkitRtlOrdering,
      PropertyId::WebkitRubyPosition,
      PropertyId::WebkitTextCombine,
      PropertyId::WebkitTextDecorationsInEffect,
      PropertyId::WebkitTextFillColor,
      PropertyId::WebkitTextSecurity,
      PropertyId::WebkitUserDrag,
      PropertyId::WebkitUserModify,
      PropertyId::WebkitUserSelect,
      PropertyId::BorderBottomColor,
      PropertyId::BorderBottomLeftRadius,
      PropertyId::BorderBottomRightRadius,
      PropertyId::BorderBottomStyle,
      PropertyId::BorderBottomWidth,
      PropertyId::BorderLeftColor,
      PropertyId::BorderLeftStyle,
      PropertyId::BorderLeftWidth,
      PropertyId::BorderRightColor,
      PropertyId::BorderRightStyle,
      PropertyId::BorderRightWidth,
      PropertyId::BorderTopColor,
      PropertyId::BorderTopLeftRadius,
      PropertyId::BorderTopRightRadius,
      PropertyId::BorderTopStyle,
      PropertyId::BorderTopWidth,
      PropertyId::Bottom,
      PropertyId::ContainIntrinsicHeight,
      PropertyId::ContainIntrinsicWidth,
      PropertyId::CornerBottomLeftShape,
      PropertyId::CornerBottomRightShape,
      PropertyId::CornerTopLeftShape,
      PropertyId::CornerTopRightShape,
      PropertyId::Height,
      PropertyId::Left,
      PropertyId::MarginBottom,
      PropertyId::MarginLeft,
      PropertyId::MarginRight,
      PropertyId::MarginTop,
      PropertyId::MaxHeight,
      PropertyId::MaxWidth,
      PropertyId::MinHeight,
      PropertyId::MinWidth,
      PropertyId::OverflowX,
      PropertyId::OverflowY,
      PropertyId::OverscrollBehaviorX,
      PropertyId::OverscrollBehaviorY,
      PropertyId::PaddingBottom,
      PropertyId::PaddingLeft,
      PropertyId::PaddingRight,
      PropertyId::PaddingTop,
      PropertyId::Right,
      PropertyId::ScrollMarginBottom,
      PropertyId::ScrollMarginLeft,
      PropertyId::ScrollMarginRight,
      PropertyId::ScrollMarginTop,
      PropertyId::ScrollPaddingBottom,
      PropertyId::ScrollPaddingLeft,
      PropertyId::ScrollPaddingRight,
      PropertyId::ScrollPaddingTop,
      PropertyId::Top,
      PropertyId::Width,
      PropertyId::BlockSize,
      PropertyId::BorderBlockEndColor,
      PropertyId::BorderBlockEndStyle,
      PropertyId::BorderBlockEndWidth,
      PropertyId::BorderBlockStartColor,
      PropertyId::BorderBlockStartStyle,
      PropertyId::BorderBlockStartWidth,
      PropertyId::BorderEndEndRadius,
      PropertyId::BorderEndStartRadius,
      PropertyId::BorderInlineEndColor,
      PropertyId::BorderInlineEndStyle,
      PropertyId::BorderInlineEndWidth,
      PropertyId::BorderInlineStartColor,
      PropertyId::BorderInlineStartStyle,
      PropertyId::BorderInlineStartWidth,
      PropertyId::BorderStartEndRadius,
      PropertyId::BorderStartStartRadius,
      PropertyId::ContainIntrinsicBlockSize,
      PropertyId::ContainIntrinsicInlineSize,
      PropertyId::CornerEndEndShape,
      PropertyId::CornerEndStartShape,
      PropertyId::CornerStartEndShape,
      PropertyId::CornerStartStartShape,
      PropertyId::InlineSize,
      PropertyId::InsetBlockEnd,
      PropertyId::InsetBlockStart,
      PropertyId::InsetInlineEnd,
      PropertyId::InsetInlineStart,
      PropertyId::MarginBlockEnd,
      PropertyId::MarginBlockStart,
      PropertyId::MarginInlineEnd,
      PropertyId::MarginInlineStart,
      PropertyId::MaxBlockSize,
      PropertyId::MaxInlineSize,
      PropertyId::MinBlockSize,
      PropertyId::MinInlineSize,
      PropertyId::OverflowBlock,
      PropertyId::OverflowInline,
      PropertyId::OverscrollBehaviorBlock,
      PropertyId::OverscrollBehaviorInline,
      PropertyId::PaddingBlockEnd,
      PropertyId::PaddingBlockStart,
      PropertyId::PaddingInlineEnd,
      PropertyId::PaddingInlineStart,
      PropertyId::ScrollMarginBlockEnd,
      PropertyId::ScrollMarginBlockStart,
      PropertyId::ScrollMarginInlineEnd,
      PropertyId::ScrollMarginInlineStart,
      PropertyId::ScrollPaddingBlockEnd,
      PropertyId::ScrollPaddingBlockStart,
      PropertyId::ScrollPaddingInlineEnd,
      PropertyId::ScrollPaddingInlineStart,
    };

    return PropertyShorthand {PropertyId::All, properties};
  }

  PropertyShorthand AnimationShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::AnimationDuration,
      PropertyId::AnimationTimingFunction,
      PropertyId::AnimationDelay,
      PropertyId::AnimationIterationCount,
      PropertyId::AnimationDirection,
      PropertyId::AnimationFillMode,
      PropertyId::AnimationPlayState,
      PropertyId::AnimationName,
      PropertyId::AnimationTimeline,
      PropertyId::AnimationRangeStart,
      PropertyId::AnimationRangeEnd,
    };

    return PropertyShorthand {PropertyId::Animation, properties};
  }

  PropertyShorthand AnimationRangeShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::AnimationRangeStart,
      PropertyId::AnimationRangeEnd,
    };

    return PropertyShorthand {PropertyId::AnimationRange, properties};
  }

  PropertyShorthand BackgroundShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BackgroundImage,
      PropertyId::BackgroundPositionX,
      PropertyId::BackgroundPositionY,
      PropertyId::BackgroundSize,
      PropertyId::BackgroundRepeat,
      PropertyId::BackgroundAttachment,
      PropertyId::BackgroundOrigin,
      PropertyId::BackgroundClip,
      PropertyId::BackgroundColor,
    };

    return PropertyShorthand {PropertyId::Background, properties};
  }

  PropertyShorthand BackgroundPositionShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BackgroundPositionX,
      PropertyId::BackgroundPositionY,
    };

    return PropertyShorthand {PropertyId::BackgroundPosition, properties};
  }

  PropertyShorthand BlockStepShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BlockStepSize,
      PropertyId::BlockStepInsert,
      PropertyId::BlockStepAlign,
      PropertyId::BlockStepRound,
    };

    return PropertyShorthand {PropertyId::BlockStep, properties};
  }

  PropertyShorthand BorderShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderTopWidth,
      PropertyId::BorderRightWidth,
      PropertyId::BorderBottomWidth,
      PropertyId::BorderLeftWidth,
      PropertyId::BorderTopStyle,
      PropertyId::BorderRightStyle,
      PropertyId::BorderBottomStyle,
      PropertyId::BorderLeftStyle,
      PropertyId::BorderTopColor,
      PropertyId::BorderRightColor,
      PropertyId::BorderBottomColor,
      PropertyId::BorderLeftColor,
      PropertyId::BorderImageSource,
      PropertyId::BorderImageSlice,
      PropertyId::BorderImageWidth,
      PropertyId::BorderImageOutset,
      PropertyId::BorderImageRepeat,
    };

    return PropertyShorthand {PropertyId::Border, properties};
  }

  PropertyShorthand BorderBlockShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderBlockStartWidth,
      PropertyId::BorderBlockEndWidth,
      PropertyId::BorderBlockStartStyle,
      PropertyId::BorderBlockEndStyle,
      PropertyId::BorderBlockStartColor,
      PropertyId::BorderBlockEndColor,
    };

    return PropertyShorthand {PropertyId::BorderBlock, properties};
  }

  PropertyShorthand BorderBlockColorShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderBlockStartColor,
      PropertyId::BorderBlockEndColor,
    };

    return PropertyShorthand {PropertyId::BorderBlockColor, properties};
  }

  PropertyShorthand BorderBlockEndShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderBlockEndWidth,
      PropertyId::BorderBlockEndStyle,
      PropertyId::BorderBlockEndColor,
    };

    return PropertyShorthand {PropertyId::BorderBlockEnd, properties};
  }

  PropertyShorthand BorderBlockStartShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderBlockStartWidth,
      PropertyId::BorderBlockStartStyle,
      PropertyId::BorderBlockStartColor,
    };

    return PropertyShorthand {PropertyId::BorderBlockStart, properties};
  }

  PropertyShorthand BorderBlockStyleShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderBlockStartStyle,
      PropertyId::BorderBlockEndStyle,
    };

    return PropertyShorthand {PropertyId::BorderBlockStyle, properties};
  }

  PropertyShorthand BorderBlockWidthShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderBlockStartWidth,
      PropertyId::BorderBlockEndWidth,
    };

    return PropertyShorthand {PropertyId::BorderBlockWidth, properties};
  }

  PropertyShorthand BorderBottomShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderBottomWidth,
      PropertyId::BorderBottomStyle,
      PropertyId::BorderBottomColor,
    };

    return PropertyShorthand {PropertyId::BorderBottom, properties};
  }

  PropertyShorthand BorderColorShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderTopColor,
      PropertyId::BorderRightColor,
      PropertyId::BorderBottomColor,
      PropertyId::BorderLeftColor,
    };

    return PropertyShorthand {PropertyId::BorderColor, properties};
  }

  PropertyShorthand BorderImageShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderImageSource,
      PropertyId::BorderImageSlice,
      PropertyId::BorderImageWidth,
      PropertyId::BorderImageOutset,
      PropertyId::BorderImageRepeat,
    };

    return PropertyShorthand {PropertyId::BorderImage, properties};
  }

  PropertyShorthand BorderInlineShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderInlineStartWidth,
      PropertyId::BorderInlineEndWidth,
      PropertyId::BorderInlineStartStyle,
      PropertyId::BorderInlineEndStyle,
      PropertyId::BorderInlineStartColor,
      PropertyId::BorderInlineEndColor,
    };

    return PropertyShorthand {PropertyId::BorderInline, properties};
  }

  PropertyShorthand BorderInlineColorShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderInlineStartColor,
      PropertyId::BorderInlineEndColor,
    };

    return PropertyShorthand {PropertyId::BorderInlineColor, properties};
  }

  PropertyShorthand BorderInlineEndShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderInlineEndWidth,
      PropertyId::BorderInlineEndStyle,
      PropertyId::BorderInlineEndColor,
    };

    return PropertyShorthand {PropertyId::BorderInlineEnd, properties};
  }

  PropertyShorthand BorderInlineStartShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderInlineStartWidth,
      PropertyId::BorderInlineStartStyle,
      PropertyId::BorderInlineStartColor,
    };

    return PropertyShorthand {PropertyId::BorderInlineStart, properties};
  }

  PropertyShorthand BorderInlineStyleShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderInlineStartStyle,
      PropertyId::BorderInlineEndStyle,
    };

    return PropertyShorthand {PropertyId::BorderInlineStyle, properties};
  }

  PropertyShorthand BorderInlineWidthShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderInlineStartWidth,
      PropertyId::BorderInlineEndWidth,
    };

    return PropertyShorthand {PropertyId::BorderInlineWidth, properties};
  }

  PropertyShorthand BorderLeftShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderLeftWidth,
      PropertyId::BorderLeftStyle,
      PropertyId::BorderLeftColor,
    };

    return PropertyShorthand {PropertyId::BorderLeft, properties};
  }

  PropertyShorthand BorderRadiusShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderTopLeftRadius,
      PropertyId::BorderTopRightRadius,
      PropertyId::BorderBottomRightRadius,
      PropertyId::BorderBottomLeftRadius,
    };

    return PropertyShorthand {PropertyId::BorderRadius, properties};
  }

  PropertyShorthand BorderRightShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderRightWidth,
      PropertyId::BorderRightStyle,
      PropertyId::BorderRightColor,
    };

    return PropertyShorthand {PropertyId::BorderRight, properties};
  }

  PropertyShorthand BorderSpacingShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::WebkitBorderHorizontalSpacing,
      PropertyId::WebkitBorderVerticalSpacing,
    };

    return PropertyShorthand {PropertyId::BorderSpacing, properties};
  }

  PropertyShorthand BorderStyleShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderTopStyle,
      PropertyId::BorderRightStyle,
      PropertyId::BorderBottomStyle,
      PropertyId::BorderLeftStyle,
    };

    return PropertyShorthand {PropertyId::BorderStyle, properties};
  }

  PropertyShorthand BorderTopShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderTopWidth,
      PropertyId::BorderTopStyle,
      PropertyId::BorderTopColor,
    };

    return PropertyShorthand {PropertyId::BorderTop, properties};
  }

  PropertyShorthand BorderWidthShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BorderTopWidth,
      PropertyId::BorderRightWidth,
      PropertyId::BorderBottomWidth,
      PropertyId::BorderLeftWidth,
    };

    return PropertyShorthand {PropertyId::BorderWidth, properties};
  }

  PropertyShorthand ColumnRuleShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ColumnRuleWidth,
      PropertyId::ColumnRuleStyle,
      PropertyId::ColumnRuleColor,
    };

    return PropertyShorthand {PropertyId::ColumnRule, properties};
  }

  PropertyShorthand ColumnsShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ColumnWidth,
      PropertyId::ColumnCount,
    };

    return PropertyShorthand {PropertyId::Columns, properties};
  }

  PropertyShorthand ContainIntrinsicSizeShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ContainIntrinsicWidth,
      PropertyId::ContainIntrinsicHeight,
    };

    return PropertyShorthand {PropertyId::ContainIntrinsicSize, properties};
  }

  PropertyShorthand ContainerShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ContainerName,
      PropertyId::ContainerType,
    };

    return PropertyShorthand {PropertyId::Container, properties};
  }

  PropertyShorthand CornerShapeShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::CornerTopLeftShape,
      PropertyId::CornerTopRightShape,
      PropertyId::CornerBottomRightShape,
      PropertyId::CornerBottomLeftShape,
    };

    return PropertyShorthand {PropertyId::CornerShape, properties};
  }

  PropertyShorthand FlexShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::FlexGrow,
      PropertyId::FlexShrink,
      PropertyId::FlexBasis,
    };

    return PropertyShorthand {PropertyId::Flex, properties};
  }

  PropertyShorthand FlexFlowShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::FlexDirection,
      PropertyId::FlexWrap,
    };

    return PropertyShorthand {PropertyId::FlexFlow, properties};
  }

  PropertyShorthand FontShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::FontStyle,
      PropertyId::FontVariantCaps,
      PropertyId::FontWeight,
      PropertyId::FontWidth,
      PropertyId::FontSize,
      PropertyId::LineHeight,
      PropertyId::FontFamily,
      PropertyId::FontSizeAdjust,
      PropertyId::FontKerning,
      PropertyId::FontVariantAlternates,
      PropertyId::FontVariantLigatures,
      PropertyId::FontVariantNumeric,
      PropertyId::FontVariantEastAsian,
      PropertyId::FontVariantPosition,
      PropertyId::FontVariantEmoji,
      PropertyId::FontFeatureSettings,
    };

    return PropertyShorthand {PropertyId::Font, properties};
  }

  PropertyShorthand FontSynthesisShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::FontSynthesisWeight,
      PropertyId::FontSynthesisStyle,
      PropertyId::FontSynthesisSmallCaps,
    };

    return PropertyShorthand {PropertyId::FontSynthesis, properties};
  }

  PropertyShorthand FontVariantShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::FontVariantLigatures,
      PropertyId::FontVariantCaps,
      PropertyId::FontVariantAlternates,
      PropertyId::FontVariantNumeric,
      PropertyId::FontVariantEastAsian,
      PropertyId::FontVariantPosition,
      PropertyId::FontVariantEmoji,
    };

    return PropertyShorthand {PropertyId::FontVariant, properties};
  }

  PropertyShorthand GapShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::RowGap,
      PropertyId::ColumnGap,
    };

    return PropertyShorthand {PropertyId::Gap, properties};
  }

  PropertyShorthand GridShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::GridTemplateRows,
      PropertyId::GridTemplateColumns,
      PropertyId::GridTemplateAreas,
      PropertyId::GridAutoFlow,
      PropertyId::GridAutoRows,
      PropertyId::GridAutoColumns,
    };

    return PropertyShorthand {PropertyId::Grid, properties};
  }

  PropertyShorthand GridAreaShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::GridRowStart,
      PropertyId::GridColumnStart,
      PropertyId::GridRowEnd,
      PropertyId::GridColumnEnd,
    };

    return PropertyShorthand {PropertyId::GridArea, properties};
  }

  PropertyShorthand GridColumnShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::GridColumnStart,
      PropertyId::GridColumnEnd,
    };

    return PropertyShorthand {PropertyId::GridColumn, properties};
  }

  PropertyShorthand GridRowShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::GridRowStart,
      PropertyId::GridRowEnd,
    };

    return PropertyShorthand {PropertyId::GridRow, properties};
  }

  PropertyShorthand GridTemplateShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::GridTemplateRows,
      PropertyId::GridTemplateColumns,
      PropertyId::GridTemplateAreas,
    };

    return PropertyShorthand {PropertyId::GridTemplate, properties};
  }

  PropertyShorthand InsetShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::Top,
      PropertyId::Right,
      PropertyId::Bottom,
      PropertyId::Left,
    };

    return PropertyShorthand {PropertyId::Inset, properties};
  }

  PropertyShorthand InsetBlockShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::InsetBlockStart,
      PropertyId::InsetBlockEnd,
    };

    return PropertyShorthand {PropertyId::InsetBlock, properties};
  }

  PropertyShorthand InsetInlineShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::InsetInlineStart,
      PropertyId::InsetInlineEnd,
    };

    return PropertyShorthand {PropertyId::InsetInline, properties};
  }

  PropertyShorthand LineClampShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::MaxLines,
      PropertyId::BlockEllipsis,
      PropertyId::Continue,
    };

    return PropertyShorthand {PropertyId::LineClamp, properties};
  }

  PropertyShorthand ListStyleShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ListStylePosition,
      PropertyId::ListStyleImage,
      PropertyId::ListStyleType,
    };

    return PropertyShorthand {PropertyId::ListStyle, properties};
  }

  PropertyShorthand MarginShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::MarginTop,
      PropertyId::MarginRight,
      PropertyId::MarginBottom,
      PropertyId::MarginLeft,
    };

    return PropertyShorthand {PropertyId::Margin, properties};
  }

  PropertyShorthand MarginBlockShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::MarginBlockStart,
      PropertyId::MarginBlockEnd,
    };

    return PropertyShorthand {PropertyId::MarginBlock, properties};
  }

  PropertyShorthand MarginInlineShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::MarginInlineStart,
      PropertyId::MarginInlineEnd,
    };

    return PropertyShorthand {PropertyId::MarginInline, properties};
  }

  PropertyShorthand MarkerShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::MarkerStart,
      PropertyId::MarkerMid,
      PropertyId::MarkerEnd,
    };

    return PropertyShorthand {PropertyId::Marker, properties};
  }

  PropertyShorthand MaskShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::MaskImage,
      PropertyId::WebkitMaskPositionX,
      PropertyId::WebkitMaskPositionY,
      PropertyId::MaskSize,
      PropertyId::MaskRepeat,
      PropertyId::MaskOrigin,
      PropertyId::MaskClip,
      PropertyId::MaskComposite,
      PropertyId::MaskMode,
      PropertyId::MaskBorderSource,
      PropertyId::MaskBorderSlice,
      PropertyId::MaskBorderWidth,
      PropertyId::MaskBorderOutset,
      PropertyId::MaskBorderRepeat,
    };

    return PropertyShorthand {PropertyId::Mask, properties};
  }

  PropertyShorthand MaskBorderShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::MaskBorderSource,
      PropertyId::MaskBorderSlice,
      PropertyId::MaskBorderWidth,
      PropertyId::MaskBorderOutset,
      PropertyId::MaskBorderRepeat,
    };

    return PropertyShorthand {PropertyId::MaskBorder, properties};
  }

  PropertyShorthand MaskPositionShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::WebkitMaskPositionX,
      PropertyId::WebkitMaskPositionY,
    };

    return PropertyShorthand {PropertyId::MaskPosition, properties};
  }

  PropertyShorthand OffsetShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::OffsetPosition,
      PropertyId::OffsetPath,
      PropertyId::OffsetDistance,
      PropertyId::OffsetRotate,
      PropertyId::OffsetAnchor,
    };

    return PropertyShorthand {PropertyId::Offset, properties};
  }

  PropertyShorthand OutlineShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::OutlineColor,
      PropertyId::OutlineStyle,
      PropertyId::OutlineWidth,
    };

    return PropertyShorthand {PropertyId::Outline, properties};
  }

  PropertyShorthand OverflowShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::OverflowX,
      PropertyId::OverflowY,
    };

    return PropertyShorthand {PropertyId::Overflow, properties};
  }

  PropertyShorthand OverscrollBehaviorShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::OverscrollBehaviorX,
      PropertyId::OverscrollBehaviorY,
    };

    return PropertyShorthand {PropertyId::OverscrollBehavior, properties};
  }

  PropertyShorthand PaddingShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::PaddingTop,
      PropertyId::PaddingRight,
      PropertyId::PaddingBottom,
      PropertyId::PaddingLeft,
    };

    return PropertyShorthand {PropertyId::Padding, properties};
  }

  PropertyShorthand PaddingBlockShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::PaddingBlockStart,
      PropertyId::PaddingBlockEnd,
    };

    return PropertyShorthand {PropertyId::PaddingBlock, properties};
  }

  PropertyShorthand PaddingInlineShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::PaddingInlineStart,
      PropertyId::PaddingInlineEnd,
    };

    return PropertyShorthand {PropertyId::PaddingInline, properties};
  }

  PropertyShorthand PageBreakAfterShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BreakAfter,
    };

    return PropertyShorthand {PropertyId::PageBreakAfter, properties};
  }

  PropertyShorthand PageBreakBeforeShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BreakBefore,
    };

    return PropertyShorthand {PropertyId::PageBreakBefore, properties};
  }

  PropertyShorthand PageBreakInsideShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BreakInside,
    };

    return PropertyShorthand {PropertyId::PageBreakInside, properties};
  }

  PropertyShorthand PerspectiveOriginShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::PerspectiveOriginX,
      PropertyId::PerspectiveOriginY,
    };

    return PropertyShorthand {PropertyId::PerspectiveOrigin, properties};
  }

  PropertyShorthand PlaceContentShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::AlignContent,
      PropertyId::JustifyContent,
    };

    return PropertyShorthand {PropertyId::PlaceContent, properties};
  }

  PropertyShorthand PlaceItemsShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::AlignItems,
      PropertyId::JustifyItems,
    };

    return PropertyShorthand {PropertyId::PlaceItems, properties};
  }

  PropertyShorthand PlaceSelfShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::AlignSelf,
      PropertyId::JustifySelf,
    };

    return PropertyShorthand {PropertyId::PlaceSelf, properties};
  }

  PropertyShorthand PositionTryShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::PositionTryOrder,
      PropertyId::PositionTryFallbacks,
    };

    return PropertyShorthand {PropertyId::PositionTry, properties};
  }

  PropertyShorthand ScrollMarginShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ScrollMarginTop,
      PropertyId::ScrollMarginRight,
      PropertyId::ScrollMarginBottom,
      PropertyId::ScrollMarginLeft,
    };

    return PropertyShorthand {PropertyId::ScrollMargin, properties};
  }

  PropertyShorthand ScrollMarginBlockShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ScrollMarginBlockStart,
      PropertyId::ScrollMarginBlockEnd,
    };

    return PropertyShorthand {PropertyId::ScrollMarginBlock, properties};
  }

  PropertyShorthand ScrollMarginInlineShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ScrollMarginInlineStart,
      PropertyId::ScrollMarginInlineEnd,
    };

    return PropertyShorthand {PropertyId::ScrollMarginInline, properties};
  }

  PropertyShorthand ScrollPaddingShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ScrollPaddingTop,
      PropertyId::ScrollPaddingRight,
      PropertyId::ScrollPaddingBottom,
      PropertyId::ScrollPaddingLeft,
    };

    return PropertyShorthand {PropertyId::ScrollPadding, properties};
  }

  PropertyShorthand ScrollPaddingBlockShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ScrollPaddingBlockStart,
      PropertyId::ScrollPaddingBlockEnd,
    };

    return PropertyShorthand {PropertyId::ScrollPaddingBlock, properties};
  }

  PropertyShorthand ScrollPaddingInlineShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ScrollPaddingInlineStart,
      PropertyId::ScrollPaddingInlineEnd,
    };

    return PropertyShorthand {PropertyId::ScrollPaddingInline, properties};
  }

  PropertyShorthand ScrollTimelineShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ScrollTimelineName,
      PropertyId::ScrollTimelineAxis,
    };

    return PropertyShorthand {PropertyId::ScrollTimeline, properties};
  }

  PropertyShorthand TextBoxShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::TextBoxTrim,
      PropertyId::TextBoxEdge,
    };

    return PropertyShorthand {PropertyId::TextBox, properties};
  }

  PropertyShorthand TextDecorationShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::TextDecorationLine,
      PropertyId::TextDecorationThickness,
      PropertyId::TextDecorationStyle,
      PropertyId::TextDecorationColor,
    };

    return PropertyShorthand {PropertyId::TextDecoration, properties};
  }

  PropertyShorthand TextDecorationSkipShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::TextDecorationSkipInk,
    };

    return PropertyShorthand {PropertyId::TextDecorationSkip, properties};
  }

  PropertyShorthand TextEmphasisShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::TextEmphasisStyle,
      PropertyId::TextEmphasisColor,
    };

    return PropertyShorthand {PropertyId::TextEmphasis, properties};
  }

  PropertyShorthand TextWrapShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::TextWrapMode,
      PropertyId::TextWrapStyle,
    };

    return PropertyShorthand {PropertyId::TextWrap, properties};
  }

  PropertyShorthand TransformOriginShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::TransformOriginX,
      PropertyId::TransformOriginY,
      PropertyId::TransformOriginZ,
    };

    return PropertyShorthand {PropertyId::TransformOrigin, properties};
  }

  PropertyShorthand TransitionShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::TransitionProperty,
      PropertyId::TransitionDuration,
      PropertyId::TransitionTimingFunction,
      PropertyId::TransitionDelay,
      PropertyId::TransitionBehavior,
    };

    return PropertyShorthand {PropertyId::Transition, properties};
  }

  PropertyShorthand ViewTimelineShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::ViewTimelineName,
      PropertyId::ViewTimelineAxis,
      PropertyId::ViewTimelineInset,
    };

    return PropertyShorthand {PropertyId::ViewTimeline, properties};
  }

  PropertyShorthand WhiteSpaceShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::WhiteSpaceCollapse,
      PropertyId::TextWrapMode,
    };

    return PropertyShorthand {PropertyId::WhiteSpace, properties};
  }

  PropertyShorthand WebkitBackgroundSizeShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::BackgroundSize,
    };

    return PropertyShorthand {PropertyId::WebkitBackgroundSize, properties};
  }

  PropertyShorthand WebkitMaskPositionShorthand() noexcept
  {
    constexpr static PropertyId properties[] = {
      PropertyId::WebkitMaskPositionX,
      PropertyId::WebkitMaskPositionY,
    };

    return PropertyShorthand {PropertyId::WebkitMaskPosition, properties};
  }

  PropertyShorthand ShorthandForProperty(PropertyId id) noexcept
  {
    switch (id)
    {
      case PropertyId::All:
      {
        return AllShorthand();
      }
      case PropertyId::Animation:
      {
        return AnimationShorthand();
      }
      case PropertyId::AnimationRange:
      {
        return AnimationRangeShorthand();
      }
      case PropertyId::Background:
      {
        return BackgroundShorthand();
      }
      case PropertyId::BackgroundPosition:
      {
        return BackgroundPositionShorthand();
      }
      case PropertyId::BlockStep:
      {
        return BlockStepShorthand();
      }
      case PropertyId::Border:
      {
        return BorderShorthand();
      }
      case PropertyId::BorderBlock:
      {
        return BorderBlockShorthand();
      }
      case PropertyId::BorderBlockColor:
      {
        return BorderBlockColorShorthand();
      }
      case PropertyId::BorderBlockEnd:
      {
        return BorderBlockEndShorthand();
      }
      case PropertyId::BorderBlockStart:
      {
        return BorderBlockStartShorthand();
      }
      case PropertyId::BorderBlockStyle:
      {
        return BorderBlockStyleShorthand();
      }
      case PropertyId::BorderBlockWidth:
      {
        return BorderBlockWidthShorthand();
      }
      case PropertyId::BorderBottom:
      {
        return BorderBottomShorthand();
      }
      case PropertyId::BorderColor:
      {
        return BorderColorShorthand();
      }
      case PropertyId::BorderImage:
      {
        return BorderImageShorthand();
      }
      case PropertyId::BorderInline:
      {
        return BorderInlineShorthand();
      }
      case PropertyId::BorderInlineColor:
      {
        return BorderInlineColorShorthand();
      }
      case PropertyId::BorderInlineEnd:
      {
        return BorderInlineEndShorthand();
      }
      case PropertyId::BorderInlineStart:
      {
        return BorderInlineStartShorthand();
      }
      case PropertyId::BorderInlineStyle:
      {
        return BorderInlineStyleShorthand();
      }
      case PropertyId::BorderInlineWidth:
      {
        return BorderInlineWidthShorthand();
      }
      case PropertyId::BorderLeft:
      {
        return BorderLeftShorthand();
      }
      case PropertyId::BorderRadius:
      {
        return BorderRadiusShorthand();
      }
      case PropertyId::BorderRight:
      {
        return BorderRightShorthand();
      }
      case PropertyId::BorderSpacing:
      {
        return BorderSpacingShorthand();
      }
      case PropertyId::BorderStyle:
      {
        return BorderStyleShorthand();
      }
      case PropertyId::BorderTop:
      {
        return BorderTopShorthand();
      }
      case PropertyId::BorderWidth:
      {
        return BorderWidthShorthand();
      }
      case PropertyId::ColumnRule:
      {
        return ColumnRuleShorthand();
      }
      case PropertyId::Columns:
      {
        return ColumnsShorthand();
      }
      case PropertyId::ContainIntrinsicSize:
      {
        return ContainIntrinsicSizeShorthand();
      }
      case PropertyId::Container:
      {
        return ContainerShorthand();
      }
      case PropertyId::CornerShape:
      {
        return CornerShapeShorthand();
      }
      case PropertyId::Flex:
      {
        return FlexShorthand();
      }
      case PropertyId::FlexFlow:
      {
        return FlexFlowShorthand();
      }
      case PropertyId::Font:
      {
        return FontShorthand();
      }
      case PropertyId::FontSynthesis:
      {
        return FontSynthesisShorthand();
      }
      case PropertyId::FontVariant:
      {
        return FontVariantShorthand();
      }
      case PropertyId::Gap:
      {
        return GapShorthand();
      }
      case PropertyId::Grid:
      {
        return GridShorthand();
      }
      case PropertyId::GridArea:
      {
        return GridAreaShorthand();
      }
      case PropertyId::GridColumn:
      {
        return GridColumnShorthand();
      }
      case PropertyId::GridRow:
      {
        return GridRowShorthand();
      }
      case PropertyId::GridTemplate:
      {
        return GridTemplateShorthand();
      }
      case PropertyId::Inset:
      {
        return InsetShorthand();
      }
      case PropertyId::InsetBlock:
      {
        return InsetBlockShorthand();
      }
      case PropertyId::InsetInline:
      {
        return InsetInlineShorthand();
      }
      case PropertyId::LineClamp:
      {
        return LineClampShorthand();
      }
      case PropertyId::ListStyle:
      {
        return ListStyleShorthand();
      }
      case PropertyId::Margin:
      {
        return MarginShorthand();
      }
      case PropertyId::MarginBlock:
      {
        return MarginBlockShorthand();
      }
      case PropertyId::MarginInline:
      {
        return MarginInlineShorthand();
      }
      case PropertyId::Marker:
      {
        return MarkerShorthand();
      }
      case PropertyId::Mask:
      {
        return MaskShorthand();
      }
      case PropertyId::MaskBorder:
      {
        return MaskBorderShorthand();
      }
      case PropertyId::MaskPosition:
      {
        return MaskPositionShorthand();
      }
      case PropertyId::Offset:
      {
        return OffsetShorthand();
      }
      case PropertyId::Outline:
      {
        return OutlineShorthand();
      }
      case PropertyId::Overflow:
      {
        return OverflowShorthand();
      }
      case PropertyId::OverscrollBehavior:
      {
        return OverscrollBehaviorShorthand();
      }
      case PropertyId::Padding:
      {
        return PaddingShorthand();
      }
      case PropertyId::PaddingBlock:
      {
        return PaddingBlockShorthand();
      }
      case PropertyId::PaddingInline:
      {
        return PaddingInlineShorthand();
      }
      case PropertyId::PageBreakAfter:
      {
        return PageBreakAfterShorthand();
      }
      case PropertyId::PageBreakBefore:
      {
        return PageBreakBeforeShorthand();
      }
      case PropertyId::PageBreakInside:
      {
        return PageBreakInsideShorthand();
      }
      case PropertyId::PerspectiveOrigin:
      {
        return PerspectiveOriginShorthand();
      }
      case PropertyId::PlaceContent:
      {
        return PlaceContentShorthand();
      }
      case PropertyId::PlaceItems:
      {
        return PlaceItemsShorthand();
      }
      case PropertyId::PlaceSelf:
      {
        return PlaceSelfShorthand();
      }
      case PropertyId::PositionTry:
      {
        return PositionTryShorthand();
      }
      case PropertyId::ScrollMargin:
      {
        return ScrollMarginShorthand();
      }
      case PropertyId::ScrollMarginBlock:
      {
        return ScrollMarginBlockShorthand();
      }
      case PropertyId::ScrollMarginInline:
      {
        return ScrollMarginInlineShorthand();
      }
      case PropertyId::ScrollPadding:
      {
        return ScrollPaddingShorthand();
      }
      case PropertyId::ScrollPaddingBlock:
      {
        return ScrollPaddingBlockShorthand();
      }
      case PropertyId::ScrollPaddingInline:
      {
        return ScrollPaddingInlineShorthand();
      }
      case PropertyId::ScrollTimeline:
      {
        return ScrollTimelineShorthand();
      }
      case PropertyId::TextBox:
      {
        return TextBoxShorthand();
      }
      case PropertyId::TextDecoration:
      {
        return TextDecorationShorthand();
      }
      case PropertyId::TextDecorationSkip:
      {
        return TextDecorationSkipShorthand();
      }
      case PropertyId::TextEmphasis:
      {
        return TextEmphasisShorthand();
      }
      case PropertyId::TextWrap:
      {
        return TextWrapShorthand();
      }
      case PropertyId::TransformOrigin:
      {
        return TransformOriginShorthand();
      }
      case PropertyId::Transition:
      {
        return TransitionShorthand();
      }
      case PropertyId::ViewTimeline:
      {
        return ViewTimelineShorthand();
      }
      case PropertyId::WhiteSpace:
      {
        return WhiteSpaceShorthand();
      }
      case PropertyId::WebkitBackgroundSize:
      {
        return WebkitBackgroundSizeShorthand();
      }
      case PropertyId::WebkitMaskPosition:
      {
        return WebkitMaskPositionShorthand();
      }
      default:
      {
        return {};
      }
    }
  }
  PropertyShorthandList MatchingShorthandsForLonghand(PropertyId id) noexcept
  {
    switch (id)
    {
      case PropertyId::AnimationRangeEnd:
      case PropertyId::AnimationRangeStart:
      {
        return PropertyShorthandList {AllShorthand(), AnimationShorthand(), AnimationRangeShorthand()};
      }
      case PropertyId::AnimationDelay:
      case PropertyId::AnimationDirection:
      case PropertyId::AnimationDuration:
      case PropertyId::AnimationFillMode:
      case PropertyId::AnimationIterationCount:
      case PropertyId::AnimationName:
      case PropertyId::AnimationPlayState:
      case PropertyId::AnimationTimeline:
      case PropertyId::AnimationTimingFunction:
      {
        return PropertyShorthandList {AllShorthand(), AnimationShorthand()};
      }
      case PropertyId::BackgroundPositionX:
      case PropertyId::BackgroundPositionY:
      {
        return PropertyShorthandList {AllShorthand(), BackgroundShorthand(), BackgroundPositionShorthand()};
      }
      case PropertyId::BackgroundSize:
      {
        return PropertyShorthandList {AllShorthand(), BackgroundShorthand(), WebkitBackgroundSizeShorthand()};
      }
      case PropertyId::BackgroundAttachment:
      case PropertyId::BackgroundClip:
      case PropertyId::BackgroundColor:
      case PropertyId::BackgroundImage:
      case PropertyId::BackgroundOrigin:
      case PropertyId::BackgroundRepeat:
      {
        return PropertyShorthandList {AllShorthand(), BackgroundShorthand()};
      }
      case PropertyId::BlockStepAlign:
      case PropertyId::BlockStepInsert:
      case PropertyId::BlockStepRound:
      case PropertyId::BlockStepSize:
      {
        return PropertyShorthandList {AllShorthand(), BlockStepShorthand()};
      }
      case PropertyId::BorderBlockEndColor:
      {
        return PropertyShorthandList {AllShorthand(), BorderBlockShorthand(), BorderBlockEndShorthand(), BorderBlockColorShorthand()};
      }
      case PropertyId::BorderBlockEndStyle:
      {
        return PropertyShorthandList {AllShorthand(), BorderBlockShorthand(), BorderBlockEndShorthand(), BorderBlockStyleShorthand()};
      }
      case PropertyId::BorderBlockEndWidth:
      {
        return PropertyShorthandList {AllShorthand(), BorderBlockShorthand(), BorderBlockEndShorthand(), BorderBlockWidthShorthand()};
      }
      case PropertyId::BorderBlockStartColor:
      {
        return PropertyShorthandList {AllShorthand(), BorderBlockShorthand(), BorderBlockStartShorthand(), BorderBlockColorShorthand()};
      }
      case PropertyId::BorderBlockStartStyle:
      {
        return PropertyShorthandList {AllShorthand(), BorderBlockShorthand(), BorderBlockStartShorthand(), BorderBlockStyleShorthand()};
      }
      case PropertyId::BorderBlockStartWidth:
      {
        return PropertyShorthandList {AllShorthand(), BorderBlockShorthand(), BorderBlockStartShorthand(), BorderBlockWidthShorthand()};
      }
      case PropertyId::BorderInlineEndColor:
      {
        return PropertyShorthandList {AllShorthand(), BorderInlineShorthand(), BorderInlineEndShorthand(), BorderInlineColorShorthand()};
      }
      case PropertyId::BorderInlineEndStyle:
      {
        return PropertyShorthandList {AllShorthand(), BorderInlineShorthand(), BorderInlineEndShorthand(), BorderInlineStyleShorthand()};
      }
      case PropertyId::BorderInlineEndWidth:
      {
        return PropertyShorthandList {AllShorthand(), BorderInlineShorthand(), BorderInlineEndShorthand(), BorderInlineWidthShorthand()};
      }
      case PropertyId::BorderInlineStartColor:
      {
        return PropertyShorthandList {AllShorthand(), BorderInlineShorthand(), BorderInlineStartShorthand(), BorderInlineColorShorthand()};
      }
      case PropertyId::BorderInlineStartStyle:
      {
        return PropertyShorthandList {AllShorthand(), BorderInlineShorthand(), BorderInlineStartShorthand(), BorderInlineStyleShorthand()};
      }
      case PropertyId::BorderInlineStartWidth:
      {
        return PropertyShorthandList {AllShorthand(), BorderInlineShorthand(), BorderInlineStartShorthand(), BorderInlineWidthShorthand()};
      }
      case PropertyId::BorderBottomLeftRadius:
      case PropertyId::BorderBottomRightRadius:
      case PropertyId::BorderTopLeftRadius:
      case PropertyId::BorderTopRightRadius:
      {
        return PropertyShorthandList {AllShorthand(), BorderRadiusShorthand()};
      }
      case PropertyId::BorderBottomColor:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderColorShorthand(), BorderBottomShorthand()};
      }
      case PropertyId::BorderLeftColor:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderColorShorthand(), BorderLeftShorthand()};
      }
      case PropertyId::BorderRightColor:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderColorShorthand(), BorderRightShorthand()};
      }
      case PropertyId::BorderTopColor:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderColorShorthand(), BorderTopShorthand()};
      }
      case PropertyId::BorderImageOutset:
      case PropertyId::BorderImageRepeat:
      case PropertyId::BorderImageSlice:
      case PropertyId::BorderImageSource:
      case PropertyId::BorderImageWidth:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderImageShorthand()};
      }
      case PropertyId::BorderBottomStyle:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderStyleShorthand(), BorderBottomShorthand()};
      }
      case PropertyId::BorderLeftStyle:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderStyleShorthand(), BorderLeftShorthand()};
      }
      case PropertyId::BorderRightStyle:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderStyleShorthand(), BorderRightShorthand()};
      }
      case PropertyId::BorderTopStyle:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderStyleShorthand(), BorderTopShorthand()};
      }
      case PropertyId::BorderBottomWidth:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderWidthShorthand(), BorderBottomShorthand()};
      }
      case PropertyId::BorderLeftWidth:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderWidthShorthand(), BorderLeftShorthand()};
      }
      case PropertyId::BorderRightWidth:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderWidthShorthand(), BorderRightShorthand()};
      }
      case PropertyId::BorderTopWidth:
      {
        return PropertyShorthandList {AllShorthand(), BorderShorthand(), BorderWidthShorthand(), BorderTopShorthand()};
      }
      case PropertyId::WebkitBorderHorizontalSpacing:
      case PropertyId::WebkitBorderVerticalSpacing:
      {
        return PropertyShorthandList {AllShorthand(), BorderSpacingShorthand()};
      }
      case PropertyId::ColumnRuleColor:
      case PropertyId::ColumnRuleStyle:
      case PropertyId::ColumnRuleWidth:
      {
        return PropertyShorthandList {AllShorthand(), ColumnRuleShorthand()};
      }
      case PropertyId::ColumnCount:
      case PropertyId::ColumnWidth:
      {
        return PropertyShorthandList {AllShorthand(), ColumnsShorthand()};
      }
      case PropertyId::ContainIntrinsicHeight:
      case PropertyId::ContainIntrinsicWidth:
      {
        return PropertyShorthandList {AllShorthand(), ContainIntrinsicSizeShorthand()};
      }
      case PropertyId::ContainerName:
      case PropertyId::ContainerType:
      {
        return PropertyShorthandList {AllShorthand(), ContainerShorthand()};
      }
      case PropertyId::CornerBottomLeftShape:
      case PropertyId::CornerBottomRightShape:
      case PropertyId::CornerTopLeftShape:
      case PropertyId::CornerTopRightShape:
      {
        return PropertyShorthandList {AllShorthand(), CornerShapeShorthand()};
      }
      case PropertyId::FlexDirection:
      case PropertyId::FlexWrap:
      {
        return PropertyShorthandList {AllShorthand(), FlexFlowShorthand()};
      }
      case PropertyId::FlexBasis:
      case PropertyId::FlexGrow:
      case PropertyId::FlexShrink:
      {
        return PropertyShorthandList {AllShorthand(), FlexShorthand()};
      }
      case PropertyId::FontVariantAlternates:
      case PropertyId::FontVariantCaps:
      case PropertyId::FontVariantEastAsian:
      case PropertyId::FontVariantEmoji:
      case PropertyId::FontVariantLigatures:
      case PropertyId::FontVariantNumeric:
      case PropertyId::FontVariantPosition:
      {
        return PropertyShorthandList {AllShorthand(), FontShorthand(), FontVariantShorthand()};
      }
      case PropertyId::FontFamily:
      case PropertyId::FontFeatureSettings:
      case PropertyId::FontKerning:
      case PropertyId::FontSize:
      case PropertyId::FontSizeAdjust:
      case PropertyId::FontStyle:
      case PropertyId::FontWeight:
      case PropertyId::FontWidth:
      case PropertyId::LineHeight:
      {
        return PropertyShorthandList {AllShorthand(), FontShorthand()};
      }
      case PropertyId::FontSynthesisSmallCaps:
      case PropertyId::FontSynthesisStyle:
      case PropertyId::FontSynthesisWeight:
      {
        return PropertyShorthandList {AllShorthand(), FontSynthesisShorthand()};
      }
      case PropertyId::ColumnGap:
      case PropertyId::RowGap:
      {
        return PropertyShorthandList {AllShorthand(), GapShorthand()};
      }
      case PropertyId::GridColumnEnd:
      case PropertyId::GridColumnStart:
      {
        return PropertyShorthandList {AllShorthand(), GridAreaShorthand(), GridColumnShorthand()};
      }
      case PropertyId::GridRowEnd:
      case PropertyId::GridRowStart:
      {
        return PropertyShorthandList {AllShorthand(), GridAreaShorthand(), GridRowShorthand()};
      }
      case PropertyId::GridTemplateAreas:
      case PropertyId::GridTemplateColumns:
      case PropertyId::GridTemplateRows:
      {
        return PropertyShorthandList {AllShorthand(), GridShorthand(), GridTemplateShorthand()};
      }
      case PropertyId::GridAutoColumns:
      case PropertyId::GridAutoFlow:
      case PropertyId::GridAutoRows:
      {
        return PropertyShorthandList {AllShorthand(), GridShorthand()};
      }
      case PropertyId::InsetBlockEnd:
      case PropertyId::InsetBlockStart:
      {
        return PropertyShorthandList {AllShorthand(), InsetBlockShorthand()};
      }
      case PropertyId::InsetInlineEnd:
      case PropertyId::InsetInlineStart:
      {
        return PropertyShorthandList {AllShorthand(), InsetInlineShorthand()};
      }
      case PropertyId::Bottom:
      case PropertyId::Left:
      case PropertyId::Right:
      case PropertyId::Top:
      {
        return PropertyShorthandList {AllShorthand(), InsetShorthand()};
      }
      case PropertyId::BlockEllipsis:
      case PropertyId::Continue:
      case PropertyId::MaxLines:
      {
        return PropertyShorthandList {AllShorthand(), LineClampShorthand()};
      }
      case PropertyId::ListStyleImage:
      case PropertyId::ListStylePosition:
      case PropertyId::ListStyleType:
      {
        return PropertyShorthandList {AllShorthand(), ListStyleShorthand()};
      }
      case PropertyId::MarginBlockEnd:
      case PropertyId::MarginBlockStart:
      {
        return PropertyShorthandList {AllShorthand(), MarginBlockShorthand()};
      }
      case PropertyId::MarginInlineEnd:
      case PropertyId::MarginInlineStart:
      {
        return PropertyShorthandList {AllShorthand(), MarginInlineShorthand()};
      }
      case PropertyId::MarginBottom:
      case PropertyId::MarginLeft:
      case PropertyId::MarginRight:
      case PropertyId::MarginTop:
      {
        return PropertyShorthandList {AllShorthand(), MarginShorthand()};
      }
      case PropertyId::MarkerEnd:
      case PropertyId::MarkerMid:
      case PropertyId::MarkerStart:
      {
        return PropertyShorthandList {AllShorthand(), MarkerShorthand()};
      }
      case PropertyId::MaskBorderOutset:
      case PropertyId::MaskBorderRepeat:
      case PropertyId::MaskBorderSlice:
      case PropertyId::MaskBorderSource:
      case PropertyId::MaskBorderWidth:
      {
        return PropertyShorthandList {AllShorthand(), MaskShorthand(), MaskBorderShorthand()};
      }
      case PropertyId::WebkitMaskPositionX:
      case PropertyId::WebkitMaskPositionY:
      {
        return PropertyShorthandList {AllShorthand(), MaskShorthand(), MaskPositionShorthand(), WebkitMaskPositionShorthand()};
      }
      case PropertyId::MaskClip:
      case PropertyId::MaskComposite:
      case PropertyId::MaskImage:
      case PropertyId::MaskMode:
      case PropertyId::MaskOrigin:
      case PropertyId::MaskRepeat:
      case PropertyId::MaskSize:
      {
        return PropertyShorthandList {AllShorthand(), MaskShorthand()};
      }
      case PropertyId::OffsetAnchor:
      case PropertyId::OffsetDistance:
      case PropertyId::OffsetPath:
      case PropertyId::OffsetPosition:
      case PropertyId::OffsetRotate:
      {
        return PropertyShorthandList {AllShorthand(), OffsetShorthand()};
      }
      case PropertyId::OutlineColor:
      case PropertyId::OutlineStyle:
      case PropertyId::OutlineWidth:
      {
        return PropertyShorthandList {AllShorthand(), OutlineShorthand()};
      }
      case PropertyId::OverflowX:
      case PropertyId::OverflowY:
      {
        return PropertyShorthandList {AllShorthand(), OverflowShorthand()};
      }
      case PropertyId::OverscrollBehaviorX:
      case PropertyId::OverscrollBehaviorY:
      {
        return PropertyShorthandList {AllShorthand(), OverscrollBehaviorShorthand()};
      }
      case PropertyId::PaddingBlockEnd:
      case PropertyId::PaddingBlockStart:
      {
        return PropertyShorthandList {AllShorthand(), PaddingBlockShorthand()};
      }
      case PropertyId::PaddingInlineEnd:
      case PropertyId::PaddingInlineStart:
      {
        return PropertyShorthandList {AllShorthand(), PaddingInlineShorthand()};
      }
      case PropertyId::PaddingBottom:
      case PropertyId::PaddingLeft:
      case PropertyId::PaddingRight:
      case PropertyId::PaddingTop:
      {
        return PropertyShorthandList {AllShorthand(), PaddingShorthand()};
      }
      case PropertyId::BreakAfter:
      {
        return PropertyShorthandList {AllShorthand(), PageBreakAfterShorthand()};
      }
      case PropertyId::BreakBefore:
      {
        return PropertyShorthandList {AllShorthand(), PageBreakBeforeShorthand()};
      }
      case PropertyId::BreakInside:
      {
        return PropertyShorthandList {AllShorthand(), PageBreakInsideShorthand()};
      }
      case PropertyId::PerspectiveOriginX:
      case PropertyId::PerspectiveOriginY:
      {
        return PropertyShorthandList {AllShorthand(), PerspectiveOriginShorthand()};
      }
      case PropertyId::AlignContent:
      case PropertyId::JustifyContent:
      {
        return PropertyShorthandList {AllShorthand(), PlaceContentShorthand()};
      }
      case PropertyId::AlignItems:
      case PropertyId::JustifyItems:
      {
        return PropertyShorthandList {AllShorthand(), PlaceItemsShorthand()};
      }
      case PropertyId::AlignSelf:
      case PropertyId::JustifySelf:
      {
        return PropertyShorthandList {AllShorthand(), PlaceSelfShorthand()};
      }
      case PropertyId::PositionTryFallbacks:
      case PropertyId::PositionTryOrder:
      {
        return PropertyShorthandList {AllShorthand(), PositionTryShorthand()};
      }
      case PropertyId::ScrollMarginBlockEnd:
      case PropertyId::ScrollMarginBlockStart:
      {
        return PropertyShorthandList {AllShorthand(), ScrollMarginBlockShorthand()};
      }
      case PropertyId::ScrollMarginInlineEnd:
      case PropertyId::ScrollMarginInlineStart:
      {
        return PropertyShorthandList {AllShorthand(), ScrollMarginInlineShorthand()};
      }
      case PropertyId::ScrollMarginBottom:
      case PropertyId::ScrollMarginLeft:
      case PropertyId::ScrollMarginRight:
      case PropertyId::ScrollMarginTop:
      {
        return PropertyShorthandList {AllShorthand(), ScrollMarginShorthand()};
      }
      case PropertyId::ScrollPaddingBlockEnd:
      case PropertyId::ScrollPaddingBlockStart:
      {
        return PropertyShorthandList {AllShorthand(), ScrollPaddingBlockShorthand()};
      }
      case PropertyId::ScrollPaddingInlineEnd:
      case PropertyId::ScrollPaddingInlineStart:
      {
        return PropertyShorthandList {AllShorthand(), ScrollPaddingInlineShorthand()};
      }
      case PropertyId::ScrollPaddingBottom:
      case PropertyId::ScrollPaddingLeft:
      case PropertyId::ScrollPaddingRight:
      case PropertyId::ScrollPaddingTop:
      {
        return PropertyShorthandList {AllShorthand(), ScrollPaddingShorthand()};
      }
      case PropertyId::ScrollTimelineAxis:
      case PropertyId::ScrollTimelineName:
      {
        return PropertyShorthandList {AllShorthand(), ScrollTimelineShorthand()};
      }
      case PropertyId::TextBoxEdge:
      case PropertyId::TextBoxTrim:
      {
        return PropertyShorthandList {AllShorthand(), TextBoxShorthand()};
      }
      case PropertyId::TextDecorationColor:
      case PropertyId::TextDecorationLine:
      case PropertyId::TextDecorationStyle:
      case PropertyId::TextDecorationThickness:
      {
        return PropertyShorthandList {AllShorthand(), TextDecorationShorthand()};
      }
      case PropertyId::TextDecorationSkipInk:
      {
        return PropertyShorthandList {AllShorthand(), TextDecorationSkipShorthand()};
      }
      case PropertyId::TextEmphasisColor:
      case PropertyId::TextEmphasisStyle:
      {
        return PropertyShorthandList {AllShorthand(), TextEmphasisShorthand()};
      }
      case PropertyId::TextWrapMode:
      {
        return PropertyShorthandList {AllShorthand(), TextWrapShorthand(), WhiteSpaceShorthand()};
      }
      case PropertyId::TextWrapStyle:
      {
        return PropertyShorthandList {AllShorthand(), TextWrapShorthand()};
      }
      case PropertyId::TransformOriginX:
      case PropertyId::TransformOriginY:
      case PropertyId::TransformOriginZ:
      {
        return PropertyShorthandList {AllShorthand(), TransformOriginShorthand()};
      }
      case PropertyId::TransitionBehavior:
      case PropertyId::TransitionDelay:
      case PropertyId::TransitionDuration:
      case PropertyId::TransitionProperty:
      case PropertyId::TransitionTimingFunction:
      {
        return PropertyShorthandList {AllShorthand(), TransitionShorthand()};
      }
      case PropertyId::ViewTimelineAxis:
      case PropertyId::ViewTimelineInset:
      case PropertyId::ViewTimelineName:
      {
        return PropertyShorthandList {AllShorthand(), ViewTimelineShorthand()};
      }
      case PropertyId::WhiteSpaceCollapse:
      {
        return PropertyShorthandList {AllShorthand(), WhiteSpaceShorthand()};
      }
      case PropertyId::AppleColorFilter:
      case PropertyId::WebkitBoxDecorationBreak:
      case PropertyId::WebkitColumnProgression:
      case PropertyId::WebkitFontSmoothing:
      case PropertyId::WebkitHyphenateLimitAfter:
      case PropertyId::WebkitHyphenateLimitBefore:
      case PropertyId::WebkitHyphenateLimitLines:
      case PropertyId::WebkitInitialLetter:
      case PropertyId::WebkitLineAlign:
      case PropertyId::WebkitLineBoxContain:
      case PropertyId::WebkitLocale:
      case PropertyId::WebkitRtlOrdering:
      case PropertyId::WebkitRubyPosition:
      case PropertyId::WebkitTextCombine:
      case PropertyId::WebkitTextDecorationsInEffect:
      case PropertyId::WebkitTextFillColor:
      case PropertyId::WebkitTextSecurity:
      case PropertyId::WebkitUserDrag:
      case PropertyId::WebkitUserModify:
      case PropertyId::WebkitUserSelect:
      case PropertyId::AccentColor:
      case PropertyId::AlignmentBaseline:
      case PropertyId::AnchorName:
      case PropertyId::AnchorScope:
      case PropertyId::AnimationComposition:
      case PropertyId::Appearance:
      case PropertyId::AspectRatio:
      case PropertyId::BackdropFilter:
      case PropertyId::BackfaceVisibility:
      case PropertyId::BackgroundBlendMode:
      case PropertyId::BaselineShift:
      case PropertyId::BlockSize:
      case PropertyId::BorderCollapse:
      case PropertyId::BorderEndEndRadius:
      case PropertyId::BorderEndStartRadius:
      case PropertyId::BorderStartEndRadius:
      case PropertyId::BorderStartStartRadius:
      case PropertyId::BoxShadow:
      case PropertyId::BoxSizing:
      case PropertyId::BufferedRendering:
      case PropertyId::CaptionSide:
      case PropertyId::CaretColor:
      case PropertyId::Clear:
      case PropertyId::Clip:
      case PropertyId::ClipPath:
      case PropertyId::ClipRule:
      case PropertyId::Color:
      case PropertyId::ColorInterpolation:
      case PropertyId::ColorInterpolationFilters:
      case PropertyId::ColumnFill:
      case PropertyId::ColumnSpan:
      case PropertyId::Contain:
      case PropertyId::ContainIntrinsicBlockSize:
      case PropertyId::ContainIntrinsicInlineSize:
      case PropertyId::Content:
      case PropertyId::ContentVisibility:
      case PropertyId::CornerEndEndShape:
      case PropertyId::CornerEndStartShape:
      case PropertyId::CornerStartEndShape:
      case PropertyId::CornerStartStartShape:
      case PropertyId::CounterIncrement:
      case PropertyId::CounterReset:
      case PropertyId::CounterSet:
      case PropertyId::Cursor:
      case PropertyId::Cx:
      case PropertyId::Cy:
      case PropertyId::D:
      case PropertyId::Display:
      case PropertyId::DominantBaseline:
      case PropertyId::DynamicRangeLimit:
      case PropertyId::EmptyCells:
      case PropertyId::FieldSizing:
      case PropertyId::Fill:
      case PropertyId::FillOpacity:
      case PropertyId::FillRule:
      case PropertyId::Filter:
      case PropertyId::Float:
      case PropertyId::FloodColor:
      case PropertyId::FloodOpacity:
      case PropertyId::FontPalette:
      case PropertyId::GlyphOrientationHorizontal:
      case PropertyId::GlyphOrientationVertical:
      case PropertyId::HangingPunctuation:
      case PropertyId::Height:
      case PropertyId::HyphenateCharacter:
      case PropertyId::Hyphens:
      case PropertyId::ImageOrientation:
      case PropertyId::ImageRendering:
      case PropertyId::InlineSize:
      case PropertyId::InputSecurity:
      case PropertyId::Isolation:
      case PropertyId::ItemTolerance:
      case PropertyId::LetterSpacing:
      case PropertyId::LightingColor:
      case PropertyId::LineBreak:
      case PropertyId::LineFitEdge:
      case PropertyId::MarginTrim:
      case PropertyId::MaskType:
      case PropertyId::MathDepth:
      case PropertyId::MathShift:
      case PropertyId::MathStyle:
      case PropertyId::MaxBlockSize:
      case PropertyId::MaxHeight:
      case PropertyId::MaxInlineSize:
      case PropertyId::MaxWidth:
      case PropertyId::MinBlockSize:
      case PropertyId::MinHeight:
      case PropertyId::MinInlineSize:
      case PropertyId::MinWidth:
      case PropertyId::MixBlendMode:
      case PropertyId::ObjectFit:
      case PropertyId::ObjectPosition:
      case PropertyId::Opacity:
      case PropertyId::Order:
      case PropertyId::Orphans:
      case PropertyId::OutlineOffset:
      case PropertyId::OverflowAnchor:
      case PropertyId::OverflowBlock:
      case PropertyId::OverflowInline:
      case PropertyId::OverflowWrap:
      case PropertyId::OverscrollBehaviorBlock:
      case PropertyId::OverscrollBehaviorInline:
      case PropertyId::Page:
      case PropertyId::PaintOrder:
      case PropertyId::Perspective:
      case PropertyId::PointerEvents:
      case PropertyId::Position:
      case PropertyId::PositionAnchor:
      case PropertyId::PositionArea:
      case PropertyId::PositionVisibility:
      case PropertyId::PrintColorAdjust:
      case PropertyId::Quotes:
      case PropertyId::R:
      case PropertyId::Resize:
      case PropertyId::Rotate:
      case PropertyId::RubyAlign:
      case PropertyId::RubyOverhang:
      case PropertyId::RubyPosition:
      case PropertyId::Rx:
      case PropertyId::Ry:
      case PropertyId::Scale:
      case PropertyId::ScrollBehavior:
      case PropertyId::ScrollSnapAlign:
      case PropertyId::ScrollSnapStop:
      case PropertyId::ScrollSnapType:
      case PropertyId::ScrollbarColor:
      case PropertyId::ScrollbarGutter:
      case PropertyId::ScrollbarWidth:
      case PropertyId::ShapeImageThreshold:
      case PropertyId::ShapeMargin:
      case PropertyId::ShapeOutside:
      case PropertyId::ShapeRendering:
      case PropertyId::SpeakAs:
      case PropertyId::StopColor:
      case PropertyId::StopOpacity:
      case PropertyId::Stroke:
      case PropertyId::StrokeColor:
      case PropertyId::StrokeDasharray:
      case PropertyId::StrokeDashoffset:
      case PropertyId::StrokeLinecap:
      case PropertyId::StrokeLinejoin:
      case PropertyId::StrokeMiterlimit:
      case PropertyId::StrokeOpacity:
      case PropertyId::StrokeWidth:
      case PropertyId::TabSize:
      case PropertyId::TableLayout:
      case PropertyId::TextAlign:
      case PropertyId::TextAlignLast:
      case PropertyId::TextAnchor:
      case PropertyId::TextAutospace:
      case PropertyId::TextCombineUpright:
      case PropertyId::TextEmphasisPosition:
      case PropertyId::TextGroupAlign:
      case PropertyId::TextIndent:
      case PropertyId::TextJustify:
      case PropertyId::TextOrientation:
      case PropertyId::TextOverflow:
      case PropertyId::TextRendering:
      case PropertyId::TextShadow:
      case PropertyId::TextSpacingTrim:
      case PropertyId::TextTransform:
      case PropertyId::TextUnderlineOffset:
      case PropertyId::TextUnderlinePosition:
      case PropertyId::TimelineScope:
      case PropertyId::TouchAction:
      case PropertyId::Transform:
      case PropertyId::TransformBox:
      case PropertyId::TransformStyle:
      case PropertyId::Translate:
      case PropertyId::VectorEffect:
      case PropertyId::VerticalAlign:
      case PropertyId::ViewTransitionClass:
      case PropertyId::ViewTransitionName:
      case PropertyId::Visibility:
      case PropertyId::Widows:
      case PropertyId::Width:
      case PropertyId::WillChange:
      case PropertyId::WordBreak:
      case PropertyId::WordSpacing:
      case PropertyId::WritingMode:
      case PropertyId::X:
      case PropertyId::Y:
      case PropertyId::ZIndex:
      case PropertyId::Zoom:
      {
        return PropertyShorthandList {AllShorthand()};
      }
      default:
      {
        return {};
      }
    }
  }
}
