// <auto-generated>
//   Generated at 2026-08-21 18:22:47 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#include "Krystal.HTML/CSS/Properties/CSSPropertyShorthandFunctions.hpp"
#include "Krystal.HTML/CSS/Properties/CSSPropertyShorthand.hpp"
#include <array>

namespace Krys::HTML
{
  CSSPropertyShorthand AllShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::WritingMode,
      CSSPropertyId::Display,
      CSSPropertyId::FontFamily,
      CSSPropertyId::FontFeatureSettings,
      CSSPropertyId::FontKerning,
      CSSPropertyId::FontPalette,
      CSSPropertyId::FontSize,
      CSSPropertyId::FontSizeAdjust,
      CSSPropertyId::FontStyle,
      CSSPropertyId::FontSynthesisSmallCaps,
      CSSPropertyId::FontSynthesisStyle,
      CSSPropertyId::FontSynthesisWeight,
      CSSPropertyId::FontVariantAlternates,
      CSSPropertyId::FontVariantCaps,
      CSSPropertyId::FontVariantEastAsian,
      CSSPropertyId::FontVariantEmoji,
      CSSPropertyId::FontVariantLigatures,
      CSSPropertyId::FontVariantNumeric,
      CSSPropertyId::FontVariantPosition,
      CSSPropertyId::FontWeight,
      CSSPropertyId::FontWidth,
      CSSPropertyId::WebkitFontSmoothing,
      CSSPropertyId::BackgroundImage,
      CSSPropertyId::D,
      CSSPropertyId::LineHeight,
      CSSPropertyId::MarginTrim,
      CSSPropertyId::CornerBottomLeftShape,
      CSSPropertyId::CornerBottomRightShape,
      CSSPropertyId::CornerTopLeftShape,
      CSSPropertyId::CornerTopRightShape,
      CSSPropertyId::MarginBottom,
      CSSPropertyId::MarginLeft,
      CSSPropertyId::MarginRight,
      CSSPropertyId::MarginTop,
      CSSPropertyId::PaddingBottom,
      CSSPropertyId::PaddingLeft,
      CSSPropertyId::PaddingRight,
      CSSPropertyId::PaddingTop,
      CSSPropertyId::CornerEndEndShape,
      CSSPropertyId::CornerEndStartShape,
      CSSPropertyId::CornerStartEndShape,
      CSSPropertyId::CornerStartStartShape,
      CSSPropertyId::MarginBlockEnd,
      CSSPropertyId::MarginBlockStart,
      CSSPropertyId::MarginInlineEnd,
      CSSPropertyId::MarginInlineStart,
      CSSPropertyId::PaddingBlockEnd,
      CSSPropertyId::PaddingBlockStart,
      CSSPropertyId::PaddingInlineEnd,
      CSSPropertyId::PaddingInlineStart,
    };

    return {.ShorthandId = CSSPropertyId::All, .LonghandProperties = properties};
  }

  CSSPropertyShorthand CornerShapeShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::CornerTopLeftShape,
      CSSPropertyId::CornerTopRightShape,
      CSSPropertyId::CornerBottomRightShape,
      CSSPropertyId::CornerBottomLeftShape,
    };

    return {.ShorthandId = CSSPropertyId::CornerShape, .LonghandProperties = properties};
  }

  CSSPropertyShorthand FontShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::FontStyle,
      CSSPropertyId::FontVariantCaps,
      CSSPropertyId::FontWeight,
      CSSPropertyId::FontWidth,
      CSSPropertyId::FontSize,
      CSSPropertyId::LineHeight,
      CSSPropertyId::FontFamily,
      CSSPropertyId::FontSizeAdjust,
      CSSPropertyId::FontKerning,
      CSSPropertyId::FontVariantAlternates,
      CSSPropertyId::FontVariantLigatures,
      CSSPropertyId::FontVariantNumeric,
      CSSPropertyId::FontVariantEastAsian,
      CSSPropertyId::FontVariantPosition,
      CSSPropertyId::FontVariantEmoji,
      CSSPropertyId::FontFeatureSettings,
    };

    return {.ShorthandId = CSSPropertyId::Font, .LonghandProperties = properties};
  }

  CSSPropertyShorthand FontSynthesisShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::FontSynthesisWeight,
      CSSPropertyId::FontSynthesisStyle,
      CSSPropertyId::FontSynthesisSmallCaps,
    };

    return {.ShorthandId = CSSPropertyId::FontSynthesis, .LonghandProperties = properties};
  }

  CSSPropertyShorthand FontVariantShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::FontVariantLigatures,
      CSSPropertyId::FontVariantCaps,
      CSSPropertyId::FontVariantAlternates,
      CSSPropertyId::FontVariantNumeric,
      CSSPropertyId::FontVariantEastAsian,
      CSSPropertyId::FontVariantPosition,
      CSSPropertyId::FontVariantEmoji,
    };

    return {.ShorthandId = CSSPropertyId::FontVariant, .LonghandProperties = properties};
  }

  CSSPropertyShorthand MarginShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::MarginTop,
      CSSPropertyId::MarginRight,
      CSSPropertyId::MarginBottom,
      CSSPropertyId::MarginLeft,
    };

    return {.ShorthandId = CSSPropertyId::Margin, .LonghandProperties = properties};
  }

  CSSPropertyShorthand MarginBlockShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::MarginBlockStart,
      CSSPropertyId::MarginBlockEnd,
    };

    return {.ShorthandId = CSSPropertyId::MarginBlock, .LonghandProperties = properties};
  }

  CSSPropertyShorthand MarginInlineShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::MarginInlineStart,
      CSSPropertyId::MarginInlineEnd,
    };

    return {.ShorthandId = CSSPropertyId::MarginInline, .LonghandProperties = properties};
  }

  CSSPropertyShorthand PaddingShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::PaddingTop,
      CSSPropertyId::PaddingRight,
      CSSPropertyId::PaddingBottom,
      CSSPropertyId::PaddingLeft,
    };

    return {.ShorthandId = CSSPropertyId::Padding, .LonghandProperties = properties};
  }

  CSSPropertyShorthand PaddingBlockShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::PaddingBlockStart,
      CSSPropertyId::PaddingBlockEnd,
    };

    return {.ShorthandId = CSSPropertyId::PaddingBlock, .LonghandProperties = properties};
  }

  CSSPropertyShorthand PaddingInlineShorthand() noexcept
  {
    constexpr static CSSPropertyId properties[] = {
      CSSPropertyId::PaddingInlineStart,
      CSSPropertyId::PaddingInlineEnd,
    };

    return {.ShorthandId = CSSPropertyId::PaddingInline, .LonghandProperties = properties};
  }

  CSSPropertyShorthand ShorthandForProperty(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::All:
      {
        return AllShorthand();
      }
      case CSSPropertyId::CornerShape:
      {
        return CornerShapeShorthand();
      }
      case CSSPropertyId::Font:
      {
        return FontShorthand();
      }
      case CSSPropertyId::FontSynthesis:
      {
        return FontSynthesisShorthand();
      }
      case CSSPropertyId::FontVariant:
      {
        return FontVariantShorthand();
      }
      case CSSPropertyId::Margin:
      {
        return MarginShorthand();
      }
      case CSSPropertyId::MarginBlock:
      {
        return MarginBlockShorthand();
      }
      case CSSPropertyId::MarginInline:
      {
        return MarginInlineShorthand();
      }
      case CSSPropertyId::Padding:
      {
        return PaddingShorthand();
      }
      case CSSPropertyId::PaddingBlock:
      {
        return PaddingBlockShorthand();
      }
      case CSSPropertyId::PaddingInline:
      {
        return PaddingInlineShorthand();
      }
      default:
      {
        return {};
      }
    }
  }

  CSSPropertyShorthandList MatchingShorthandsForLonghand(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::CornerBottomLeftShape:
      case CSSPropertyId::CornerBottomRightShape:
      case CSSPropertyId::CornerTopLeftShape:
      case CSSPropertyId::CornerTopRightShape:
      {
        return CSSPropertyShorthandList {AllShorthand(), CornerShapeShorthand()};
      }
      case CSSPropertyId::FontVariantAlternates:
      case CSSPropertyId::FontVariantCaps:
      case CSSPropertyId::FontVariantEastAsian:
      case CSSPropertyId::FontVariantEmoji:
      case CSSPropertyId::FontVariantLigatures:
      case CSSPropertyId::FontVariantNumeric:
      case CSSPropertyId::FontVariantPosition:
      {
        return CSSPropertyShorthandList {AllShorthand(), FontShorthand(), FontVariantShorthand()};
      }
      case CSSPropertyId::FontFamily:
      case CSSPropertyId::FontFeatureSettings:
      case CSSPropertyId::FontKerning:
      case CSSPropertyId::FontSize:
      case CSSPropertyId::FontSizeAdjust:
      case CSSPropertyId::FontStyle:
      case CSSPropertyId::FontWeight:
      case CSSPropertyId::FontWidth:
      case CSSPropertyId::LineHeight:
      {
        return CSSPropertyShorthandList {AllShorthand(), FontShorthand()};
      }
      case CSSPropertyId::FontSynthesisSmallCaps:
      case CSSPropertyId::FontSynthesisStyle:
      case CSSPropertyId::FontSynthesisWeight:
      {
        return CSSPropertyShorthandList {AllShorthand(), FontSynthesisShorthand()};
      }
      case CSSPropertyId::MarginBlockEnd:
      case CSSPropertyId::MarginBlockStart:
      {
        return CSSPropertyShorthandList {AllShorthand(), MarginBlockShorthand()};
      }
      case CSSPropertyId::MarginInlineEnd:
      case CSSPropertyId::MarginInlineStart:
      {
        return CSSPropertyShorthandList {AllShorthand(), MarginInlineShorthand()};
      }
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      {
        return CSSPropertyShorthandList {AllShorthand(), MarginShorthand()};
      }
      case CSSPropertyId::PaddingBlockEnd:
      case CSSPropertyId::PaddingBlockStart:
      {
        return CSSPropertyShorthandList {AllShorthand(), PaddingBlockShorthand()};
      }
      case CSSPropertyId::PaddingInlineEnd:
      case CSSPropertyId::PaddingInlineStart:
      {
        return CSSPropertyShorthandList {AllShorthand(), PaddingInlineShorthand()};
      }
      case CSSPropertyId::PaddingBottom:
      case CSSPropertyId::PaddingLeft:
      case CSSPropertyId::PaddingRight:
      case CSSPropertyId::PaddingTop:
      {
        return CSSPropertyShorthandList {AllShorthand(), PaddingShorthand()};
      }
      case CSSPropertyId::WebkitFontSmoothing:
      case CSSPropertyId::BackgroundImage:
      case CSSPropertyId::CornerEndEndShape:
      case CSSPropertyId::CornerEndStartShape:
      case CSSPropertyId::CornerStartEndShape:
      case CSSPropertyId::CornerStartStartShape:
      case CSSPropertyId::D:
      case CSSPropertyId::Display:
      case CSSPropertyId::FontPalette:
      case CSSPropertyId::MarginTrim:
      case CSSPropertyId::WritingMode:
      {
        return CSSPropertyShorthandList {AllShorthand()};
      }
      default:
      {
        return {};
      }
    }
  }
}
