// <auto-generated>
//   Generated at 2026-08-07 01:04:43 by css-properties.generator.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#include "Krystal.HTML/CSS/Properties/CSSPropertyShorthand.hpp"
#include <array>
#include <cassert>

namespace Krys::HTML
{
  namespace
  {
    KRYS_NODISCARD constexpr CSSPropertyShorthand AllShorthand() noexcept
    {
      constexpr static auto properties = std::to_array<CSSPropertyId>({
        CSSPropertyId::MarginBottom,
        CSSPropertyId::MarginLeft,
        CSSPropertyId::MarginRight,
        CSSPropertyId::MarginTop,
        CSSPropertyId::PaddingBottom,
        CSSPropertyId::PaddingLeft,
        CSSPropertyId::PaddingRight,
        CSSPropertyId::PaddingTop,
      });

      return CSSPropertyShorthand {
        .ShorthandId = CSSPropertyId::All,
        .LonghandProperties = properties,
      };
    }
    KRYS_NODISCARD constexpr CSSPropertyShorthand MarginShorthand() noexcept
    {
      constexpr static auto properties = std::to_array<CSSPropertyId>({
        CSSPropertyId::MarginTop,
        CSSPropertyId::MarginRight,
        CSSPropertyId::MarginBottom,
        CSSPropertyId::MarginLeft,
      });

      return CSSPropertyShorthand {
        .ShorthandId = CSSPropertyId::Margin,
        .LonghandProperties = properties,
      };
    }
    KRYS_NODISCARD constexpr CSSPropertyShorthand PaddingShorthand() noexcept
    {
      constexpr static auto properties = std::to_array<CSSPropertyId>({
        CSSPropertyId::PaddingTop,
        CSSPropertyId::PaddingRight,
        CSSPropertyId::PaddingBottom,
        CSSPropertyId::PaddingLeft,
      });

      return CSSPropertyShorthand {
        .ShorthandId = CSSPropertyId::Padding,
        .LonghandProperties = properties,
      };
    }
  }

  CSSPropertyShorthandList MatchingShorthandsForLonghand(CSSPropertyId property) noexcept
  {
    switch (property)
    {
      case CSSPropertyId::MarginTop:
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      {
        return CSSPropertyShorthandList {AllShorthand(), MarginShorthand()};
      }
      default:
      {
        return {};
      }
    }
  }
}