// <auto-generated>
//   Generated at 2026-08-21 18:22:47 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#include "Krystal.HTML/CSS/Properties/CSSPropertyParsing.hpp"
#include "Krystal.HTML/CSS/Parser/CSSParserContext.hpp"
#include "Krystal.HTML/CSS/Parser/CSSParserIdioms.hpp"
#include "Krystal.HTML/CSS/Properties/CSSPropertyParser.hpp"
#include "Krystal.HTML/CSS/Properties/CSSPropertyParserCustom.hpp"
#include "Krystal.HTML/CSS/Properties/CSSPropertyParserState.hpp"

namespace Krys::HTML
{
  using namespace CSSPropertyParserHelpers;

  KRYS_NODISCARD static bool isKeywordValidForWritingMode(CSSValueId keyword, CSSPropertyParserState &state) noexcept
  {
    switch (keyword) {
    case CSSValueId::HorizontalBt:
    case CSSValueId::HorizontalTb:
    case CSSValueId::Lr:
    case CSSValueId::LrTb:
    case CSSValueId::Rl:
    case CSSValueId::RlTb:
    case CSSValueId::Tb:
    case CSSValueId::TbRl:
    case CSSValueId::VerticalLr:
    case CSSValueId::VerticalRl:
      return true;
    case CSSValueId::SidewaysLr:
    case CSSValueId::SidewaysRl:
      return state.Context.SidewaysWritingModesEnabled;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool isKeywordValidForDirection(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Ltr:
    case CSSValueId::Rtl:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontFeatureSettings(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Normal:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool isKeywordValidForFontKerning(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Auto:
    case CSSValueId::None:
    case CSSValueId::Normal:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontPalette(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Dark:
    case CSSValueId::Light:
    case CSSValueId::Normal:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontSize(CSSValueId keyword, CSSPropertyParserState &state) noexcept
  {
    switch (keyword) {
    case CSSValueId::Math:
      return state.Context.cssMathDepthEnabled;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool isKeywordValidForFontSynthesisSmallCaps(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Auto:
    case CSSValueId::None:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool isKeywordValidForFontSynthesisStyle(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Auto:
    case CSSValueId::None:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool isKeywordValidForFontSynthesisWeight(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Auto:
    case CSSValueId::None:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantAlternates(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Normal:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool isKeywordValidForFontVariantCaps(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::AllPetiteCaps:
    case CSSValueId::AllSmallCaps:
    case CSSValueId::Normal:
    case CSSValueId::PetiteCaps:
    case CSSValueId::SmallCaps:
    case CSSValueId::TitlingCaps:
    case CSSValueId::Unicase:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantEastAsian(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Normal:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool isKeywordValidForFontVariantEmoji(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Emoji:
    case CSSValueId::Normal:
    case CSSValueId::Text:
    case CSSValueId::Unicode:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantLigatures(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::None:
    case CSSValueId::Normal:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantNumeric(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Normal:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool isKeywordValidForFontVariantPosition(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Normal:
    case CSSValueId::Sub:
    case CSSValueId::Super:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontWeight(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Bolder:
    case CSSValueId::Lighter:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool isKeywordValidForWebkitFontSmoothing(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Antialiased:
    case CSSValueId::Auto:
    case CSSValueId::None:
    case CSSValueId::SubpixelAntialiased:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForD(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::None:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForLineHeight(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Normal:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForMarginBottom(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Auto:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForMarginLeft(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Auto:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForMarginRight(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Auto:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForMarginTop(CSSValueId keyword) noexcept
  {
    switch (keyword) {
    case CSSValueId::Auto:
      return true;
    default:
      return false;
    }
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontPalette(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // dark | light | normal
    if (auto result = consumeIdent(range, IsKeywordValidForFontPalette))
      return result;
    // <palette-identifier>
    return ConsumePaletteIdentifier(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantLigatures(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // none | normal
    if (auto result = consumeIdent(range, IsKeywordValidForFontVariantLigatures))
      return result;
    // [ <common-lig-values> || <discretionary-lig-values> || <historical-lig-values> || <contextual-alt-values> ]@(no-single-item-opt)
    auto consumeMatchOneOrMoreAnyOrder = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
      RefPtr<CSSValue> value0; // <common-lig-values>
      auto tryConsumeTerm0 = [&value0](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm0 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // <common-lig-values>
          return ConsumeCommonLigValues(range, state);
        };
        if (value0)
          return false;
        value0 = consumeTerm0(range, state);
        return !!value0;
      };
      RefPtr<CSSValue> value1; // <discretionary-lig-values>
      auto tryConsumeTerm1 = [&value1](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm1 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // <discretionary-lig-values>
          return ConsumeDiscretionaryLigValues(range, state);
        };
        if (value1)
          return false;
        value1 = consumeTerm1(range, state);
        return !!value1;
      };
      RefPtr<CSSValue> value2; // <historical-lig-values>
      auto tryConsumeTerm2 = [&value2](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm2 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // <historical-lig-values>
          return ConsumeHistoricalLigValues(range, state);
        };
        if (value2)
          return false;
        value2 = consumeTerm2(range, state);
        return !!value2;
      };
      RefPtr<CSSValue> value3; // <contextual-alt-values>
      auto tryConsumeTerm3 = [&value3](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm3 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // <contextual-alt-values>
          return ConsumeContextualAltValues(range, state);
        };
        if (value3)
          return false;
        value3 = consumeTerm3(range, state);
        return !!value3;
      };
      for (size_t i = 0; i < 4 && !range.atEnd(); ++i) {
        if (tryConsumeTerm0(range, state) || tryConsumeTerm1(range, state) || tryConsumeTerm2(range, state) || tryConsumeTerm3(range, state))
          continue;
        break;
      }
      CSSValueListBuilder list;
      if (value0) // <common-lig-values>
        list.append(value0.releaseNonNull());
      if (value1) // <discretionary-lig-values>
        list.append(value1.releaseNonNull());
      if (value2) // <historical-lig-values>
        list.append(value2.releaseNonNull());
      if (value3) // <contextual-alt-values>
        list.append(value3.releaseNonNull());
      if (list.isEmpty())
        return { };
      return CSSValueList::createSpaceSeparated(WTF::move(list));
    };
    return consumeMatchOneOrMoreAnyOrder(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantNumeric(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = consumeIdent(range, IsKeywordValidForFontVariantNumeric))
      return result;
    // [ <numeric-figure-values> || <numeric-spacing-values> || <numeric-fraction-values> || ordinal || slashed-zero ]@(no-single-item-opt)
    auto consumeMatchOneOrMoreAnyOrder = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
      RefPtr<CSSValue> value0; // <numeric-figure-values>
      auto tryConsumeTerm0 = [&value0](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm0 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // <numeric-figure-values>
          return ConsumeNumericFigureValues(range, state);
        };
        if (value0)
          return false;
        value0 = consumeTerm0(range, state);
        return !!value0;
      };
      RefPtr<CSSValue> value1; // <numeric-spacing-values>
      auto tryConsumeTerm1 = [&value1](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm1 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // <numeric-spacing-values>
          return ConsumeNumericSpacingValues(range, state);
        };
        if (value1)
          return false;
        value1 = consumeTerm1(range, state);
        return !!value1;
      };
      RefPtr<CSSValue> value2; // <numeric-fraction-values>
      auto tryConsumeTerm2 = [&value2](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm2 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // <numeric-fraction-values>
          return ConsumeNumericFractionValues(range, state);
        };
        if (value2)
          return false;
        value2 = consumeTerm2(range, state);
        return !!value2;
      };
      RefPtr<CSSValue> value3; // ordinal
      auto tryConsumeTerm3 = [&value3](CSSTokenRange & range) -> bool {
        auto consumeTerm3 = [](CSSTokenRange & range) -> RefPtr<CSSValue> {
          // ordinal
          switch (auto keyword = range.Peek().ValueId(); keyword) {
          case CSSValueId::Ordinal:
            range.Discard();
            range.DiscardWhitespace();
            return CreateRef<CSSPrimitiveValue>(keyword);
          default:
            return nullptr;
          }
        };
        if (value3)
          return false;
        value3 = consumeTerm3(range);
        return !!value3;
      };
      RefPtr<CSSValue> value4; // slashed-zero
      auto tryConsumeTerm4 = [&value4](CSSTokenRange & range) -> bool {
        auto consumeTerm4 = [](CSSTokenRange & range) -> RefPtr<CSSValue> {
          // slashed-zero
          switch (auto keyword = range.Peek().ValueId(); keyword) {
          case CSSValueId::SlashedZero:
            range.Discard();
            range.DiscardWhitespace();
            return CreateRef<CSSPrimitiveValue>(keyword);
          default:
            return nullptr;
          }
        };
        if (value4)
          return false;
        value4 = consumeTerm4(range);
        return !!value4;
      };
      for (size_t i = 0; i < 5 && !range.atEnd(); ++i) {
        if (tryConsumeTerm0(range, state) || tryConsumeTerm1(range, state) || tryConsumeTerm2(range, state) || tryConsumeTerm3(range) || tryConsumeTerm4(range))
          continue;
        break;
      }
      CSSValueListBuilder list;
      if (value0) // <numeric-figure-values>
        list.append(value0.releaseNonNull());
      if (value1) // <numeric-spacing-values>
        list.append(value1.releaseNonNull());
      if (value2) // <numeric-fraction-values>
        list.append(value2.releaseNonNull());
      if (value3) // ordinal
        list.append(value3.releaseNonNull());
      if (value4) // slashed-zero
        list.append(value4.releaseNonNull());
      if (list.isEmpty())
        return { };
      return CSSValueList::createSpaceSeparated(WTF::move(list));
    };
    return consumeMatchOneOrMoreAnyOrder(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBackgroundImage(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-background-image>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-background-image>
        return ConsumeSingleBackgroundImage(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeD(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // none
    if (auto result = consumeIdent(range, IsKeywordValidForD))
      return result;
    // <path()>
    return ConsumePath(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMarginBottom(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // auto
    if (auto result = consumeIdent(range, IsKeywordValidForMarginBottom))
      return result;
    // <length-percentage anchor-size=['allowed']>
    return CSSPrimitiveValueResolver<CSS::LengthPercentage<>>::ConsumeAndResolve(range, state, { .AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(true), .UnitlessZeroLength = AllowUnitlessZero(true) });
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMarginLeft(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // auto
    if (auto result = consumeIdent(range, IsKeywordValidForMarginLeft))
      return result;
    // <length-percentage anchor-size=['allowed']>
    return CSSPrimitiveValueResolver<CSS::LengthPercentage<>>::ConsumeAndResolve(range, state, { .AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(true), .UnitlessZeroLength = AllowUnitlessZero(true) });
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMarginRight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // auto
    if (auto result = consumeIdent(range, IsKeywordValidForMarginRight))
      return result;
    // <length-percentage anchor-size=['allowed']>
    return CSSPrimitiveValueResolver<CSS::LengthPercentage<>>::ConsumeAndResolve(range, state, { .AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(true), .UnitlessZeroLength = AllowUnitlessZero(true) });
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMarginTop(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // auto
    if (auto result = consumeIdent(range, IsKeywordValidForMarginTop))
      return result;
    // <length-percentage anchor-size=['allowed']>
    return CSSPrimitiveValueResolver<CSS::LengthPercentage<>>::ConsumeAndResolve(range, state, { .AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(true), .UnitlessZeroLength = AllowUnitlessZero(true) });
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontFeatureSettings(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = consumeIdent(range, IsKeywordValidForFontFeatureSettings))
      return result;
    // <feature-tag-value>#@(no-single-item-opt)
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <feature-tag-value>
        return ConsumeFeatureTagValue(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::None, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontSize(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // math@(settings-flag=cssMathDepthEnabled)
    if (auto result = consumeIdent(range, IsKeywordValidForFontSize, state))
      return result;
    // <absolute-size>
    if (auto result = ConsumeAbsoluteSize(range, state))
      return result;
    // <relative-size>
    if (auto result = ConsumeRelativeSize(range, state))
      return result;
    // <length-percentage [0,inf]>
    if (auto result = CSSPrimitiveValueResolver<CSS::LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, { .AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true) }))
      return result;
    // <-webkit-absolute-size>
    if (auto result = ConsumeWebkitAbsoluteSize(range, state))
      return result;
    // <-webkit-relative-size>
    return ConsumeWebkitRelativeSize(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantAlternates(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = consumeIdent(range, IsKeywordValidForFontVariantAlternates))
      return result;
    // [ stylistic(<feature-value-name>) || historical-forms || styleset(<feature-value-name>#) || character-variant(<feature-value-name>#) || swash(<feature-value-name>) || ornaments(<feature-value-name>) || annotation(<feature-value-name>) ]@(no-single-item-opt)
    auto consumeMatchOneOrMoreAnyOrder = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
      RefPtr<CSSValue> value0; // stylistic(<feature-value-name>)
      auto tryConsumeTerm0 = [&value0](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm0 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // stylistic(<feature-value-name>)
          auto ConsumeStylisticFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              auto ConsumeParameter = [](CSSTokenRange &args, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                // <feature-value-name>
                return ConsumeFeatureValueName(args, state);
              };
              auto parameter = ConsumeParameter(args, state);
              if (!parameter)
                return { };
              return CSSValueListBuilder { parameter.releaseNonNull() };
            };
            if (range.Peek().FunctionId() != CSSValueId::Stylistic)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Stylistic, Krys::Move(result.value()));
          };
          return ConsumeStylisticFunction(range, state);
        };
        if (value0)
          return false;
        value0 = consumeTerm0(range, state);
        return !!value0;
      };
      RefPtr<CSSValue> value1; // historical-forms
      auto tryConsumeTerm1 = [&value1](CSSTokenRange & range) -> bool {
        auto consumeTerm1 = [](CSSTokenRange & range) -> RefPtr<CSSValue> {
          // historical-forms
          switch (auto keyword = range.Peek().ValueId(); keyword) {
          case CSSValueId::HistoricalForms:
            range.Discard();
            range.DiscardWhitespace();
            return CreateRef<CSSPrimitiveValue>(keyword);
          default:
            return nullptr;
          }
        };
        if (value1)
          return false;
        value1 = consumeTerm1(range);
        return !!value1;
      };
      RefPtr<CSSValue> value2; // styleset(<feature-value-name>#)
      auto tryConsumeTerm2 = [&value2](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm2 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // styleset(<feature-value-name>#)
          auto ConsumeStylesetFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              // <feature-value-name>#
              auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
                auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                  // <feature-value-name>
                  return ConsumeFeatureValueName(range, state);
                };
                return ConsumeListSeparatedByIntoBuilder<',', ListBounds::MinimumOf(1)>(range, ConsumeRepeatedTerm, state);
              };
              return ConsumeUnboundedRepetition(args, state);
            };
            if (range.Peek().FunctionId() != CSSValueId::Styleset)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Styleset, Krys::Move(result.value()));
          };
          return ConsumeStylesetFunction(range, state);
        };
        if (value2)
          return false;
        value2 = consumeTerm2(range, state);
        return !!value2;
      };
      RefPtr<CSSValue> value3; // character-variant(<feature-value-name>#)
      auto tryConsumeTerm3 = [&value3](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm3 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // character-variant(<feature-value-name>#)
          auto ConsumeCharacterVariantFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              // <feature-value-name>#
              auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
                auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                  // <feature-value-name>
                  return ConsumeFeatureValueName(range, state);
                };
                return ConsumeListSeparatedByIntoBuilder<',', ListBounds::MinimumOf(1)>(range, ConsumeRepeatedTerm, state);
              };
              return ConsumeUnboundedRepetition(args, state);
            };
            if (range.Peek().FunctionId() != CSSValueId::CharacterVariant)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::CharacterVariant, Krys::Move(result.value()));
          };
          return ConsumeCharacterVariantFunction(range, state);
        };
        if (value3)
          return false;
        value3 = consumeTerm3(range, state);
        return !!value3;
      };
      RefPtr<CSSValue> value4; // swash(<feature-value-name>)
      auto tryConsumeTerm4 = [&value4](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm4 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // swash(<feature-value-name>)
          auto ConsumeSwashFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              auto ConsumeParameter = [](CSSTokenRange &args, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                // <feature-value-name>
                return ConsumeFeatureValueName(args, state);
              };
              auto parameter = ConsumeParameter(args, state);
              if (!parameter)
                return { };
              return CSSValueListBuilder { parameter.releaseNonNull() };
            };
            if (range.Peek().FunctionId() != CSSValueId::Swash)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Swash, Krys::Move(result.value()));
          };
          return ConsumeSwashFunction(range, state);
        };
        if (value4)
          return false;
        value4 = consumeTerm4(range, state);
        return !!value4;
      };
      RefPtr<CSSValue> value5; // ornaments(<feature-value-name>)
      auto tryConsumeTerm5 = [&value5](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm5 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // ornaments(<feature-value-name>)
          auto ConsumeOrnamentsFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              auto ConsumeParameter = [](CSSTokenRange &args, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                // <feature-value-name>
                return ConsumeFeatureValueName(args, state);
              };
              auto parameter = ConsumeParameter(args, state);
              if (!parameter)
                return { };
              return CSSValueListBuilder { parameter.releaseNonNull() };
            };
            if (range.Peek().FunctionId() != CSSValueId::Ornaments)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Ornaments, Krys::Move(result.value()));
          };
          return ConsumeOrnamentsFunction(range, state);
        };
        if (value5)
          return false;
        value5 = consumeTerm5(range, state);
        return !!value5;
      };
      RefPtr<CSSValue> value6; // annotation(<feature-value-name>)
      auto tryConsumeTerm6 = [&value6](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm6 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // annotation(<feature-value-name>)
          auto ConsumeAnnotationFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              auto ConsumeParameter = [](CSSTokenRange &args, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                // <feature-value-name>
                return ConsumeFeatureValueName(args, state);
              };
              auto parameter = ConsumeParameter(args, state);
              if (!parameter)
                return { };
              return CSSValueListBuilder { parameter.releaseNonNull() };
            };
            if (range.Peek().FunctionId() != CSSValueId::Annotation)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Annotation, Krys::Move(result.value()));
          };
          return ConsumeAnnotationFunction(range, state);
        };
        if (value6)
          return false;
        value6 = consumeTerm6(range, state);
        return !!value6;
      };
      for (size_t i = 0; i < 7 && !range.atEnd(); ++i) {
        if (tryConsumeTerm0(range, state) || tryConsumeTerm1(range) || tryConsumeTerm2(range, state) || tryConsumeTerm3(range, state) || tryConsumeTerm4(range, state) || tryConsumeTerm5(range, state) || tryConsumeTerm6(range, state))
          continue;
        break;
      }
      CSSValueListBuilder list;
      if (value0) // stylistic(<feature-value-name>)
        list.append(value0.releaseNonNull());
      if (value1) // historical-forms
        list.append(value1.releaseNonNull());
      if (value2) // styleset(<feature-value-name>#)
        list.append(value2.releaseNonNull());
      if (value3) // character-variant(<feature-value-name>#)
        list.append(value3.releaseNonNull());
      if (value4) // swash(<feature-value-name>)
        list.append(value4.releaseNonNull());
      if (value5) // ornaments(<feature-value-name>)
        list.append(value5.releaseNonNull());
      if (value6) // annotation(<feature-value-name>)
        list.append(value6.releaseNonNull());
      if (list.isEmpty())
        return { };
      return CSSValueList::createSpaceSeparated(WTF::move(list));
    };
    return consumeMatchOneOrMoreAnyOrder(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantCaps(CSSTokenRange &range) noexcept
  {
    return consumeIdent(range, isKeywordValidForFontVariantCaps);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantEastAsian(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = consumeIdent(range, IsKeywordValidForFontVariantEastAsian))
      return result;
    // [ <east-asian-variant-values> || <east-asian-width-values> || ruby ]@(no-single-item-opt)
    auto consumeMatchOneOrMoreAnyOrder = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
      RefPtr<CSSValue> value0; // <east-asian-variant-values>
      auto tryConsumeTerm0 = [&value0](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm0 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // <east-asian-variant-values>
          return ConsumeEastAsianVariantValues(range, state);
        };
        if (value0)
          return false;
        value0 = consumeTerm0(range, state);
        return !!value0;
      };
      RefPtr<CSSValue> value1; // <east-asian-width-values>
      auto tryConsumeTerm1 = [&value1](CSSTokenRange & range, CSS::PropertyParserState& state) -> bool {
        auto consumeTerm1 = [](CSSTokenRange & range, CSS::PropertyParserState& state) -> RefPtr<CSSValue> {
          // <east-asian-width-values>
          return ConsumeEastAsianWidthValues(range, state);
        };
        if (value1)
          return false;
        value1 = consumeTerm1(range, state);
        return !!value1;
      };
      RefPtr<CSSValue> value2; // ruby
      auto tryConsumeTerm2 = [&value2](CSSTokenRange & range) -> bool {
        auto consumeTerm2 = [](CSSTokenRange & range) -> RefPtr<CSSValue> {
          // ruby
          switch (auto keyword = range.Peek().ValueId(); keyword) {
          case CSSValueId::Ruby:
            range.Discard();
            range.DiscardWhitespace();
            return CreateRef<CSSPrimitiveValue>(keyword);
          default:
            return nullptr;
          }
        };
        if (value2)
          return false;
        value2 = consumeTerm2(range);
        return !!value2;
      };
      for (size_t i = 0; i < 3 && !range.atEnd(); ++i) {
        if (tryConsumeTerm0(range, state) || tryConsumeTerm1(range, state) || tryConsumeTerm2(range))
          continue;
        break;
      }
      CSSValueListBuilder list;
      if (value0) // <east-asian-variant-values>
        list.append(value0.releaseNonNull());
      if (value1) // <east-asian-width-values>
        list.append(value1.releaseNonNull());
      if (value2) // ruby
        list.append(value2.releaseNonNull());
      if (list.isEmpty())
        return { };
      return CSSValueList::createSpaceSeparated(WTF::move(list));
    };
    return consumeMatchOneOrMoreAnyOrder(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantEmoji(CSSTokenRange &range) noexcept
  {
    return consumeIdent(range, isKeywordValidForFontVariantEmoji);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantPosition(CSSTokenRange &range) noexcept
  {
    return consumeIdent(range, isKeywordValidForFontVariantPosition);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontWeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // bolder | lighter
    if (auto result = consumeIdent(range, IsKeywordValidForFontWeight))
      return result;
    // <font-weight-absolute>
    return ConsumeFontWeightAbsolute(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeLineHeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = consumeIdent(range, IsKeywordValidForLineHeight))
      return result;
    // <number [0,inf]>
    if (auto result = CSSPrimitiveValueResolver<CSS::Number<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state))
      return result;
    // <length-percentage [0,inf]>
    return CSSPrimitiveValueResolver<CSS::LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, { .AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true) });
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeCornerStartEndShape(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <corner-shape-value>
    return ConsumeCornerShapeValue(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ParseStylePropertyLonghand(CSSTokenRange &range, CSSPropertyId id, CSSPropertyParserState &state)
  {
    if (!isExposed(id, state.context.propertySettings) && !isInternal(id)) {
      // Allow internal properties as we use them to parse several internal-only-shorthands (e.g. background-repeat),
      // and to handle certain DOM-exposed values (e.g. -webkit-font-size-delta from execCommand('FontSizeDelta')).
      ASSERT_NOT_REACHED();
      return { };
    }
    switch (id) {
    case CSSPropertyId::WritingMode:
      return consumeIdent(range, isKeywordValidForWritingMode, state);
    case CSSPropertyId::Direction:
      return consumeIdent(range, isKeywordValidForDirection);
    case CSSPropertyId::Display:
      return consumeDisplay(range, state);
    case CSSPropertyId::FontFamily:
      return ConsumeFontFamily(range, state);
    case CSSPropertyId::FontFeatureSettings:
      return CSSPropertyParsing::ConsumeFontFeatureSettings(range, state);
    case CSSPropertyId::FontKerning:
      return consumeIdent(range, isKeywordValidForFontKerning);
    case CSSPropertyId::FontPalette:
      return ConsumeFontPalette(range, state);
    case CSSPropertyId::FontSize:
      return CSSPropertyParsing::ConsumeFontSize(range, state);
    case CSSPropertyId::FontSizeAdjust:
      return ConsumeFontSizeAdjust(range, state);
    case CSSPropertyId::FontStyle:
      return ConsumeFontStyle(range, state);
    case CSSPropertyId::FontSynthesisSmallCaps:
      return consumeIdent(range, isKeywordValidForFontSynthesisSmallCaps);
    case CSSPropertyId::FontSynthesisStyle:
      return consumeIdent(range, isKeywordValidForFontSynthesisStyle);
    case CSSPropertyId::FontSynthesisWeight:
      return consumeIdent(range, isKeywordValidForFontSynthesisWeight);
    case CSSPropertyId::FontVariantAlternates:
      return CSSPropertyParsing::ConsumeFontVariantAlternates(range, state);
    case CSSPropertyId::FontVariantCaps:
      return consumeIdent(range, isKeywordValidForFontVariantCaps);
    case CSSPropertyId::FontVariantEastAsian:
      return CSSPropertyParsing::ConsumeFontVariantEastAsian(range, state);
    case CSSPropertyId::FontVariantEmoji:
      return consumeIdent(range, isKeywordValidForFontVariantEmoji);
    case CSSPropertyId::FontVariantLigatures:
      return ConsumeFontVariantLigatures(range, state);
    case CSSPropertyId::FontVariantNumeric:
      return ConsumeFontVariantNumeric(range, state);
    case CSSPropertyId::FontVariantPosition:
      return consumeIdent(range, isKeywordValidForFontVariantPosition);
    case CSSPropertyId::FontWeight:
      return CSSPropertyParsing::ConsumeFontWeight(range, state);
    case CSSPropertyId::FontWidth:
      return ConsumeFontWidthAbsolute(range, state);
    case CSSPropertyId::WebkitFontSmoothing:
      return consumeIdent(range, isKeywordValidForWebkitFontSmoothing);
    case CSSPropertyId::BackgroundImage:
      return ConsumeBackgroundImage(range, state);
    case CSSPropertyId::D:
      return ConsumeD(range, state);
    case CSSPropertyId::LineHeight:
      return CSSPropertyParsing::ConsumeLineHeight(range, state);
    case CSSPropertyId::MarginTrim:
      return ConsumeMarginTrim(range, state);
    case CSSPropertyId::CornerBottomLeftShape:
    case CSSPropertyId::CornerBottomRightShape:
    case CSSPropertyId::CornerTopLeftShape:
    case CSSPropertyId::CornerTopRightShape:
    case CSSPropertyId::CornerEndEndShape:
    case CSSPropertyId::CornerEndStartShape:
    case CSSPropertyId::CornerStartEndShape:
    case CSSPropertyId::CornerStartStartShape:
      return ConsumeCornerShapeValue(range, state);
    case CSSPropertyId::MarginBottom:
      return ConsumeMarginBottom(range, state);
    case CSSPropertyId::MarginLeft:
      return ConsumeMarginLeft(range, state);
    case CSSPropertyId::MarginRight:
      return ConsumeMarginRight(range, state);
    case CSSPropertyId::MarginTop:
      return ConsumeMarginTop(range, state);
    case CSSPropertyId::PaddingBottom:
    case CSSPropertyId::PaddingLeft:
    case CSSPropertyId::PaddingRight:
    case CSSPropertyId::PaddingTop:
    case CSSPropertyId::PaddingBlockEnd:
    case CSSPropertyId::PaddingBlockStart:
    case CSSPropertyId::PaddingInlineEnd:
    case CSSPropertyId::PaddingInlineStart:
      return CSSPrimitiveValueResolver<CSS::LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, { .AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true) });
    case CSSPropertyId::MarginBlockEnd:
    case CSSPropertyId::MarginBlockStart:
    case CSSPropertyId::MarginInlineEnd:
    case CSSPropertyId::MarginInlineStart:
      return ConsumeMarginLogical(range, state);
    default:
      return { };
    }
  }

  bool CSSPropertyParsing::parseStylePropertyShorthand(CSSParserTokenRange& range, CSSPropertyId id, CSS::PropertyParserState& state, CSS::PropertyParserResult& result)
  {
    ASSERT(isShorthand(id));

    switch (id) {
    case CSSPropertyId::CornerShape:
      if (!state.context.propertySettings.CornerShapePropertyEnabled) {
        ASSERT_NOT_REACHED();
        return false;
      }
      return CSS::PropertyParserCustom::consumeCoalescingQuadShorthand(range, state, CornerShapeShorthand(), result);
    case CSSPropertyId::Font:
      return CSS::PropertyParserCustom::consumeFontShorthand(range, state, FontShorthand(), result);
    case CSSPropertyId::FontSynthesis:
      return CSS::PropertyParserCustom::consumeFontSynthesisShorthand(range, state, FontSynthesisShorthand(), result);
    case CSSPropertyId::FontVariant:
      return CSS::PropertyParserCustom::ConsumeFontVariantShorthand(range, state, FontVariantShorthand(), result);
    case CSSPropertyId::Margin:
      return CSS::PropertyParserCustom::consumeCoalescingQuadShorthand(range, state, MarginShorthand(), result);
    case CSSPropertyId::MarginBlock:
      return CSS::PropertyParserCustom::consumeCoalescingPairShorthand(range, state, MarginBlockShorthand(), result);
    case CSSPropertyId::MarginInline:
      return CSS::PropertyParserCustom::consumeCoalescingPairShorthand(range, state, MarginInlineShorthand(), result);
    case CSSPropertyId::Padding:
      return CSS::PropertyParserCustom::consumeCoalescingQuadShorthand(range, state, PaddingShorthand(), result);
    case CSSPropertyId::PaddingBlock:
      return CSS::PropertyParserCustom::consumeCoalescingPairShorthand(range, state, PaddingBlockShorthand(), result);
    case CSSPropertyId::PaddingInline:
      return CSS::PropertyParserCustom::consumeCoalescingPairShorthand(range, state, PaddingInlineShorthand(), result);
    default:
      return false;
    }
  }

  bool CSSPropertyParsing::IsKeywordValidForStyleProperty(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState& state)
  {
    switch (id)
    {
      case CSSPropertyId::WritingMode:
      {
        return isKeywordValidForWritingMode(keyword, state);
      }
      case CSSPropertyId::Direction:
      {
        return isKeywordValidForDirection(keyword);
      }
      case CSSPropertyId::FontFeatureSettings:
      {
        return IsKeywordValidForFontFeatureSettings(keyword);
      }
      case CSSPropertyId::FontKerning:
      {
        return isKeywordValidForFontKerning(keyword);
      }
      case CSSPropertyId::FontPalette:
      {
        return IsKeywordValidForFontPalette(keyword);
      }
      case CSSPropertyId::FontSize:
      {
        return IsKeywordValidForFontSize(keyword, state);
      }
      case CSSPropertyId::FontSynthesisSmallCaps:
      {
        return isKeywordValidForFontSynthesisSmallCaps(keyword);
      }
      case CSSPropertyId::FontSynthesisStyle:
      {
        return isKeywordValidForFontSynthesisStyle(keyword);
      }
      case CSSPropertyId::FontSynthesisWeight:
      {
        return isKeywordValidForFontSynthesisWeight(keyword);
      }
      case CSSPropertyId::FontVariantAlternates:
      {
        return IsKeywordValidForFontVariantAlternates(keyword);
      }
      case CSSPropertyId::FontVariantCaps:
      {
        return isKeywordValidForFontVariantCaps(keyword);
      }
      case CSSPropertyId::FontVariantEastAsian:
      {
        return IsKeywordValidForFontVariantEastAsian(keyword);
      }
      case CSSPropertyId::FontVariantEmoji:
      {
        return isKeywordValidForFontVariantEmoji(keyword);
      }
      case CSSPropertyId::FontVariantLigatures:
      {
        return IsKeywordValidForFontVariantLigatures(keyword);
      }
      case CSSPropertyId::FontVariantNumeric:
      {
        return IsKeywordValidForFontVariantNumeric(keyword);
      }
      case CSSPropertyId::FontVariantPosition:
      {
        return isKeywordValidForFontVariantPosition(keyword);
      }
      case CSSPropertyId::FontWeight:
      {
        return IsKeywordValidForFontWeight(keyword);
      }
      case CSSPropertyId::WebkitFontSmoothing:
      {
        return isKeywordValidForWebkitFontSmoothing(keyword);
      }
      case CSSPropertyId::D:
      {
        return IsKeywordValidForD(keyword);
      }
      case CSSPropertyId::LineHeight:
      {
        return IsKeywordValidForLineHeight(keyword);
      }
      case CSSPropertyId::MarginBottom:
      {
        return IsKeywordValidForMarginBottom(keyword);
      }
      case CSSPropertyId::MarginLeft:
      {
        return IsKeywordValidForMarginLeft(keyword);
      }
      case CSSPropertyId::MarginRight:
      {
        return IsKeywordValidForMarginRight(keyword);
      }
      case CSSPropertyId::MarginTop:
      {
        return IsKeywordValidForMarginTop(keyword);
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSPropertyParsing::IsKeywordFastPathEligibleStyleProperty(CSSPropertyId id)
  {
    switch (id)
    {
      case CSSPropertyId::WritingMode:
      case CSSPropertyId::Direction:
      case CSSPropertyId::FontFeatureSettings:
      case CSSPropertyId::FontKerning:
      case CSSPropertyId::FontPalette:
      case CSSPropertyId::FontSize:
      case CSSPropertyId::FontSynthesisSmallCaps:
      case CSSPropertyId::FontSynthesisStyle:
      case CSSPropertyId::FontSynthesisWeight:
      case CSSPropertyId::FontVariantAlternates:
      case CSSPropertyId::FontVariantCaps:
      case CSSPropertyId::FontVariantEastAsian:
      case CSSPropertyId::FontVariantEmoji:
      case CSSPropertyId::FontVariantLigatures:
      case CSSPropertyId::FontVariantNumeric:
      case CSSPropertyId::FontVariantPosition:
      case CSSPropertyId::FontWeight:
      case CSSPropertyId::WebkitFontSmoothing:
      case CSSPropertyId::D:
      case CSSPropertyId::LineHeight:
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

}
