// <auto-generated>
//   Generated at 2026-08-11 17:30:22 by css-properties.generator.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#include "Krystal.HTML/CSS/Properties/CSSPropertyConsumer.hpp"

namespace Krys::HTML
{
  bool CSSPropertyConsumer::ParseShorthandStyleProperty(CSSTokenRange tokens, CSSPropertyParserState &state,
                                                        ParsedCSSPropertyList &properties) noexcept
  {
    return false;
  }

  bool CSSPropertyConsumer::ParseLonghandStyleProperty(CSSTokenRange tokens, CSSPropertyParserState &state,
                                                       ParsedCSSPropertyList &properties) noexcept
  {
    return false;
  }
}