// <auto-generated>
//   Generated at 2026-08-14 15:07:05 by css-properties.generator.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#include "Krystal.HTML/CSS/Properties/CSSPropertyShorthand.hpp"
#include <array>
#include <cassert>

namespace Krys::HTML
{
  namespace
  {
    KRYS_NODISCARD constexpr CSSPropertyShorthand AllShorthand() noexcept
    {
      constexpr static auto properties = std::to_array<CSSPropertyId>({
        CSSPropertyId::MarginBottom,
        CSSPropertyId::MarginLeft,
        CSSPropertyId::MarginRight,
        CSSPropertyId::MarginTop,
        CSSPropertyId::PaddingBottom,
        CSSPropertyId::PaddingLeft,
        CSSPropertyId::PaddingRight,
        CSSPropertyId::PaddingTop,
      });

      return CSSPropertyShorthand {
        .ShorthandId = CSSPropertyId::All,
        .LonghandProperties = properties,
      };
    }
    KRYS_NODISCARD constexpr CSSPropertyShorthand MarginShorthand() noexcept
    {
      constexpr static auto properties = std::to_array<CSSPropertyId>({
        CSSPropertyId::MarginTop,
        CSSPropertyId::MarginRight,
        CSSPropertyId::MarginBottom,
        CSSPropertyId::MarginLeft,
      });

      return CSSPropertyShorthand {
        .ShorthandId = CSSPropertyId::Margin,
        .LonghandProperties = properties,
      };
    }
    KRYS_NODISCARD constexpr CSSPropertyShorthand PaddingShorthand() noexcept
    {
      constexpr static auto properties = std::to_array<CSSPropertyId>({
        CSSPropertyId::PaddingTop,
        CSSPropertyId::PaddingRight,
        CSSPropertyId::PaddingBottom,
        CSSPropertyId::PaddingLeft,
      });

      return CSSPropertyShorthand {
        .ShorthandId = CSSPropertyId::Padding,
        .LonghandProperties = properties,
      };
    }
  }

  CSSPropertyShorthand LonghandsForShorthand(CSSPropertyId property) noexcept
  {
    switch (property)
    {
      case CSSPropertyId::All:
      {
        return AllShorthand();
      }
      case CSSPropertyId::Margin:
      {
        return MarginShorthand();
      }
      case CSSPropertyId::Padding:
      {
        return PaddingShorthand();
      }
      default:
      {
        return {};
      }
    }
  }

  CSSPropertyShorthandList MatchingShorthandsForLonghand(CSSPropertyId property) noexcept
  {
    switch (property)
    {
        case CSSPropertyId::MarginBottom:
        case CSSPropertyId::MarginLeft:
        case CSSPropertyId::MarginRight:
        case CSSPropertyId::MarginTop:
        {
            return CSSPropertyShorthandList {
                AllShorthand(),
                MarginShorthand(),
            };
        }
        case CSSPropertyId::PaddingBottom:
        case CSSPropertyId::PaddingLeft:
        case CSSPropertyId::PaddingRight:
        case CSSPropertyId::PaddingTop:
        {
            return CSSPropertyShorthandList {
                AllShorthand(),
                PaddingShorthand(),
            };
        }
      default:
      {
        return {};
      }
    }
  }
}