// <auto-generated>
//   Generated at 2026-08-23 11:23:38 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#include "Krystal.HTML/CSS/Properties/CSSPropertyParsing.hpp"
#include "Krystal.HTML/CSS/Parser/CSSParserContext.hpp"
#include "Krystal.HTML/CSS/Parser/CSSParserIdioms.hpp"
#include "Krystal.HTML/CSS/Properties/CSSPropertyParser.hpp"
#include "Krystal.HTML/CSS/Properties/CSSPropertyParserCustom.hpp"
#include "Krystal.HTML/CSS/Properties/CSSPropertyParserState.hpp"

namespace Krys::HTML
{
  using namespace CSSPropertyParserHelpers;

  KRYS_NODISCARD static bool IsKeywordValidForWritingMode(CSSValueId keyword, CSSPropertyParserState &state) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::HorizontalBt:
      case CSSValueId::HorizontalTb:
      case CSSValueId::Lr:
      case CSSValueId::LrTb:
      case CSSValueId::Rl:
      case CSSValueId::RlTb:
      case CSSValueId::Tb:
      case CSSValueId::TbRl:
      case CSSValueId::VerticalLr:
      case CSSValueId::VerticalRl:
      {
        return true;
      }
      case CSSValueId::SidewaysLr:
      case CSSValueId::SidewaysRl:
      {
        return state.Context.SidewaysWritingModesEnabled;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForDirection(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Ltr:
      case CSSValueId::Rtl:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontFeatureSettings(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Normal:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontKerning(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Auto:
      case CSSValueId::None:
      case CSSValueId::Normal:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontPalette(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Dark:
      case CSSValueId::Light:
      case CSSValueId::Normal:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontSize(CSSValueId keyword, CSSPropertyParserState &state) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Math:
      {
        return state.Context.CSSMathDepthEnabled;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontSynthesisSmallCaps(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Auto:
      case CSSValueId::None:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontSynthesisStyle(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Auto:
      case CSSValueId::None:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontSynthesisWeight(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Auto:
      case CSSValueId::None:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantAlternates(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Normal:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantCaps(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::AllPetiteCaps:
      case CSSValueId::AllSmallCaps:
      case CSSValueId::Normal:
      case CSSValueId::PetiteCaps:
      case CSSValueId::SmallCaps:
      case CSSValueId::TitlingCaps:
      case CSSValueId::Unicase:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantEastAsian(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Normal:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantEmoji(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Emoji:
      case CSSValueId::Normal:
      case CSSValueId::Text:
      case CSSValueId::Unicode:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantLigatures(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::None:
      case CSSValueId::Normal:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantNumeric(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Normal:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontVariantPosition(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Normal:
      case CSSValueId::Sub:
      case CSSValueId::Super:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForFontWeight(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Bolder:
      case CSSValueId::Lighter:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForBorderCollapse(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Collapse:
      case CSSValueId::Separate:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForBorderImageSource(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::None:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForD(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::None:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForLineHeight(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Normal:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForMarginBottom(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Auto:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForMarginLeft(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Auto:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForMarginRight(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Auto:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static bool IsKeywordValidForMarginTop(CSSValueId keyword) noexcept
  {
    switch (keyword)
    {
      case CSSValueId::Auto:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontPalette(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // dark | light | normal
    if (auto result = ConsumeIdent(range, IsKeywordValidForFontPalette))
    {
      return result;
    }
    // <palette-identifier>
    return ConsumePaletteIdentifier(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantLigatures(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // none | normal
    if (auto result = ConsumeIdent(range, IsKeywordValidForFontVariantLigatures))
    {
      return result;
    }
    // [ <common-lig-values> || <discretionary-lig-values> || <historical-lig-values> || <contextual-alt-values> ]@(no-single-item-opt)
    auto ConsumeMatchOneOrMoreAnyOrder = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
    {
      RefPtr<CSSValue> value0; // <common-lig-values>
      auto TryConsumeTerm0 = [&value0](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm0 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // <common-lig-values>
          return ConsumeCommonLigValues(range, state);
        };
        if (value0)
        {
          return false;
        }
        value0 = ConsumeTerm0(range, state);
        return !!value0;
      };
      RefPtr<CSSValue> value1; // <discretionary-lig-values>
      auto TryConsumeTerm1 = [&value1](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm1 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // <discretionary-lig-values>
          return ConsumeDiscretionaryLigValues(range, state);
        };
        if (value1)
        {
          return false;
        }
        value1 = ConsumeTerm1(range, state);
        return !!value1;
      };
      RefPtr<CSSValue> value2; // <historical-lig-values>
      auto TryConsumeTerm2 = [&value2](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm2 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // <historical-lig-values>
          return ConsumeHistoricalLigValues(range, state);
        };
        if (value2)
        {
          return false;
        }
        value2 = ConsumeTerm2(range, state);
        return !!value2;
      };
      RefPtr<CSSValue> value3; // <contextual-alt-values>
      auto TryConsumeTerm3 = [&value3](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm3 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // <contextual-alt-values>
          return ConsumeContextualAltValues(range, state);
        };
        if (value3)
        {
          return false;
        }
        value3 = ConsumeTerm3(range, state);
        return !!value3;
      };
      for (size_t i = 0uz; i < 4 && !range.IsAtEnd(); ++i)
      {
        if (TryConsumeTerm0(range, state) || TryConsumeTerm1(range, state) || TryConsumeTerm2(range, state) || TryConsumeTerm3(range, state))
        {
          continue;
        }
        break;
      }
      CSSValueListBuilder list;
      if (value0) // <common-lig-values>
      {
        list.append(value0.releaseNonNull());
      }
      if (value1) // <discretionary-lig-values>
      {
        list.append(value1.releaseNonNull());
      }
      if (value2) // <historical-lig-values>
      {
        list.append(value2.releaseNonNull());
      }
      if (value3) // <contextual-alt-values>
      {
        list.append(value3.releaseNonNull());
      }
      if (list.IsEmpty())
      {
        return { };
      }
      return CSSValueList::createSpaceSeparated(Krys::Move(list));
    };
    return ConsumeMatchOneOrMoreAnyOrder(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantNumeric(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = ConsumeIdent(range, IsKeywordValidForFontVariantNumeric))
    {
      return result;
    }
    // [ <numeric-figure-values> || <numeric-spacing-values> || <numeric-fraction-values> || ordinal || slashed-zero ]@(no-single-item-opt)
    auto ConsumeMatchOneOrMoreAnyOrder = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
    {
      RefPtr<CSSValue> value0; // <numeric-figure-values>
      auto TryConsumeTerm0 = [&value0](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm0 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // <numeric-figure-values>
          return ConsumeNumericFigureValues(range, state);
        };
        if (value0)
        {
          return false;
        }
        value0 = ConsumeTerm0(range, state);
        return !!value0;
      };
      RefPtr<CSSValue> value1; // <numeric-spacing-values>
      auto TryConsumeTerm1 = [&value1](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm1 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // <numeric-spacing-values>
          return ConsumeNumericSpacingValues(range, state);
        };
        if (value1)
        {
          return false;
        }
        value1 = ConsumeTerm1(range, state);
        return !!value1;
      };
      RefPtr<CSSValue> value2; // <numeric-fraction-values>
      auto TryConsumeTerm2 = [&value2](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm2 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // <numeric-fraction-values>
          return ConsumeNumericFractionValues(range, state);
        };
        if (value2)
        {
          return false;
        }
        value2 = ConsumeTerm2(range, state);
        return !!value2;
      };
      RefPtr<CSSValue> value3; // ordinal
      auto TryConsumeTerm3 = [&value3](CSSTokenRange &range) -> bool
      {
        auto ConsumeTerm3 = [](CSSTokenRange &range) -> RefPtr<CSSValue>
        {
          // ordinal
          switch (auto keyword = range.Peek().ValueId(); keyword)
          {
            case CSSValueId::Ordinal:
            {
              range.Discard();
              range.DiscardWhitespace();
              return CreateRef<CSSPrimitiveValue>(keyword);
            }
            default:
            {
              return nullptr;
            }
          }
        };
        if (value3)
        {
          return false;
        }
        value3 = ConsumeTerm3(range);
        return !!value3;
      };
      RefPtr<CSSValue> value4; // slashed-zero
      auto TryConsumeTerm4 = [&value4](CSSTokenRange &range) -> bool
      {
        auto ConsumeTerm4 = [](CSSTokenRange &range) -> RefPtr<CSSValue>
        {
          // slashed-zero
          switch (auto keyword = range.Peek().ValueId(); keyword)
          {
            case CSSValueId::SlashedZero:
            {
              range.Discard();
              range.DiscardWhitespace();
              return CreateRef<CSSPrimitiveValue>(keyword);
            }
            default:
            {
              return nullptr;
            }
          }
        };
        if (value4)
        {
          return false;
        }
        value4 = ConsumeTerm4(range);
        return !!value4;
      };
      for (size_t i = 0uz; i < 5 && !range.IsAtEnd(); ++i)
      {
        if (TryConsumeTerm0(range, state) || TryConsumeTerm1(range, state) || TryConsumeTerm2(range, state) || TryConsumeTerm3(range) || TryConsumeTerm4(range))
        {
          continue;
        }
        break;
      }
      CSSValueListBuilder list;
      if (value0) // <numeric-figure-values>
      {
        list.append(value0.releaseNonNull());
      }
      if (value1) // <numeric-spacing-values>
      {
        list.append(value1.releaseNonNull());
      }
      if (value2) // <numeric-fraction-values>
      {
        list.append(value2.releaseNonNull());
      }
      if (value3) // ordinal
      {
        list.append(value3.releaseNonNull());
      }
      if (value4) // slashed-zero
      {
        list.append(value4.releaseNonNull());
      }
      if (list.IsEmpty())
      {
        return { };
      }
      return CSSValueList::createSpaceSeparated(Krys::Move(list));
    };
    return ConsumeMatchOneOrMoreAnyOrder(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBackgroundImage(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-background-image>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-background-image>
        return ConsumeSingleBackgroundImage(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationComposition(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-composition>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-composition>
        return ConsumeSingleAnimationComposition(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationDelay(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <time>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <time>
        return CSSPrimitiveValueResolver<Time<>>::ConsumeAndResolve(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationDirection(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-direction>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-direction>
        return ConsumeSingleAnimationDirection(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationDuration(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-duration>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-duration>
        return ConsumeSingleAnimationDuration(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationFillMode(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-fill-mode>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-fill-mode>
        return ConsumeSingleAnimationFillMode(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationIterationCount(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-iteration-count>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-iteration-count>
        return ConsumeSingleAnimationIterationCount(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationName(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-name>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-name>
        return ConsumeSingleAnimationName(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationPlayState(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-play-state>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-play-state>
        return ConsumeSingleAnimationPlayState(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationRangeEnd(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-range-end>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-range-end>
        return ConsumeSingleAnimationRangeEnd(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationRangeStart(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-range-start>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-range-start>
        return ConsumeSingleAnimationRangeStart(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationTimeline(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <single-animation-timeline>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <single-animation-timeline>
        return ConsumeSingleAnimationTimeline(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeAnimationTimingFunction(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <easing-function>#
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <easing-function>
        return ConsumeEasingFunction(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::SingleValue, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderImageSource(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // none
    if (auto result = ConsumeIdent(range, IsKeywordValidForBorderImageSource))
    {
      return result;
    }
    // <image>
    return ConsumeImage(range, state, {.AllowedImageTypes = { AllowedImageType::URLFunction, AllowedImageType::ImageSet, AllowedImageType::GeneratedImage } });
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeD(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // none
    if (auto result = ConsumeIdent(range, IsKeywordValidForD))
    {
      return result;
    }
    // <path()>
    return ConsumePath(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderBottomLeftRadius(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <length-percentage [0,inf]>{1,2}@(type=CSSValuePair default=previous)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <length-percentage [0,inf]>
        return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term1) {
        term1 = term0;
        range = rangeCopy;
        return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderBottomRightRadius(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <length-percentage [0,inf]>{1,2}@(type=CSSValuePair default=previous)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <length-percentage [0,inf]>
        return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term1) {
        term1 = term0;
        range = rangeCopy;
        return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderTopLeftRadius(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <length-percentage [0,inf]>{1,2}@(type=CSSValuePair default=previous)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <length-percentage [0,inf]>
        return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term1) {
        term1 = term0;
        range = rangeCopy;
        return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderTopRightRadius(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <length-percentage [0,inf]>{1,2}@(type=CSSValuePair default=previous)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <length-percentage [0,inf]>
        return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term1) {
        term1 = term0;
        range = rangeCopy;
        return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMarginBottom(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // auto
    if (auto result = ConsumeIdent(range, IsKeywordValidForMarginBottom))
    {
      return result;
    }
    // <length-percentage anchor-size=['allowed']>
    return CSSPrimitiveValueResolver<LengthPercentage<>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(true), .UnitlessZeroLength = AllowUnitlessZero(true)});
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMarginLeft(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // auto
    if (auto result = ConsumeIdent(range, IsKeywordValidForMarginLeft))
    {
      return result;
    }
    // <length-percentage anchor-size=['allowed']>
    return CSSPrimitiveValueResolver<LengthPercentage<>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(true), .UnitlessZeroLength = AllowUnitlessZero(true)});
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMarginRight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // auto
    if (auto result = ConsumeIdent(range, IsKeywordValidForMarginRight))
    {
      return result;
    }
    // <length-percentage anchor-size=['allowed']>
    return CSSPrimitiveValueResolver<LengthPercentage<>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(true), .UnitlessZeroLength = AllowUnitlessZero(true)});
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMarginTop(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // auto
    if (auto result = ConsumeIdent(range, IsKeywordValidForMarginTop))
    {
      return result;
    }
    // <length-percentage anchor-size=['allowed']>
    return CSSPrimitiveValueResolver<LengthPercentage<>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(true), .UnitlessZeroLength = AllowUnitlessZero(true)});
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderEndEndRadius(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <length-percentage [0,inf]>{1,2}@(type=CSSValuePair default=previous)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <length-percentage [0,inf]>
        return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term1) {
        term1 = term0;
        range = rangeCopy;
        return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderEndStartRadius(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <length-percentage [0,inf]>{1,2}@(type=CSSValuePair default=previous)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <length-percentage [0,inf]>
        return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term1) {
        term1 = term0;
        range = rangeCopy;
        return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderStartEndRadius(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <length-percentage [0,inf]>{1,2}@(type=CSSValuePair default=previous)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <length-percentage [0,inf]>
        return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term1) {
        term1 = term0;
        range = rangeCopy;
        return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range, state);
  }

  KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderStartStartRadius(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <length-percentage [0,inf]>{1,2}@(type=CSSValuePair default=previous)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <length-percentage [0,inf]>
        return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term1) {
        term1 = term0;
        range = rangeCopy;
        return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontFeatureSettings(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = ConsumeIdent(range, IsKeywordValidForFontFeatureSettings))
    {
      return result;
    }
    // <feature-tag-value>#@(no-single-item-opt)
    auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <feature-tag-value>
        return ConsumeFeatureTagValue(range, state);
      };
      return ConsumeListSeparatedBy<',', ListBounds::MinimumOf(1), ListOptimization::None, CSSValueList>(range, ConsumeRepeatedTerm, state);
    };
    return ConsumeUnboundedRepetition(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontSize(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // math@(settings-flag=CSSMathDepthEnabled)
    if (auto result = ConsumeIdent(range, IsKeywordValidForFontSize, state))
    {
      return result;
    }
    // <absolute-size>
    if (auto result = ConsumeAbsoluteSize(range, state))
    {
      return result;
    }
    // <relative-size>
    if (auto result = ConsumeRelativeSize(range, state))
    {
      return result;
    }
    // <length-percentage [0,inf]>
    if (auto result = CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)}))
    {
      return result;
    }
    // <-webkit-absolute-size>
    if (auto result = ConsumeWebkitAbsoluteSize(range, state))
    {
      return result;
    }
    // <-webkit-relative-size>
    return ConsumeWebkitRelativeSize(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantAlternates(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = ConsumeIdent(range, IsKeywordValidForFontVariantAlternates))
    {
      return result;
    }
    // [ stylistic(<feature-value-name>) || historical-forms || styleset(<feature-value-name>#) || character-variant(<feature-value-name>#) || swash(<feature-value-name>) || ornaments(<feature-value-name>) || annotation(<feature-value-name>) ]@(no-single-item-opt)
    auto ConsumeMatchOneOrMoreAnyOrder = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
    {
      RefPtr<CSSValue> value0; // stylistic(<feature-value-name>)
      auto TryConsumeTerm0 = [&value0](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm0 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // stylistic(<feature-value-name>)
          auto ConsumeStylisticFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              auto ConsumeParameter = [](CSSTokenRange &args, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                // <feature-value-name>
                return ConsumeFeatureValueName(args, state);
              };
              auto parameter = ConsumeParameter(args, state);
              if (!parameter)
                return { };
              return CSSValueListBuilder { parameter.releaseNonNull() };
            };
            if (range.Peek().FunctionId() != CSSValueId::Stylistic)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Stylistic, Krys::Move(result.value()));
          };
          return ConsumeStylisticFunction(range, state);
        };
        if (value0)
        {
          return false;
        }
        value0 = ConsumeTerm0(range, state);
        return !!value0;
      };
      RefPtr<CSSValue> value1; // historical-forms
      auto TryConsumeTerm1 = [&value1](CSSTokenRange &range) -> bool
      {
        auto ConsumeTerm1 = [](CSSTokenRange &range) -> RefPtr<CSSValue>
        {
          // historical-forms
          switch (auto keyword = range.Peek().ValueId(); keyword)
          {
            case CSSValueId::HistoricalForms:
            {
              range.Discard();
              range.DiscardWhitespace();
              return CreateRef<CSSPrimitiveValue>(keyword);
            }
            default:
            {
              return nullptr;
            }
          }
        };
        if (value1)
        {
          return false;
        }
        value1 = ConsumeTerm1(range);
        return !!value1;
      };
      RefPtr<CSSValue> value2; // styleset(<feature-value-name>#)
      auto TryConsumeTerm2 = [&value2](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm2 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // styleset(<feature-value-name>#)
          auto ConsumeStylesetFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              // <feature-value-name>#
              auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
                auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                  // <feature-value-name>
                  return ConsumeFeatureValueName(range, state);
                };
                return ConsumeListSeparatedByIntoBuilder<',', ListBounds::MinimumOf(1)>(range, ConsumeRepeatedTerm, state);
              };
              return ConsumeUnboundedRepetition(args, state);
            };
            if (range.Peek().FunctionId() != CSSValueId::Styleset)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Styleset, Krys::Move(result.value()));
          };
          return ConsumeStylesetFunction(range, state);
        };
        if (value2)
        {
          return false;
        }
        value2 = ConsumeTerm2(range, state);
        return !!value2;
      };
      RefPtr<CSSValue> value3; // character-variant(<feature-value-name>#)
      auto TryConsumeTerm3 = [&value3](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm3 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // character-variant(<feature-value-name>#)
          auto ConsumeCharacterVariantFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              // <feature-value-name>#
              auto ConsumeUnboundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
                auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                  // <feature-value-name>
                  return ConsumeFeatureValueName(range, state);
                };
                return ConsumeListSeparatedByIntoBuilder<',', ListBounds::MinimumOf(1)>(range, ConsumeRepeatedTerm, state);
              };
              return ConsumeUnboundedRepetition(args, state);
            };
            if (range.Peek().FunctionId() != CSSValueId::CharacterVariant)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::CharacterVariant, Krys::Move(result.value()));
          };
          return ConsumeCharacterVariantFunction(range, state);
        };
        if (value3)
        {
          return false;
        }
        value3 = ConsumeTerm3(range, state);
        return !!value3;
      };
      RefPtr<CSSValue> value4; // swash(<feature-value-name>)
      auto TryConsumeTerm4 = [&value4](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm4 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // swash(<feature-value-name>)
          auto ConsumeSwashFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              auto ConsumeParameter = [](CSSTokenRange &args, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                // <feature-value-name>
                return ConsumeFeatureValueName(args, state);
              };
              auto parameter = ConsumeParameter(args, state);
              if (!parameter)
                return { };
              return CSSValueListBuilder { parameter.releaseNonNull() };
            };
            if (range.Peek().FunctionId() != CSSValueId::Swash)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Swash, Krys::Move(result.value()));
          };
          return ConsumeSwashFunction(range, state);
        };
        if (value4)
        {
          return false;
        }
        value4 = ConsumeTerm4(range, state);
        return !!value4;
      };
      RefPtr<CSSValue> value5; // ornaments(<feature-value-name>)
      auto TryConsumeTerm5 = [&value5](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm5 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // ornaments(<feature-value-name>)
          auto ConsumeOrnamentsFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              auto ConsumeParameter = [](CSSTokenRange &args, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                // <feature-value-name>
                return ConsumeFeatureValueName(args, state);
              };
              auto parameter = ConsumeParameter(args, state);
              if (!parameter)
                return { };
              return CSSValueListBuilder { parameter.releaseNonNull() };
            };
            if (range.Peek().FunctionId() != CSSValueId::Ornaments)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Ornaments, Krys::Move(result.value()));
          };
          return ConsumeOrnamentsFunction(range, state);
        };
        if (value5)
        {
          return false;
        }
        value5 = ConsumeTerm5(range, state);
        return !!value5;
      };
      RefPtr<CSSValue> value6; // annotation(<feature-value-name>)
      auto TryConsumeTerm6 = [&value6](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm6 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // annotation(<feature-value-name>)
          auto ConsumeAnnotationFunction = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
            auto ConsumeParameters = [](CSSTokenRange &args, CSSPropertyParserState &state) -> Maybe<CSSValueListBuilder> {
              auto ConsumeParameter = [](CSSTokenRange &args, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
                // <feature-value-name>
                return ConsumeFeatureValueName(args, state);
              };
              auto parameter = ConsumeParameter(args, state);
              if (!parameter)
                return { };
              return CSSValueListBuilder { parameter.releaseNonNull() };
            };
            if (range.Peek().FunctionId() != CSSValueId::Annotation)
              return { };
            CSSTokenRange rangeCopy = range;
            CSSTokenRange args = ConsumeFunction(rangeCopy);
            auto result = ConsumeParameters(args, state);
            if (!result.has_value())
              return { };
            if (!args.IsAtEnd())
              return { };
            range = rangeCopy;
            return CreateRef<CSSFunctionValue>(CSSValueId::Annotation, Krys::Move(result.value()));
          };
          return ConsumeAnnotationFunction(range, state);
        };
        if (value6)
        {
          return false;
        }
        value6 = ConsumeTerm6(range, state);
        return !!value6;
      };
      for (size_t i = 0uz; i < 7 && !range.IsAtEnd(); ++i)
      {
        if (TryConsumeTerm0(range, state) || TryConsumeTerm1(range) || TryConsumeTerm2(range, state) || TryConsumeTerm3(range, state) || TryConsumeTerm4(range, state) || TryConsumeTerm5(range, state) || TryConsumeTerm6(range, state))
        {
          continue;
        }
        break;
      }
      CSSValueListBuilder list;
      if (value0) // stylistic(<feature-value-name>)
      {
        list.append(value0.releaseNonNull());
      }
      if (value1) // historical-forms
      {
        list.append(value1.releaseNonNull());
      }
      if (value2) // styleset(<feature-value-name>#)
      {
        list.append(value2.releaseNonNull());
      }
      if (value3) // character-variant(<feature-value-name>#)
      {
        list.append(value3.releaseNonNull());
      }
      if (value4) // swash(<feature-value-name>)
      {
        list.append(value4.releaseNonNull());
      }
      if (value5) // ornaments(<feature-value-name>)
      {
        list.append(value5.releaseNonNull());
      }
      if (value6) // annotation(<feature-value-name>)
      {
        list.append(value6.releaseNonNull());
      }
      if (list.IsEmpty())
      {
        return { };
      }
      return CSSValueList::createSpaceSeparated(Krys::Move(list));
    };
    return ConsumeMatchOneOrMoreAnyOrder(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantCaps(CSSTokenRange &range) noexcept
  {
    return ConsumeIdent(range, IsKeywordValidForFontVariantCaps);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantEastAsian(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = ConsumeIdent(range, IsKeywordValidForFontVariantEastAsian))
    {
      return result;
    }
    // [ <east-asian-variant-values> || <east-asian-width-values> || ruby ]@(no-single-item-opt)
    auto ConsumeMatchOneOrMoreAnyOrder = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
    {
      RefPtr<CSSValue> value0; // <east-asian-variant-values>
      auto TryConsumeTerm0 = [&value0](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm0 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // <east-asian-variant-values>
          return ConsumeEastAsianVariantValues(range, state);
        };
        if (value0)
        {
          return false;
        }
        value0 = ConsumeTerm0(range, state);
        return !!value0;
      };
      RefPtr<CSSValue> value1; // <east-asian-width-values>
      auto TryConsumeTerm1 = [&value1](CSSTokenRange &range, CSSPropertyParserState &state) -> bool
      {
        auto ConsumeTerm1 = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue>
        {
          // <east-asian-width-values>
          return ConsumeEastAsianWidthValues(range, state);
        };
        if (value1)
        {
          return false;
        }
        value1 = ConsumeTerm1(range, state);
        return !!value1;
      };
      RefPtr<CSSValue> value2; // ruby
      auto TryConsumeTerm2 = [&value2](CSSTokenRange &range) -> bool
      {
        auto ConsumeTerm2 = [](CSSTokenRange &range) -> RefPtr<CSSValue>
        {
          // ruby
          switch (auto keyword = range.Peek().ValueId(); keyword)
          {
            case CSSValueId::Ruby:
            {
              range.Discard();
              range.DiscardWhitespace();
              return CreateRef<CSSPrimitiveValue>(keyword);
            }
            default:
            {
              return nullptr;
            }
          }
        };
        if (value2)
        {
          return false;
        }
        value2 = ConsumeTerm2(range);
        return !!value2;
      };
      for (size_t i = 0uz; i < 3 && !range.IsAtEnd(); ++i)
      {
        if (TryConsumeTerm0(range, state) || TryConsumeTerm1(range, state) || TryConsumeTerm2(range))
        {
          continue;
        }
        break;
      }
      CSSValueListBuilder list;
      if (value0) // <east-asian-variant-values>
      {
        list.append(value0.releaseNonNull());
      }
      if (value1) // <east-asian-width-values>
      {
        list.append(value1.releaseNonNull());
      }
      if (value2) // ruby
      {
        list.append(value2.releaseNonNull());
      }
      if (list.IsEmpty())
      {
        return { };
      }
      return CSSValueList::createSpaceSeparated(Krys::Move(list));
    };
    return ConsumeMatchOneOrMoreAnyOrder(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantEmoji(CSSTokenRange &range) noexcept
  {
    return ConsumeIdent(range, IsKeywordValidForFontVariantEmoji);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontVariantPosition(CSSTokenRange &range) noexcept
  {
    return ConsumeIdent(range, IsKeywordValidForFontVariantPosition);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeFontWeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // bolder | lighter
    if (auto result = ConsumeIdent(range, IsKeywordValidForFontWeight))
    {
      return result;
    }
    // <font-weight-absolute>
    return ConsumeFontWeightAbsolute(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeBorderImageOutset(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // [ <number [0,inf]> | <length [0,inf]> ]{1,4}@(type=CSSQuadValue no-single-item-opt)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range, CSSPropertyParserState &state) -> RefPtr<CSSValue> {
        // <number [0,inf]>
        if (auto result = CSSPrimitiveValueResolver<Number<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state))
        {
          return result;
        }
        // <length [0,inf]>
        return CSSPrimitiveValueResolver<Length<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.UnitlessZeroLength = AllowUnitlessZero(true)});
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term1) {
        range = rangeCopy;
        return CreateRef<CSSQuadValue>(term0.releaseNonNull());
      }
      auto term2 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term2) {
        range = rangeCopy;
        return CreateRef<CSSQuadValue>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      auto term3 = ConsumeRepeatedTerm(rangeCopy, state);
      if (!term3) {
        range = rangeCopy;
        return CreateRef<CSSQuadValue>(term0.releaseNonNull(), term1.releaseNonNull(), term2.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSQuadValue>(term0.releaseNonNull(), term1.releaseNonNull(), term2.releaseNonNull(), term3.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeBorderImageRepeat(CSSTokenRange &range) noexcept
  {
    // [ stretch | repeat | round | space ]{1,2}@(type=CSSValuePair default=previous)
    auto ConsumeBoundedRepetition = [](CSSTokenRange &range) -> RefPtr<CSSValue> {
      auto ConsumeRepeatedTerm = [](CSSTokenRange &range) -> RefPtr<CSSValue> {
        // stretch | repeat | round | space
        switch (auto keyword = range.Peek().ValueId(); keyword)
        {
          case CSSValueId::Stretch:
          case CSSValueId::Repeat:
          case CSSValueId::Round:
          case CSSValueId::Space:
          {
            range.Discard();
            range.DiscardWhitespace();
            return CreateRef<CSSPrimitiveValue>(keyword);
          }
          default:
          {
            return nullptr;
          }
        }
      };
      CSSTokenRange rangeCopy = range;
      auto term0 = ConsumeRepeatedTerm(rangeCopy);
      if (!term0)
        return { };
      auto term1 = ConsumeRepeatedTerm(rangeCopy);
      if (!term1) {
        term1 = term0;
        range = rangeCopy;
        return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
      }
      range = rangeCopy;
      return CreateRef<CSSValuePair>(term0.releaseNonNull(), term1.releaseNonNull());
    };
    return ConsumeBoundedRepetition(range);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeLineHeight(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // normal
    if (auto result = ConsumeIdent(range, IsKeywordValidForLineHeight))
    {
      return result;
    }
    // <number [0,inf]>
    if (auto result = CSSPrimitiveValueResolver<Number<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state))
    {
      return result;
    }
    // <length-percentage [0,inf]>
    return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
  }

  RefPtr<CSSValue> CSSPropertyParsing::ConsumeCornerStartEndShape(CSSTokenRange &range, CSSPropertyParserState &state) noexcept
  {
    // <corner-shape-value>
    return ConsumeCornerShapeValue(range, state);
  }

  RefPtr<CSSValue> CSSPropertyParsing::ParseStylePropertyLonghand(CSSTokenRange &range, CSSPropertyId id, CSSPropertyParserState &state) noexcept
  {
    if (!IsExposed(id, state.Context.PropertySettings) && !IsInternal(id))
    {
      // Allow internal properties as we use them to parse several internal-only-shorthands (e.g. background-repeat),
      // and to handle certain DOM-exposed values (e.g. -webkit-font-size-delta from execCommand('FontSizeDelta')).
      assert(false);
      return {};
    }
    switch (id)
    {
      case CSSPropertyId::WritingMode:
      {
        return ConsumeIdent(range, IsKeywordValidForWritingMode, state);
      }
      case CSSPropertyId::Direction:
      {
        return ConsumeIdent(range, IsKeywordValidForDirection);
      }
      case CSSPropertyId::Display:
      {
        return ConsumeDisplay(range, state);
      }
      case CSSPropertyId::FontFamily:
      {
        return ConsumeFontFamily(range, state);
      }
      case CSSPropertyId::FontFeatureSettings:
      {
        return CSSPropertyParsing::ConsumeFontFeatureSettings(range, state);
      }
      case CSSPropertyId::FontKerning:
      {
        return ConsumeIdent(range, IsKeywordValidForFontKerning);
      }
      case CSSPropertyId::FontPalette:
      {
        return ConsumeFontPalette(range, state);
      }
      case CSSPropertyId::FontSize:
      {
        return CSSPropertyParsing::ConsumeFontSize(range, state);
      }
      case CSSPropertyId::FontSizeAdjust:
      {
        return ConsumeFontSizeAdjust(range, state);
      }
      case CSSPropertyId::FontStyle:
      {
        return ConsumeFontStyle(range, state);
      }
      case CSSPropertyId::FontSynthesisSmallCaps:
      {
        return ConsumeIdent(range, IsKeywordValidForFontSynthesisSmallCaps);
      }
      case CSSPropertyId::FontSynthesisStyle:
      {
        return ConsumeIdent(range, IsKeywordValidForFontSynthesisStyle);
      }
      case CSSPropertyId::FontSynthesisWeight:
      {
        return ConsumeIdent(range, IsKeywordValidForFontSynthesisWeight);
      }
      case CSSPropertyId::FontVariantAlternates:
      {
        return CSSPropertyParsing::ConsumeFontVariantAlternates(range, state);
      }
      case CSSPropertyId::FontVariantCaps:
      {
        return ConsumeIdent(range, IsKeywordValidForFontVariantCaps);
      }
      case CSSPropertyId::FontVariantEastAsian:
      {
        return CSSPropertyParsing::ConsumeFontVariantEastAsian(range, state);
      }
      case CSSPropertyId::FontVariantEmoji:
      {
        return ConsumeIdent(range, IsKeywordValidForFontVariantEmoji);
      }
      case CSSPropertyId::FontVariantLigatures:
      {
        return ConsumeFontVariantLigatures(range, state);
      }
      case CSSPropertyId::FontVariantNumeric:
      {
        return ConsumeFontVariantNumeric(range, state);
      }
      case CSSPropertyId::FontVariantPosition:
      {
        return ConsumeIdent(range, IsKeywordValidForFontVariantPosition);
      }
      case CSSPropertyId::FontWeight:
      {
        return CSSPropertyParsing::ConsumeFontWeight(range, state);
      }
      case CSSPropertyId::FontWidth:
      {
        return ConsumeFontWidthAbsolute(range, state);
      }
      case CSSPropertyId::BackgroundImage:
      {
        return ConsumeBackgroundImage(range, state);
      }
      case CSSPropertyId::AnimationComposition:
      {
        return ConsumeAnimationComposition(range, state);
      }
      case CSSPropertyId::AnimationDelay:
      {
        return ConsumeAnimationDelay(range, state);
      }
      case CSSPropertyId::AnimationDirection:
      {
        return ConsumeAnimationDirection(range, state);
      }
      case CSSPropertyId::AnimationDuration:
      {
        return ConsumeAnimationDuration(range, state);
      }
      case CSSPropertyId::AnimationFillMode:
      {
        return ConsumeAnimationFillMode(range, state);
      }
      case CSSPropertyId::AnimationIterationCount:
      {
        return ConsumeAnimationIterationCount(range, state);
      }
      case CSSPropertyId::AnimationName:
      {
        return ConsumeAnimationName(range, state);
      }
      case CSSPropertyId::AnimationPlayState:
      {
        return ConsumeAnimationPlayState(range, state);
      }
      case CSSPropertyId::AnimationRangeEnd:
      {
        return ConsumeAnimationRangeEnd(range, state);
      }
      case CSSPropertyId::AnimationRangeStart:
      {
        return ConsumeAnimationRangeStart(range, state);
      }
      case CSSPropertyId::AnimationTimeline:
      {
        return ConsumeAnimationTimeline(range, state);
      }
      case CSSPropertyId::AnimationTimingFunction:
      {
        return ConsumeAnimationTimingFunction(range, state);
      }
      case CSSPropertyId::BorderCollapse:
      {
        return ConsumeIdent(range, IsKeywordValidForBorderCollapse);
      }
      case CSSPropertyId::BorderImageOutset:
      {
        return CSSPropertyParsing::ConsumeBorderImageOutset(range, state);
      }
      case CSSPropertyId::BorderImageRepeat:
      {
        return CSSPropertyParsing::ConsumeBorderImageRepeat(range);
      }
      case CSSPropertyId::BorderImageSlice:
      {
        return ConsumeBorderImageSlice(range, state);
      }
      case CSSPropertyId::BorderImageSource:
      {
        return ConsumeBorderImageSource(range, state);
      }
      case CSSPropertyId::BorderImageWidth:
      {
        return ConsumeBorderImageWidth(range, state);
      }
      case CSSPropertyId::Color:
      case CSSPropertyId::BorderBottomColor:
      case CSSPropertyId::BorderLeftColor:
      case CSSPropertyId::BorderRightColor:
      case CSSPropertyId::BorderTopColor:
      case CSSPropertyId::BorderBlockEndColor:
      case CSSPropertyId::BorderBlockStartColor:
      case CSSPropertyId::BorderInlineEndColor:
      case CSSPropertyId::BorderInlineStartColor:
      {
        return ConsumeColor(range, state, {.AllowedColorTypes = { CSSColorType::Absolute, CSSColorType::Current, CSSColorType::System } });
      }
      case CSSPropertyId::D:
      {
        return ConsumeD(range, state);
      }
      case CSSPropertyId::LineHeight:
      {
        return CSSPropertyParsing::ConsumeLineHeight(range, state);
      }
      case CSSPropertyId::MarginTrim:
      {
        return ConsumeMarginTrim(range, state);
      }
      case CSSPropertyId::BorderBottomLeftRadius:
      {
        return ConsumeBorderBottomLeftRadius(range, state);
      }
      case CSSPropertyId::BorderBottomRightRadius:
      {
        return ConsumeBorderBottomRightRadius(range, state);
      }
      case CSSPropertyId::BorderBottomStyle:
      case CSSPropertyId::BorderLeftStyle:
      case CSSPropertyId::BorderRightStyle:
      case CSSPropertyId::BorderTopStyle:
      case CSSPropertyId::BorderBlockEndStyle:
      case CSSPropertyId::BorderBlockStartStyle:
      case CSSPropertyId::BorderInlineEndStyle:
      case CSSPropertyId::BorderInlineStartStyle:
      {
        return ConsumeLineStyle(range, state);
      }
      case CSSPropertyId::BorderBottomWidth:
      case CSSPropertyId::BorderLeftWidth:
      case CSSPropertyId::BorderRightWidth:
      case CSSPropertyId::BorderTopWidth:
      case CSSPropertyId::BorderBlockEndWidth:
      case CSSPropertyId::BorderBlockStartWidth:
      case CSSPropertyId::BorderInlineEndWidth:
      case CSSPropertyId::BorderInlineStartWidth:
      {
        return ConsumeLineWidth(range, state);
      }
      case CSSPropertyId::BorderTopLeftRadius:
      {
        return ConsumeBorderTopLeftRadius(range, state);
      }
      case CSSPropertyId::BorderTopRightRadius:
      {
        return ConsumeBorderTopRightRadius(range, state);
      }
      case CSSPropertyId::CornerBottomLeftShape:
      case CSSPropertyId::CornerBottomRightShape:
      case CSSPropertyId::CornerTopLeftShape:
      case CSSPropertyId::CornerTopRightShape:
      case CSSPropertyId::CornerEndEndShape:
      case CSSPropertyId::CornerEndStartShape:
      case CSSPropertyId::CornerStartEndShape:
      case CSSPropertyId::CornerStartStartShape:
      {
        return ConsumeCornerShapeValue(range, state);
      }
      case CSSPropertyId::MarginBottom:
      {
        return ConsumeMarginBottom(range, state);
      }
      case CSSPropertyId::MarginLeft:
      {
        return ConsumeMarginLeft(range, state);
      }
      case CSSPropertyId::MarginRight:
      {
        return ConsumeMarginRight(range, state);
      }
      case CSSPropertyId::MarginTop:
      {
        return ConsumeMarginTop(range, state);
      }
      case CSSPropertyId::PaddingBottom:
      case CSSPropertyId::PaddingLeft:
      case CSSPropertyId::PaddingRight:
      case CSSPropertyId::PaddingTop:
      case CSSPropertyId::PaddingBlockEnd:
      case CSSPropertyId::PaddingBlockStart:
      case CSSPropertyId::PaddingInlineEnd:
      case CSSPropertyId::PaddingInlineStart:
      {
        return CSSPrimitiveValueResolver<LengthPercentage<CSS::Range{0, CSS::Range::infinity}>>::ConsumeAndResolve(range, state, {.AnchorPolicy = AllowAnchor(false), .AnchorSizePolicy = AllowAnchorSize(false), .UnitlessZeroLength = AllowUnitlessZero(true)});
      }
      case CSSPropertyId::BorderEndEndRadius:
      {
        return ConsumeBorderEndEndRadius(range, state);
      }
      case CSSPropertyId::BorderEndStartRadius:
      {
        return ConsumeBorderEndStartRadius(range, state);
      }
      case CSSPropertyId::BorderStartEndRadius:
      {
        return ConsumeBorderStartEndRadius(range, state);
      }
      case CSSPropertyId::BorderStartStartRadius:
      {
        return ConsumeBorderStartStartRadius(range, state);
      }
      case CSSPropertyId::MarginBlockEnd:
      case CSSPropertyId::MarginBlockStart:
      case CSSPropertyId::MarginInlineEnd:
      case CSSPropertyId::MarginInlineStart:
      {
        return ConsumeMarginLogical(range, state);
      }
      default:
      {
        return {};
      }
    }
  }

  bool CSSPropertyParsing::ParseStylePropertyShorthand(CSSTokenRange &range, CSSPropertyId id, CSSPropertyParserState &state, CSSPropertyParserResult &result) noexcept
  {
    assert(IsShorthand(id));

    switch (id)
    {
      case CSSPropertyId::Animation:
      {
        return CSSPropertyParserCustom::ConsumeAnimationShorthand(range, state, AnimationShorthand(), result);
      }
      case CSSPropertyId::AnimationRange:
      {
        if (!state.Context.PropertySettings.ScrollDrivenAnimationsEnabled)
        {
          assert(false);
          return false;
        }
        return CSSPropertyParserCustom::ConsumeAnimationRangeShorthand(range, state, AnimationRangeShorthand(), result);
      }
      case CSSPropertyId::Border:
      {
        return CSSPropertyParserCustom::ConsumeBorderShorthand(range, state, BorderShorthand(), result);
      }
      case CSSPropertyId::BorderBlock:
      {
        return CSSPropertyParserCustom::ConsumeBorderBlockShorthand(range, state, BorderBlockShorthand(), result);
      }
      case CSSPropertyId::BorderBlockColor:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, BorderBlockColorShorthand(), result);
      }
      case CSSPropertyId::BorderBlockEnd:
      {
        return CSSPropertyParserCustom::ConsumeStandardSpaceSeparatedShorthand(range, state, BorderBlockEndShorthand(), result);
      }
      case CSSPropertyId::BorderBlockStart:
      {
        return CSSPropertyParserCustom::ConsumeStandardSpaceSeparatedShorthand(range, state, BorderBlockStartShorthand(), result);
      }
      case CSSPropertyId::BorderBlockStyle:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, BorderBlockStyleShorthand(), result);
      }
      case CSSPropertyId::BorderBlockWidth:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, BorderBlockWidthShorthand(), result);
      }
      case CSSPropertyId::BorderBottom:
      {
        return CSSPropertyParserCustom::ConsumeStandardSpaceSeparatedShorthand(range, state, BorderBottomShorthand(), result);
      }
      case CSSPropertyId::BorderColor:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingQuadShorthand(range, state, BorderColorShorthand(), result);
      }
      case CSSPropertyId::BorderImage:
      {
        return CSSPropertyParserCustom::ConsumeBorderImageShorthand(range, state, BorderImageShorthand(), result);
      }
      case CSSPropertyId::BorderInline:
      {
        return CSSPropertyParserCustom::ConsumeBorderInlineShorthand(range, state, BorderInlineShorthand(), result);
      }
      case CSSPropertyId::BorderInlineColor:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, BorderInlineColorShorthand(), result);
      }
      case CSSPropertyId::BorderInlineEnd:
      {
        return CSSPropertyParserCustom::ConsumeStandardSpaceSeparatedShorthand(range, state, BorderInlineEndShorthand(), result);
      }
      case CSSPropertyId::BorderInlineStart:
      {
        return CSSPropertyParserCustom::ConsumeStandardSpaceSeparatedShorthand(range, state, BorderInlineStartShorthand(), result);
      }
      case CSSPropertyId::BorderInlineStyle:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, BorderInlineStyleShorthand(), result);
      }
      case CSSPropertyId::BorderInlineWidth:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, BorderInlineWidthShorthand(), result);
      }
      case CSSPropertyId::BorderLeft:
      {
        return CSSPropertyParserCustom::ConsumeStandardSpaceSeparatedShorthand(range, state, BorderLeftShorthand(), result);
      }
      case CSSPropertyId::BorderRadius:
      {
        return CSSPropertyParserCustom::ConsumeBorderRadiusShorthand(range, state, BorderRadiusShorthand(), result);
      }
      case CSSPropertyId::BorderRight:
      {
        return CSSPropertyParserCustom::ConsumeStandardSpaceSeparatedShorthand(range, state, BorderRightShorthand(), result);
      }
      case CSSPropertyId::BorderStyle:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingQuadShorthand(range, state, BorderStyleShorthand(), result);
      }
      case CSSPropertyId::BorderTop:
      {
        return CSSPropertyParserCustom::ConsumeStandardSpaceSeparatedShorthand(range, state, BorderTopShorthand(), result);
      }
      case CSSPropertyId::BorderWidth:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingQuadShorthand(range, state, BorderWidthShorthand(), result);
      }
      case CSSPropertyId::CornerShape:
      {
        if (!state.Context.PropertySettings.CornerShapePropertyEnabled)
        {
          assert(false);
          return false;
        }
        return CSSPropertyParserCustom::ConsumeCoalescingQuadShorthand(range, state, CornerShapeShorthand(), result);
      }
      case CSSPropertyId::Font:
      {
        return CSSPropertyParserCustom::ConsumeFontShorthand(range, state, FontShorthand(), result);
      }
      case CSSPropertyId::FontSynthesis:
      {
        return CSSPropertyParserCustom::ConsumeFontSynthesisShorthand(range, state, FontSynthesisShorthand(), result);
      }
      case CSSPropertyId::FontVariant:
      {
        return CSSPropertyParserCustom::ConsumeFontVariantShorthand(range, state, FontVariantShorthand(), result);
      }
      case CSSPropertyId::Margin:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingQuadShorthand(range, state, MarginShorthand(), result);
      }
      case CSSPropertyId::MarginBlock:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, MarginBlockShorthand(), result);
      }
      case CSSPropertyId::MarginInline:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, MarginInlineShorthand(), result);
      }
      case CSSPropertyId::Padding:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingQuadShorthand(range, state, PaddingShorthand(), result);
      }
      case CSSPropertyId::PaddingBlock:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, PaddingBlockShorthand(), result);
      }
      case CSSPropertyId::PaddingInline:
      {
        return CSSPropertyParserCustom::ConsumeCoalescingPairShorthand(range, state, PaddingInlineShorthand(), result);
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSPropertyParsing::IsKeywordValidForStyleProperty(CSSPropertyId id, CSSValueId keyword, CSSPropertyParserState & state) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::WritingMode:
      {
        return IsKeywordValidForWritingMode(keyword, state);
      }
      case CSSPropertyId::Direction:
      {
        return IsKeywordValidForDirection(keyword);
      }
      case CSSPropertyId::FontFeatureSettings:
      {
        return IsKeywordValidForFontFeatureSettings(keyword);
      }
      case CSSPropertyId::FontKerning:
      {
        return IsKeywordValidForFontKerning(keyword);
      }
      case CSSPropertyId::FontPalette:
      {
        return IsKeywordValidForFontPalette(keyword);
      }
      case CSSPropertyId::FontSize:
      {
        return IsKeywordValidForFontSize(keyword, state);
      }
      case CSSPropertyId::FontSynthesisSmallCaps:
      {
        return IsKeywordValidForFontSynthesisSmallCaps(keyword);
      }
      case CSSPropertyId::FontSynthesisStyle:
      {
        return IsKeywordValidForFontSynthesisStyle(keyword);
      }
      case CSSPropertyId::FontSynthesisWeight:
      {
        return IsKeywordValidForFontSynthesisWeight(keyword);
      }
      case CSSPropertyId::FontVariantAlternates:
      {
        return IsKeywordValidForFontVariantAlternates(keyword);
      }
      case CSSPropertyId::FontVariantCaps:
      {
        return IsKeywordValidForFontVariantCaps(keyword);
      }
      case CSSPropertyId::FontVariantEastAsian:
      {
        return IsKeywordValidForFontVariantEastAsian(keyword);
      }
      case CSSPropertyId::FontVariantEmoji:
      {
        return IsKeywordValidForFontVariantEmoji(keyword);
      }
      case CSSPropertyId::FontVariantLigatures:
      {
        return IsKeywordValidForFontVariantLigatures(keyword);
      }
      case CSSPropertyId::FontVariantNumeric:
      {
        return IsKeywordValidForFontVariantNumeric(keyword);
      }
      case CSSPropertyId::FontVariantPosition:
      {
        return IsKeywordValidForFontVariantPosition(keyword);
      }
      case CSSPropertyId::FontWeight:
      {
        return IsKeywordValidForFontWeight(keyword);
      }
      case CSSPropertyId::BorderCollapse:
      {
        return IsKeywordValidForBorderCollapse(keyword);
      }
      case CSSPropertyId::BorderImageSource:
      {
        return IsKeywordValidForBorderImageSource(keyword);
      }
      case CSSPropertyId::D:
      {
        return IsKeywordValidForD(keyword);
      }
      case CSSPropertyId::LineHeight:
      {
        return IsKeywordValidForLineHeight(keyword);
      }
      case CSSPropertyId::MarginBottom:
      {
        return IsKeywordValidForMarginBottom(keyword);
      }
      case CSSPropertyId::MarginLeft:
      {
        return IsKeywordValidForMarginLeft(keyword);
      }
      case CSSPropertyId::MarginRight:
      {
        return IsKeywordValidForMarginRight(keyword);
      }
      case CSSPropertyId::MarginTop:
      {
        return IsKeywordValidForMarginTop(keyword);
      }
      default:
      {
        return false;
      }
    }
  }

  bool CSSPropertyParsing::IsKeywordFastPathEligibleStyleProperty(CSSPropertyId id) noexcept
  {
    switch (id)
    {
      case CSSPropertyId::WritingMode:
      case CSSPropertyId::Direction:
      case CSSPropertyId::FontFeatureSettings:
      case CSSPropertyId::FontKerning:
      case CSSPropertyId::FontPalette:
      case CSSPropertyId::FontSize:
      case CSSPropertyId::FontSynthesisSmallCaps:
      case CSSPropertyId::FontSynthesisStyle:
      case CSSPropertyId::FontSynthesisWeight:
      case CSSPropertyId::FontVariantAlternates:
      case CSSPropertyId::FontVariantCaps:
      case CSSPropertyId::FontVariantEastAsian:
      case CSSPropertyId::FontVariantEmoji:
      case CSSPropertyId::FontVariantLigatures:
      case CSSPropertyId::FontVariantNumeric:
      case CSSPropertyId::FontVariantPosition:
      case CSSPropertyId::FontWeight:
      case CSSPropertyId::BorderCollapse:
      case CSSPropertyId::BorderImageSource:
      case CSSPropertyId::D:
      case CSSPropertyId::LineHeight:
      case CSSPropertyId::MarginBottom:
      case CSSPropertyId::MarginLeft:
      case CSSPropertyId::MarginRight:
      case CSSPropertyId::MarginTop:
      {
        return true;
      }
      default:
      {
        return false;
      }
    }
  }

}
