import textwrap
from typing import Iterable
from utils import time_stamp


class Writer:
    TAB_SIZE = 2

    def __init__(self, output):
        self.output = output
        self._indentation_level = 0
        self._time_stamp = time_stamp()

    @property
    def _current_indent(self):
        return (self._indentation_level * Writer.TAB_SIZE) * " "

    def write(self, text: str):
        self.output.write(self._current_indent)
        self.output.write(text)
        return self.newline()

    def write_if(self, condition: bool, text: str):
        if condition:
            self.write(text)
        return self

    def write_block(self, text: str):
        self.output.write(textwrap.indent(textwrap.dedent(text), self._current_indent))
        return self.newline()

    def write_lines(self, iterable: Iterable[str]):
        for line in iterable:
            self.write(line)
        return self

    def write_using_namespace_declarations(self, *, namespaces: list[str]):
        for namespace in namespaces:
            self.write(f"using namespace {namespace};")
        self.newline()

    def write_forward_declarations(
        self, *, structs: list[str] = [], classes: list[str] = [], namespace: str | None = None
    ):
        if namespace:
            self.write(f"namespace {namespace}")
            self.write("{")
            self._indentation_level += 1

        for structName in structs:
            self.write(f"struct {structName};")
        for className in classes:
            self.write(f"class {className};")
        self.newline()

        if namespace:
            self._indentation_level -= 1
            self.write("}")

    def write_autogenerated_heading(self, *, generator_name: str):
        """Adds the standard auto-generated heading to the top of a generated file."""
        self.write(
            f"// <auto-generated>\n"
            f"//   Generated at {self._time_stamp} by {generator_name}.py\n"
            f"//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is\n"
            f"//   regenerated.\n"
            f"// </auto-generated>"
        )

    def write_header_pragma_once(self):
        self.write("#pragma once")
        self.newline()

    def write_includes(self, *, headers: list[str] = [], system_headers: list[str] = []):
        if headers:
            for header in headers:
                self.write(f'#include "{header}"')
            self.newline()

        if system_headers:
            for header in system_headers:
                self.write(f"#include <{header}>")
            self.newline()

    def write_hpp_prelude(self, *, generator_name: str, headers: list[str] = [], system_headers: list[str] = []):
        self.write_autogenerated_heading(generator_name=generator_name)
        self.write_header_pragma_once()
        self.write_includes(headers=headers, system_headers=system_headers)

    def write_cpp_prelude(
        self, *, generator_name: str, for_header: str, headers: list[str] = [], system_headers: list[str] = []
    ):
        self.write_autogenerated_heading(generator_name=generator_name)
        self.write_includes(headers=[for_header] + headers, system_headers=system_headers)

    def newline(self):
        self.output.write("\n")
        return self

    class Block:
        def __init__(
            self, *, to: Writer, prologue: str = "", epilogue: str = "", block_start: str = "{", block_end: str = "}"
        ):
            self.to = to
            self.prologue = prologue
            self.epilogue = epilogue
            self.block_start = block_start
            self.block_end = block_end

        def __enter__(self):
            if self.prologue:
                self.to.write(self.prologue)

            if self.block_start:
                self.to.write(self.block_start)

            self.to._indentation_level += 1

        def __exit__(self, exc_type, exc_value, traceback):
            self.to._indentation_level -= 1

            if self.block_end:
                self.to.write(self.block_end)

            if self.epilogue:
                self.to.write(self.epilogue)

    def block(self, *, prologue: str = "", epilogue: str = "", block_start: str = "{", block_end: str = "}"):
        return Writer.Block(to=self, prologue=prologue, epilogue=epilogue, block_start=block_start, block_end=block_end)

    class Namespace:
        def __init__(self, *, to: Writer, namespace: str):
            self.to = to
            self.namespace = namespace

        def __enter__(self):
            if not self.namespace:
                self.to.write("namespace")
            else:
                self.to.write(f"namespace {self.namespace}")

            self.to.write("{")
            self.to._indentation_level += 1

        def __exit__(self, exc_type, exc_value, traceback):
            self.to._indentation_level -= 1
            self.to.write("}")

    def namespace(self, *, namespace: str):
        return Writer.Namespace(to=self, namespace=namespace)

    def indent(self):
        return Writer.Block(to=self, prologue="", block_start="", block_end="")

    def function_block(self, *, signature: str):
        return Writer.Block(to=self, prologue=signature)

    def switch_block(self, *, expr: str):
        return Writer.Block(to=self, prologue=f"switch ({expr})")

    def case_block(self, *, case: str):
        return Writer.Block(to=self, prologue=f"case {case}:")

    def multi_case_block(self, *, cases: list[str]):
        prologue = "\n".join(f"case {case}:" for case in cases)
        return Writer.Block(to=self, prologue=prologue)

    def default_case_block(self):
        return Writer.Block(to=self, prologue="default:")

    def struct_block(self, *, name: str):
        return Writer.Block(to=self, prologue=f"struct {name}", block_end="};")

    def class_block(self, *, name: str):
        return Writer.Block(to=self, prologue=f"class {name}", block_end="};")
