// <auto-generated>
//   Generated at 2026-09-13 18:16:22 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.Booey/CSS/Properties/PropertyId.hpp"
#include "Krystal.Booey/CSS/Values/CSSUnits.hpp"
#include "Krystal.Booey/CSS/Values/ValueId.hpp"
#include "Krystal.Core/Base.hpp"
#include "Krystal.Core/Types/Variant.hpp"

namespace krys::boo::css
{
  struct InitialNumericValue
  {
    double Number;
    CSSUnitType Type { CSSUnitType::Number };
  };

  using InitialValue = Variant<ValueId, InitialNumericValue>;

  // Skipping PropertyId::FontFamily, initial is a special value [SpecialLiteral @initial-font-family]
  // Skipping PropertyId::ObjectPosition, initial is a list with multiple values [NumericLiteral 50%, NumericLiteral 50%]
  // Skipping PropertyId::TextEmphasisPosition, initial is a list with multiple values [over, right]
  // Skipping PropertyId::WebkitLineBoxContain, initial is a list with multiple values [block, inline, replaced]
  KRYS_NODISCARD constexpr static InitialValue InitialValueForLonghand(PropertyId longhand) noexcept
  {
    switch (longhand)
    {
      case PropertyId::BorderImageOutset:
      case PropertyId::FlexGrow:
      case PropertyId::MaskBorderOutset:
      case PropertyId::MaskBorderSlice:
      case PropertyId::MathDepth:
      case PropertyId::Order:
      case PropertyId::Page:
      case PropertyId::ShapeImageThreshold:
      case PropertyId::StrokeDashoffset:
      {
        return InitialNumericValue {0, CSSUnitType::Number};
      }
      case PropertyId::RubyPosition:
      {
        return ValueId::Over;
      }
      case PropertyId::WritingMode:
      {
        return ValueId::HorizontalTb;
      }
      case PropertyId::Direction:
      {
        return ValueId::Ltr;
      }
      case PropertyId::Display:
      {
        return ValueId::Inline;
      }
      case PropertyId::AlignContent:
      case PropertyId::AlignItems:
      case PropertyId::AnimationDirection:
      case PropertyId::AnimationRangeEnd:
      case PropertyId::AnimationRangeStart:
      case PropertyId::BackgroundBlendMode:
      case PropertyId::ColumnGap:
      case PropertyId::ContainerType:
      case PropertyId::Content:
      case PropertyId::FontFeatureSettings:
      case PropertyId::FontPalette:
      case PropertyId::FontStyle:
      case PropertyId::FontVariantAlternates:
      case PropertyId::FontVariantCaps:
      case PropertyId::FontVariantEastAsian:
      case PropertyId::FontVariantEmoji:
      case PropertyId::FontVariantLigatures:
      case PropertyId::FontVariantNumeric:
      case PropertyId::FontVariantPosition:
      case PropertyId::FontWeight:
      case PropertyId::FontWidth:
      case PropertyId::GridAutoFlow:
      case PropertyId::ItemTolerance:
      case PropertyId::JustifyContent:
      case PropertyId::LetterSpacing:
      case PropertyId::LineHeight:
      case PropertyId::MathShift:
      case PropertyId::MathStyle:
      case PropertyId::MixBlendMode:
      case PropertyId::OffsetPosition:
      case PropertyId::OverflowWrap:
      case PropertyId::PaintOrder:
      case PropertyId::PositionTryOrder:
      case PropertyId::RowGap:
      case PropertyId::ScrollSnapStop:
      case PropertyId::SpeakAs:
      case PropertyId::TransitionBehavior:
      case PropertyId::UnicodeBidi:
      case PropertyId::WebkitColumnProgression:
      case PropertyId::WebkitInitialLetter:
      case PropertyId::WordBreak:
      case PropertyId::WordSpacing:
      {
        return ValueId::Normal;
      }
      case PropertyId::AccentColor:
      case PropertyId::AlignSelf:
      case PropertyId::AnimationDuration:
      case PropertyId::AnimationTimeline:
      case PropertyId::AspectRatio:
      case PropertyId::BackgroundSize:
      case PropertyId::BlockSize:
      case PropertyId::BlockStepAlign:
      case PropertyId::Bottom:
      case PropertyId::BreakAfter:
      case PropertyId::BreakBefore:
      case PropertyId::BreakInside:
      case PropertyId::BufferedRendering:
      case PropertyId::CaretColor:
      case PropertyId::Clip:
      case PropertyId::ColumnCount:
      case PropertyId::ColumnWidth:
      case PropertyId::Continue:
      case PropertyId::Cursor:
      case PropertyId::DominantBaseline:
      case PropertyId::FlexBasis:
      case PropertyId::FontKerning:
      case PropertyId::FontSynthesisSmallCaps:
      case PropertyId::FontSynthesisStyle:
      case PropertyId::FontSynthesisWeight:
      case PropertyId::GlyphOrientationVertical:
      case PropertyId::GridAutoColumns:
      case PropertyId::GridAutoRows:
      case PropertyId::GridColumnEnd:
      case PropertyId::GridColumnStart:
      case PropertyId::GridRowEnd:
      case PropertyId::GridRowStart:
      case PropertyId::Height:
      case PropertyId::HyphenateCharacter:
      case PropertyId::ImageRendering:
      case PropertyId::InlineSize:
      case PropertyId::InputSecurity:
      case PropertyId::InsetBlockEnd:
      case PropertyId::InsetBlockStart:
      case PropertyId::InsetInlineEnd:
      case PropertyId::InsetInlineStart:
      case PropertyId::Isolation:
      case PropertyId::JustifySelf:
      case PropertyId::Left:
      case PropertyId::LineBreak:
      case PropertyId::MaskBorderWidth:
      case PropertyId::MaskSize:
      case PropertyId::MinHeight:
      case PropertyId::MinWidth:
      case PropertyId::OffsetAnchor:
      case PropertyId::OffsetRotate:
      case PropertyId::Orphans:
      case PropertyId::OverflowAnchor:
      case PropertyId::OverscrollBehaviorBlock:
      case PropertyId::OverscrollBehaviorInline:
      case PropertyId::OverscrollBehaviorX:
      case PropertyId::OverscrollBehaviorY:
      case PropertyId::PointerEvents:
      case PropertyId::PositionAnchor:
      case PropertyId::Quotes:
      case PropertyId::Right:
      case PropertyId::RubyOverhang:
      case PropertyId::Rx:
      case PropertyId::Ry:
      case PropertyId::ScrollBehavior:
      case PropertyId::ScrollPaddingBlockEnd:
      case PropertyId::ScrollPaddingBlockStart:
      case PropertyId::ScrollPaddingBottom:
      case PropertyId::ScrollPaddingInlineEnd:
      case PropertyId::ScrollPaddingInlineStart:
      case PropertyId::ScrollPaddingLeft:
      case PropertyId::ScrollPaddingRight:
      case PropertyId::ScrollPaddingTop:
      case PropertyId::ScrollbarColor:
      case PropertyId::ScrollbarGutter:
      case PropertyId::ScrollbarWidth:
      case PropertyId::ShapeRendering:
      case PropertyId::TableLayout:
      case PropertyId::TextAlignLast:
      case PropertyId::TextBoxEdge:
      case PropertyId::TextDecorationSkipInk:
      case PropertyId::TextDecorationThickness:
      case PropertyId::TextJustify:
      case PropertyId::TextRendering:
      case PropertyId::TextUnderlineOffset:
      case PropertyId::TextUnderlinePosition:
      case PropertyId::TextWrapStyle:
      case PropertyId::Top:
      case PropertyId::TouchAction:
      case PropertyId::ViewTimelineInset:
      case PropertyId::WebkitFontSmoothing:
      case PropertyId::WebkitHyphenateLimitAfter:
      case PropertyId::WebkitHyphenateLimitBefore:
      case PropertyId::WebkitLocale:
      case PropertyId::WebkitUserDrag:
      case PropertyId::Widows:
      case PropertyId::Width:
      case PropertyId::WillChange:
      case PropertyId::ZIndex:
      {
        return ValueId::Auto;
      }
      case PropertyId::BorderBlockEndWidth:
      case PropertyId::BorderBlockStartWidth:
      case PropertyId::BorderBottomWidth:
      case PropertyId::BorderInlineEndWidth:
      case PropertyId::BorderInlineStartWidth:
      case PropertyId::BorderLeftWidth:
      case PropertyId::BorderRightWidth:
      case PropertyId::BorderTopWidth:
      case PropertyId::ColumnRuleWidth:
      case PropertyId::FontSize:
      case PropertyId::OutlineWidth:
      {
        return ValueId::Medium;
      }
      case PropertyId::AnchorName:
      case PropertyId::AnchorScope:
      case PropertyId::AnimationFillMode:
      case PropertyId::AnimationName:
      case PropertyId::Appearance:
      case PropertyId::AppleColorFilter:
      case PropertyId::BackdropFilter:
      case PropertyId::BackgroundImage:
      case PropertyId::BlockEllipsis:
      case PropertyId::BlockStepSize:
      case PropertyId::BorderBlockEndStyle:
      case PropertyId::BorderBlockStartStyle:
      case PropertyId::BorderBottomStyle:
      case PropertyId::BorderImageSource:
      case PropertyId::BorderInlineEndStyle:
      case PropertyId::BorderInlineStartStyle:
      case PropertyId::BorderLeftStyle:
      case PropertyId::BorderRightStyle:
      case PropertyId::BorderTopStyle:
      case PropertyId::BoxShadow:
      case PropertyId::Clear:
      case PropertyId::ClipPath:
      case PropertyId::ColumnRuleStyle:
      case PropertyId::ColumnSpan:
      case PropertyId::Contain:
      case PropertyId::ContainIntrinsicBlockSize:
      case PropertyId::ContainIntrinsicHeight:
      case PropertyId::ContainIntrinsicInlineSize:
      case PropertyId::ContainIntrinsicWidth:
      case PropertyId::ContainerName:
      case PropertyId::CounterIncrement:
      case PropertyId::CounterReset:
      case PropertyId::CounterSet:
      case PropertyId::D:
      case PropertyId::Filter:
      case PropertyId::Float:
      case PropertyId::FontSizeAdjust:
      case PropertyId::GridTemplateAreas:
      case PropertyId::GridTemplateColumns:
      case PropertyId::GridTemplateRows:
      case PropertyId::HangingPunctuation:
      case PropertyId::ListStyleImage:
      case PropertyId::MarginTrim:
      case PropertyId::MarkerEnd:
      case PropertyId::MarkerMid:
      case PropertyId::MarkerStart:
      case PropertyId::MaskBorderSource:
      case PropertyId::MaskImage:
      case PropertyId::MaxBlockSize:
      case PropertyId::MaxHeight:
      case PropertyId::MaxInlineSize:
      case PropertyId::MaxLines:
      case PropertyId::MaxWidth:
      case PropertyId::OffsetPath:
      case PropertyId::OutlineStyle:
      case PropertyId::Perspective:
      case PropertyId::PositionArea:
      case PropertyId::PositionTryFallbacks:
      case PropertyId::Resize:
      case PropertyId::Rotate:
      case PropertyId::Scale:
      case PropertyId::ScrollSnapAlign:
      case PropertyId::ScrollSnapType:
      case PropertyId::ScrollTimelineName:
      case PropertyId::ShapeOutside:
      case PropertyId::Stroke:
      case PropertyId::StrokeDasharray:
      case PropertyId::TextBoxTrim:
      case PropertyId::TextCombineUpright:
      case PropertyId::TextDecorationLine:
      case PropertyId::TextEmphasisStyle:
      case PropertyId::TextGroupAlign:
      case PropertyId::TextShadow:
      case PropertyId::TextTransform:
      case PropertyId::TimelineScope:
      case PropertyId::Transform:
      case PropertyId::Translate:
      case PropertyId::VectorEffect:
      case PropertyId::ViewTimelineName:
      case PropertyId::ViewTransitionClass:
      case PropertyId::ViewTransitionName:
      case PropertyId::WebkitLineAlign:
      case PropertyId::WebkitTextCombine:
      case PropertyId::WebkitTextDecorationsInEffect:
      case PropertyId::WebkitTextSecurity:
      {
        return ValueId::None;
      }
      case PropertyId::TextOrientation:
      {
        return ValueId::Mixed;
      }
      case PropertyId::AnimationIterationCount:
      case PropertyId::BorderImageWidth:
      case PropertyId::FillOpacity:
      case PropertyId::FlexShrink:
      case PropertyId::FloodOpacity:
      case PropertyId::Opacity:
      case PropertyId::StopOpacity:
      case PropertyId::StrokeOpacity:
      case PropertyId::Zoom:
      {
        return InitialNumericValue {1, CSSUnitType::Number};
      }
      case PropertyId::TextAutospace:
      {
        return ValueId::NoAutospace;
      }
      case PropertyId::TextSpacingTrim:
      {
        return ValueId::SpaceAll;
      }
      case PropertyId::AlignmentBaseline:
      case PropertyId::BaselineShift:
      case PropertyId::VerticalAlign:
      {
        return ValueId::Baseline;
      }
      case PropertyId::AnimationComposition:
      {
        return ValueId::Replace;
      }
      case PropertyId::AnimationDelay:
      case PropertyId::TransitionDelay:
      case PropertyId::TransitionDuration:
      {
        return InitialNumericValue {0, CSSUnitType::s};
      }
      case PropertyId::AnimationPlayState:
      {
        return ValueId::Running;
      }
      case PropertyId::AnimationTimingFunction:
      case PropertyId::TransitionTimingFunction:
      {
        return ValueId::Ease;
      }
      case PropertyId::BackfaceVisibility:
      case PropertyId::ContentVisibility:
      case PropertyId::OverflowBlock:
      case PropertyId::OverflowInline:
      case PropertyId::OverflowX:
      case PropertyId::OverflowY:
      case PropertyId::Visibility:
      {
        return ValueId::Visible;
      }
      case PropertyId::BackgroundAttachment:
      {
        return ValueId::Scroll;
      }
      case PropertyId::BackgroundClip:
      case PropertyId::MaskClip:
      case PropertyId::MaskOrigin:
      {
        return ValueId::BorderBox;
      }
      case PropertyId::BackgroundColor:
      case PropertyId::StrokeColor:
      {
        return ValueId::Transparent;
      }
      case PropertyId::BackgroundOrigin:
      {
        return ValueId::PaddingBox;
      }
      case PropertyId::BackgroundPositionX:
      case PropertyId::BackgroundPositionY:
      case PropertyId::WebkitMaskPositionX:
      case PropertyId::WebkitMaskPositionY:
      {
        return InitialNumericValue {0, CSSUnitType::Percentage};
      }
      case PropertyId::BackgroundRepeat:
      case PropertyId::MaskRepeat:
      {
        return ValueId::Repeat;
      }
      case PropertyId::BlockStepInsert:
      {
        return ValueId::MarginBox;
      }
      case PropertyId::BlockStepRound:
      {
        return ValueId::Up;
      }
      case PropertyId::BorderCollapse:
      {
        return ValueId::Separate;
      }
      case PropertyId::BorderImageRepeat:
      case PropertyId::MaskBorderRepeat:
      {
        return ValueId::Stretch;
      }
      case PropertyId::BorderImageSlice:
      {
        return InitialNumericValue {100, CSSUnitType::Percentage};
      }
      case PropertyId::BoxSizing:
      {
        return ValueId::ContentBox;
      }
      case PropertyId::CaptionSide:
      {
        return ValueId::Top;
      }
      case PropertyId::ClipRule:
      case PropertyId::FillRule:
      {
        return ValueId::Nonzero;
      }
      case PropertyId::Color:
      {
        return ValueId::Canvastext;
      }
      case PropertyId::ColorInterpolation:
      {
        return ValueId::SRGB;
      }
      case PropertyId::ColorInterpolationFilters:
      {
        return ValueId::LinearRGB;
      }
      case PropertyId::ColumnFill:
      {
        return ValueId::Balance;
      }
      case PropertyId::BorderBlockEndColor:
      case PropertyId::BorderBlockStartColor:
      case PropertyId::BorderBottomColor:
      case PropertyId::BorderInlineEndColor:
      case PropertyId::BorderInlineStartColor:
      case PropertyId::BorderLeftColor:
      case PropertyId::BorderRightColor:
      case PropertyId::BorderTopColor:
      case PropertyId::ColumnRuleColor:
      case PropertyId::OutlineColor:
      case PropertyId::TextDecorationColor:
      case PropertyId::TextEmphasisColor:
      case PropertyId::WebkitTextFillColor:
      {
        return ValueId::Currentcolor;
      }
      case PropertyId::BorderBottomLeftRadius:
      case PropertyId::BorderBottomRightRadius:
      case PropertyId::BorderEndEndRadius:
      case PropertyId::BorderEndStartRadius:
      case PropertyId::BorderStartEndRadius:
      case PropertyId::BorderStartStartRadius:
      case PropertyId::BorderTopLeftRadius:
      case PropertyId::BorderTopRightRadius:
      case PropertyId::Cx:
      case PropertyId::Cy:
      case PropertyId::MarginBlockEnd:
      case PropertyId::MarginBlockStart:
      case PropertyId::MarginBottom:
      case PropertyId::MarginInlineEnd:
      case PropertyId::MarginInlineStart:
      case PropertyId::MarginLeft:
      case PropertyId::MarginRight:
      case PropertyId::MarginTop:
      case PropertyId::MinBlockSize:
      case PropertyId::MinInlineSize:
      case PropertyId::OffsetDistance:
      case PropertyId::OutlineOffset:
      case PropertyId::PaddingBlockEnd:
      case PropertyId::PaddingBlockStart:
      case PropertyId::PaddingBottom:
      case PropertyId::PaddingInlineEnd:
      case PropertyId::PaddingInlineStart:
      case PropertyId::PaddingLeft:
      case PropertyId::PaddingRight:
      case PropertyId::PaddingTop:
      case PropertyId::R:
      case PropertyId::ScrollMarginBlockEnd:
      case PropertyId::ScrollMarginBlockStart:
      case PropertyId::ScrollMarginBottom:
      case PropertyId::ScrollMarginInlineEnd:
      case PropertyId::ScrollMarginInlineStart:
      case PropertyId::ScrollMarginLeft:
      case PropertyId::ScrollMarginRight:
      case PropertyId::ScrollMarginTop:
      case PropertyId::ShapeMargin:
      case PropertyId::TextIndent:
      case PropertyId::TransformOriginZ:
      case PropertyId::WebkitBorderHorizontalSpacing:
      case PropertyId::WebkitBorderVerticalSpacing:
      case PropertyId::X:
      case PropertyId::Y:
      {
        return InitialNumericValue {0, CSSUnitType::px};
      }
      case PropertyId::DynamicRangeLimit:
      case PropertyId::WebkitHyphenateLimitLines:
      {
        return ValueId::NoLimit;
      }
      case PropertyId::EmptyCells:
      {
        return ValueId::Show;
      }
      case PropertyId::FieldSizing:
      {
        return ValueId::Fixed;
      }
      case PropertyId::Fill:
      case PropertyId::FloodColor:
      case PropertyId::StopColor:
      {
        return ValueId::Black;
      }
      case PropertyId::FlexDirection:
      {
        return ValueId::Row;
      }
      case PropertyId::FlexWrap:
      {
        return ValueId::Nowrap;
      }
      case PropertyId::GlyphOrientationHorizontal:
      {
        return InitialNumericValue {0, CSSUnitType::deg};
      }
      case PropertyId::Hyphens:
      {
        return ValueId::Manual;
      }
      case PropertyId::ImageOrientation:
      {
        return ValueId::FromImage;
      }
      case PropertyId::JustifyItems:
      {
        return ValueId::Legacy;
      }
      case PropertyId::LightingColor:
      {
        return ValueId::White;
      }
      case PropertyId::LineFitEdge:
      {
        return ValueId::Leading;
      }
      case PropertyId::ListStylePosition:
      {
        return ValueId::Outside;
      }
      case PropertyId::ListStyleType:
      {
        return ValueId::Disc;
      }
      case PropertyId::MaskComposite:
      {
        return ValueId::Add;
      }
      case PropertyId::MaskMode:
      {
        return ValueId::MatchSource;
      }
      case PropertyId::MaskType:
      {
        return ValueId::Luminance;
      }
      case PropertyId::ObjectFit:
      {
        return ValueId::Fill;
      }
      case PropertyId::PerspectiveOriginX:
      case PropertyId::PerspectiveOriginY:
      case PropertyId::TransformOriginX:
      case PropertyId::TransformOriginY:
      {
        return InitialNumericValue {50, CSSUnitType::Percentage};
      }
      case PropertyId::Position:
      {
        return ValueId::Static;
      }
      case PropertyId::PositionVisibility:
      {
        return ValueId::AnchorsVisible;
      }
      case PropertyId::PrintColorAdjust:
      {
        return ValueId::Economy;
      }
      case PropertyId::RubyAlign:
      {
        return ValueId::SpaceAround;
      }
      case PropertyId::ScrollTimelineAxis:
      case PropertyId::ViewTimelineAxis:
      {
        return ValueId::Block;
      }
      case PropertyId::StrokeLinecap:
      {
        return ValueId::Butt;
      }
      case PropertyId::StrokeLinejoin:
      {
        return ValueId::Miter;
      }
      case PropertyId::StrokeMiterlimit:
      {
        return InitialNumericValue {4, CSSUnitType::Number};
      }
      case PropertyId::StrokeWidth:
      {
        return InitialNumericValue {1, CSSUnitType::px};
      }
      case PropertyId::TabSize:
      {
        return InitialNumericValue {8, CSSUnitType::Number};
      }
      case PropertyId::TextAlign:
      case PropertyId::TextAnchor:
      {
        return ValueId::Start;
      }
      case PropertyId::TextDecorationStyle:
      {
        return ValueId::Solid;
      }
      case PropertyId::TextOverflow:
      {
        return ValueId::Clip;
      }
      case PropertyId::TextWrapMode:
      {
        return ValueId::Wrap;
      }
      case PropertyId::TransformBox:
      {
        return ValueId::ViewBox;
      }
      case PropertyId::TransformStyle:
      {
        return ValueId::Flat;
      }
      case PropertyId::TransitionProperty:
      {
        return ValueId::All;
      }
      case PropertyId::WhiteSpaceCollapse:
      {
        return ValueId::Collapse;
      }
      case PropertyId::WebkitBoxDecorationBreak:
      {
        return ValueId::Slice;
      }
      case PropertyId::WebkitRtlOrdering:
      {
        return ValueId::Logical;
      }
      case PropertyId::WebkitRubyPosition:
      {
        return ValueId::Before;
      }
      case PropertyId::WebkitUserModify:
      {
        return ValueId::ReadOnly;
      }
      case PropertyId::WebkitUserSelect:
      {
        return ValueId::Text;
      }
      case PropertyId::CornerBottomLeftShape:
      case PropertyId::CornerBottomRightShape:
      case PropertyId::CornerEndEndShape:
      case PropertyId::CornerEndStartShape:
      case PropertyId::CornerStartEndShape:
      case PropertyId::CornerStartStartShape:
      case PropertyId::CornerTopLeftShape:
      case PropertyId::CornerTopRightShape:
      {
        return ValueId::Round;
      }
      default:
      {
        krys_unreachable();
      }
    }
  }
}
