// <auto-generated>
//   Generated at 2026-09-14 00:45:06 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.Booey/CSS/Properties/PropertyId.hpp"
#include "Krystal.Booey/CSS/Values/ValueId.hpp"
#include "Krystal.Core/Types/RefPtr.hpp"

namespace krys::boo::css
{
  struct PropertyParserResult;
  struct PropertyParserState;

  class TokenRange;
  class Value;

  struct PropertyParsing
  {
    /// @brief Parse and return a single longhand style property.
    KRYS_NODISCARD static RefPtr<Value> ParseStylePropertyLonghand(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Parse a shorthand style property, adding longhands to the provided result collection.
    /// @returns true on success, false on failure.
    KRYS_NODISCARD static bool ParseStylePropertyShorthand(TokenRange &tokens, PropertyId id, PropertyParserState &state, PropertyParserResult &result) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForStyleProperty(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleStyleProperty(PropertyId id) noexcept;

    /// @brief Parse and return a single @counter-style descriptor.
    KRYS_NODISCARD static RefPtr<Value> ParseCounterStyleDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForCounterStyleDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleCounterStyleDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @font-face descriptor.
    KRYS_NODISCARD static RefPtr<Value> ParseFontFaceDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForFontFaceDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleFontFaceDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @font-palette-values descriptor.
    KRYS_NODISCARD static RefPtr<Value> ParseFontPaletteValuesDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForFontPaletteValuesDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleFontPaletteValuesDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @page descriptor.
    KRYS_NODISCARD static RefPtr<Value> ParsePageDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForPageDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligiblePageDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @property descriptor.
    KRYS_NODISCARD static RefPtr<Value> ParsePropertyDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForPropertyDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligiblePropertyDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @function descriptor.
    KRYS_NODISCARD static RefPtr<Value> ParseFunctionDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForFunctionDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleFunctionDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @view-transition descriptor.
    KRYS_NODISCARD static RefPtr<Value> ParseViewTransitionDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForViewTransitionDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleViewTransitionDescriptor(PropertyId id) noexcept;

    // Direct consumers.

    // Exported style property consumers.
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontFeatureSettings(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontSize(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontVariantAlternates(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontVariantCaps(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontVariantEastAsian(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontVariantEmoji(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontVariantPosition(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontWeight(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeBlockEllipsis(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeBlockStepAlign(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeBlockStepInsert(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeBlockStepRound(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeBlockStepSize(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeBorderImageOutset(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeBorderImageRepeat(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeColumnCount(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeColumnGap(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeColumnWidth(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeContinue(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeLineHeight(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeListStyleType(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeMaxLines(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumePerspective(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeRowGap(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeScrollTimelineAxis(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeScrollTimelineName(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeTextBoxTrim(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeTextDecorationLine(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeTextWrapMode(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeTextWrapStyle(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeTransform(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeViewTimelineAxis(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeViewTimelineName(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeWhiteSpaceCollapse(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeContainIntrinsicHeight(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeContainIntrinsicWidth(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeOverscrollBehaviorX(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeOverscrollBehaviorY(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeCornerStartEndShape(TokenRange &range, PropertyParserState &state) noexcept;

    // Exported @font-face descriptor consumers.
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontFaceFontDisplay(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontFaceFontFamily(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontFaceFontFeatureSettings(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontFaceFontWeight(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontFaceFontWidth(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontFaceSizeAdjust(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<Value> ConsumeFontFaceUnicodeRange(TokenRange &range) noexcept;

    // Exported @view-transition descriptor consumers.
    KRYS_NODISCARD static RefPtr<Value> ConsumeViewTransitionNavigation(TokenRange &range) noexcept;

    // Exported shared consumers.
    static RefPtr<Value> ConsumeAxis(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeBlendMode(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeFontWidthAbsolute(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeGeometryBox(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeLineWidth(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeScroller(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeShapeBox(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleAnimationComposition(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleAnimationDirection(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleAnimationDuration(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleAnimationFillMode(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleAnimationIterationCount(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleAnimationName(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleAnimationPlayState(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleBackgroundAttachment(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleBackgroundBlendMode(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleBackgroundClip(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleBackgroundImage(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleBackgroundOrigin(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleBackgroundPositionX(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleBackgroundPositionY(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleBackgroundRepeat(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleContainerName(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleMaskClip(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleMaskComposite(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleMaskImage(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleMaskMode(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleMaskOrigin(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleMaskRepeat(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleScrollTimelineName(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleViewTimelineInset(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleWebkitBackgroundClip(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleWebkitBackgroundOrigin(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleWebkitMaskClip(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleWebkitMaskComposite(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSingleWebkitMaskPositionX(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleWebkitMaskPositionY(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeSingleWebkitMaskSourceType(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeSymbol(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeTimelineRangeName(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeTransformFunction(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeTransformList(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<Value> ConsumeTransitionBehaviorValue(TokenRange &range) noexcept;
    static RefPtr<Value> ConsumeWidthOrHeight(TokenRange &range, PropertyParserState &state) noexcept;
  };
}
