#pragma once

#include "Krystal.Booey/CSS/Parser/Context/ParsedPropertyList.hpp"
#include "Krystal.Booey/CSS/Parser/TokenRange.hpp"
#include "Krystal.Booey/CSS/Properties/PropertyParserState.hpp"

namespace krys::boo::css
{
  class PropertyConsumer
  {
  public:
    /// @brief Parses a shorthand style property from the given tokens and adds the resulting longhand
    /// properties to the given properties list. Returns true if the property was successfully parsed and
    /// added to the list.
    /// @note Implementation is generated by css-properties.generator.py.
    KRYS_NODISCARD static bool ParseShorthandStyleProperty(TokenRange tokens, PropertyParserState &state,
                                                           ParsedPropertyList &properties) noexcept;

    /// @brief Parses a longhand style property from the given tokens and adds it to the given properties
    /// list. Returns true if the property was successfully parsed and added to the list.
    /// @note Implementation is generated by css-properties.generator.py.
    KRYS_NODISCARD static bool ParseLonghandStyleProperty(TokenRange tokens, PropertyParserState &state,
                                                          ParsedPropertyList &properties) noexcept;
  };
}