// <auto-generated>
//   Generated at 2026-09-13 16:15:35 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.Booey/CSS/Properties/PropertyId.hpp"
#include "Krystal.Core/Attributes.hpp"

namespace krys::boo
{
  class PropertyShorthand;

  KRYS_NODISCARD PropertyShorthand AllShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand AnimationShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand AnimationRangeShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BackgroundShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BackgroundPositionShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BlockStepShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderBlockShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderBlockColorShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderBlockEndShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderBlockStartShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderBlockStyleShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderBlockWidthShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderBottomShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderColorShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderImageShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderInlineShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderInlineColorShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderInlineEndShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderInlineStartShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderInlineStyleShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderInlineWidthShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderLeftShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderRadiusShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderRightShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderSpacingShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderStyleShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderTopShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand BorderWidthShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ColumnRuleShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ColumnsShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ContainIntrinsicSizeShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ContainerShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand CornerShapeShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand FlexShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand FlexFlowShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand FontShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand FontSynthesisShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand FontVariantShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand GapShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand GridShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand GridAreaShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand GridColumnShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand GridRowShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand GridTemplateShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand InsetShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand InsetBlockShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand InsetInlineShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand LineClampShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ListStyleShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand MarginShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand MarginBlockShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand MarginInlineShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand MarkerShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand MaskShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand MaskBorderShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand MaskPositionShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand OffsetShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand OutlineShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand OverflowShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand OverscrollBehaviorShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PaddingShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PaddingBlockShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PaddingInlineShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PageBreakAfterShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PageBreakBeforeShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PageBreakInsideShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PerspectiveOriginShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PlaceContentShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PlaceItemsShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PlaceSelfShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand PositionTryShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ScrollMarginShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ScrollMarginBlockShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ScrollMarginInlineShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ScrollPaddingShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ScrollPaddingBlockShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ScrollPaddingInlineShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ScrollTimelineShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand TextBoxShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand TextDecorationShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand TextDecorationSkipShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand TextEmphasisShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand TextWrapShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand TransformOriginShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand TransitionShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand ViewTimelineShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand WhiteSpaceShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand WebkitBackgroundSizeShorthand() noexcept;
  KRYS_NODISCARD PropertyShorthand WebkitMaskPositionShorthand() noexcept;
}
