// <auto-generated>
//   Generated at 2026-09-13 16:15:35 by codegen/css_properties.py
//   Do NOT make any changes to this file. Any changes made to this file will be lost when the code is
//   regenerated.
// </auto-generated>
#pragma once

#include "Krystal.Booey/CSS/Properties/PropertyId.hpp"
#include "Krystal.Booey/CSS/Values/ValueId.hpp"
#include "Krystal.Core/Types/RefPtr.hpp"

namespace krys::boo::css
{
  struct PropertyParserResult;
  struct PropertyParserState;

  class TokenRange;
  class CSSValue;

  struct PropertyParsing
  {
    /// @brief Parse and return a single longhand style property.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseStylePropertyLonghand(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Parse a shorthand style property, adding longhands to the provided result collection.
    /// @returns true on success, false on failure.
    KRYS_NODISCARD static bool ParseStylePropertyShorthand(TokenRange &tokens, PropertyId id, PropertyParserState &state, PropertyParserResult &result) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForStyleProperty(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleStyleProperty(PropertyId id) noexcept;

    /// @brief Parse and return a single @counter-style descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseCounterStyleDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForCounterStyleDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleCounterStyleDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @font-face descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseFontFaceDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForFontFaceDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleFontFaceDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @font-palette-values descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseFontPaletteValuesDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForFontPaletteValuesDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleFontPaletteValuesDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @page descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParsePageDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForPageDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligiblePageDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @property descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParsePropertyDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForPropertyDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligiblePropertyDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @function descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseFunctionDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForFunctionDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleFunctionDescriptor(PropertyId id) noexcept;

    /// @brief Parse and return a single @view-transition descriptor.
    KRYS_NODISCARD static RefPtr<CSSValue> ParseViewTransitionDescriptor(TokenRange &tokens, PropertyId id, PropertyParserState &state) noexcept;

    /// @brief Fast path bare-keyword support.
    KRYS_NODISCARD static bool IsKeywordValidForViewTransitionDescriptor(PropertyId id, ValueId keyword, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static bool IsKeywordFastPathEligibleViewTransitionDescriptor(PropertyId id) noexcept;

    // Direct consumers.

    // Exported style property consumers.
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFeatureSettings(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontSize(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantAlternates(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantCaps(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantEastAsian(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantEmoji(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontVariantPosition(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontWeight(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockEllipsis(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockStepAlign(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockStepInsert(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockStepRound(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBlockStepSize(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderImageOutset(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeBorderImageRepeat(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeColumnCount(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeColumnGap(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeColumnWidth(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeContinue(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeLineHeight(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeListStyleType(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeMaxLines(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumePerspective(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeRowGap(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeScrollTimelineAxis(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeScrollTimelineName(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTextBoxTrim(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTextDecorationLine(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTextWrapMode(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTextWrapStyle(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeTransform(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeViewTimelineAxis(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeViewTimelineName(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeWhiteSpaceCollapse(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeContainIntrinsicHeight(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeContainIntrinsicWidth(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeOverscrollBehaviorX(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeOverscrollBehaviorY(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeCornerStartEndShape(TokenRange &range, PropertyParserState &state) noexcept;

    // Exported @font-face descriptor consumers.
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontDisplay(TokenRange &range) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontFamily(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontFeatureSettings(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontWeight(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceFontWidth(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceSizeAdjust(TokenRange &range, PropertyParserState &state) noexcept;
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeFontFaceUnicodeRange(TokenRange &range) noexcept;

    // Exported @view-transition descriptor consumers.
    KRYS_NODISCARD static RefPtr<CSSValue> ConsumeViewTransitionNavigation(TokenRange &range) noexcept;

    // Exported shared consumers.
    static RefPtr<CSSValue> ConsumeAxis(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeBlendMode(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeFontWidthAbsolute(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeGeometryBox(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeLineWidth(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeScroller(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeShapeBox(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationComposition(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationDirection(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationDuration(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationFillMode(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationIterationCount(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationName(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleAnimationPlayState(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundAttachment(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundBlendMode(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundClip(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundImage(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundOrigin(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundPositionX(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundPositionY(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleBackgroundRepeat(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleContainerName(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskClip(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskComposite(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskImage(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskMode(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskOrigin(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleMaskRepeat(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleScrollTimelineName(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleViewTimelineInset(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitBackgroundClip(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitBackgroundOrigin(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskClip(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskComposite(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskPositionX(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskPositionY(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeSingleWebkitMaskSourceType(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeSymbol(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeTimelineRangeName(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeTransformFunction(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeTransformList(TokenRange &range, PropertyParserState &state) noexcept;
    static RefPtr<CSSValue> ConsumeTransitionBehaviorValue(TokenRange &range) noexcept;
    static RefPtr<CSSValue> ConsumeWidthOrHeight(TokenRange &range, PropertyParserState &state) noexcept;
  };
}
